### ISSUE TITLE
Adding links to About Us section

### ISSUE THREAD

**Issue by AK4266** [UBA-GCOEN/StichHub#102]
### What is the issue?
Instead of leaving the About Us section plainly. We could add GitHub profile links to the Team members on the About Us Page
### Screenshot
![Screenshot 2023-05-24 114156](https://github.com/UBA-GCOEN/StichHub/assets/99728079/0a14ecee-9689-4a4f-adb5-652a8cfcc452)
### Are you willing to work ont this issue
Yes

**Comment by Naresh-chandanbatve** [comment]
Ok gor it looks nice  @AK4266

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by AK4266** [comment]
@sagnik-p Someone has already submitted a PR for this issue
