### ISSUE TITLE
Add hover animation effects to the cards.

### ISSUE THREAD

**Issue by abhinav-m22** [UBA-GCOEN/StichHub#103]
In the "How It Works section", on-hover animations can be added to different cards, in order to improve the UI/UX and maintain the consistency of the web page.

Image reference:

<img width="944" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/113239388/0cb3ee18-e217-4d37-8d4a-7737c22af779">

I want to work on this feature.
Please assign me the task under GSSoC'23.

**Comment by Naresh-chandanbatve** [comment]
Go for it @rahulaarora

**Comment by dhrumishah** [comment]
> Go for it @rahulaarora

What's the update on this issue? Can I work on it?
