### ISSUE TITLE
Add ContributingGuidelines.md

### ISSUE THREAD

**Issue by shanvijha30** [UBA-GCOEN/StichHub#11]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@UBA-GCOEN could you please assign this issue to me.
Thank you!

**Comment by Naresh-chandanbatve** [comment]
Go for it @shanvijha30 
Filename should be CONTRIBUTING.md

**Comment by Naresh-chandanbatve** [comment]
Also include the point to comment on idsue before creating pr.

**Comment by Naresh-chandanbatve** [comment]
And to refer the respective issue in their prs.
No prs will be accepted without issue reference.

You can refer the internet for  the best contributing.md file structure.

**Comment by shanvijha30** [comment]
okay

**Comment by Naresh-chandanbatve** [comment]
Its a request to complete it as early as possible as it is an issential issue....🥲

**Comment by shanvijha30** [comment]
@Naresh-chandanbatve Added PR [#49](https://github.com/UBA-GCOEN/StichHub/pull/49)
