### ISSUE TITLE
Unable to write description of contact us form

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#113]
**Describe the bug**
Unable to type something in the description of the contact us form.

**Screenshots**
![Screenshot (435)](https://github.com/UBA-GCOEN/StichHub/assets/56786344/afcf7c59-5d44-4697-be3b-a46050d2d912)

Please assign me this issue under **GSSOC'23**

**Comment by Naresh-chandanbatve** [comment]
Already resolved
