### ISSUE TITLE
Tailor Details in Tailor Dashboard

### ISSUE THREAD

**Issue by ar-ag** [UBA-GCOEN/StichHub#114]
**Describe the bug**
The details of the logged in tailor inside the tailor dashboard are placeholders rather than the real detail of the tailor

**To Reproduce**
1. SignIn/ Register as a tailor
2. On the left bar, the details of the tailor show : name as 'Mr. Akash Malhotra' and e-mail as 'inaamajay007@gmail.com' which are placeholders instead of the real name and email of the logged in tailor
3. Same is relevant when you click 'Profile' in the left bar.

**Expected behavior**
Instead of the placeholder values, the details of the logged in tailor must be displayed in the Tailor Dashboard.

**Screenshots**
![image](https://github.com/UBA-GCOEN/StichHub/assets/96348217/ad51f581-1673-4b22-bb8e-5839904b7bfd)
In TailorDashboard

![image](https://github.com/UBA-GCOEN/StichHub/assets/96348217/8dbc416d-68a5-4bca-8ec9-522d953e77c4)
In Tailor Profile

**Desktop (please complete the following information):**
 - Windows
 - chrome

**Smartphone (please complete the following information):**
 - Samsung
 - OS: Android
 - chrome

**Additional context**
To solve this issue, the name and email of the user can be taken from the localStorage of the browser and can be displayed, but in profile page to display additional information such as the address, phone no. etc, an additional API will be required which can query the database to get the information of the logged in tailor.

**Comment by ar-ag** [comment]
@Naresh-chandanbatve is the issue valid?

**Comment by Naresh-chandanbatve** [comment]
Go for it @ar-ag

**Comment by ar-ag** [comment]
@Siddhant-Patil0203  it is completed, will push the code by today.

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 it is completed, will push the code by today.

Alright
