### ISSUE TITLE
Contact form not working on the home page

### ISSUE THREAD

**Issue by rahulaarora** [UBA-GCOEN/StichHub#118]
**Describe the bug**
The contact form at the bottom of the home page is not functional.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://stichhub-chi.vercel.app/
2. Scroll down to the bottom contact form
4. Enter the details and submit and nothing happens

**Expected behaviour**
A successfully submitted or error message should be displayed to the user.

**Screenshots**
<img width="287" alt="Screenshot 2023-05-24 at 3 23 09 PM" src="https://github.com/UBA-GCOEN/StichHub/assets/24794534/27a8172b-1d1e-434c-b294-90e9ed7dccfe">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
 - Device: Realme 6
 - OS: Android 11
 - Browser Chrome
 - Version latest

**Additional context**
The submit handler in the code of contact form is not yet implemented.

- [x] There is no similar existing open issue
- [x] This is a part of GSSoC'23

**Comment by rahulaarora** [comment]
> Go for it @rahulaarora

@Naresh-chandanbatve where do you want to receive/store the contact details and messages?

### Possible solutions: 
1. receive the contact messages on your email
2. store them in the database
3. store them in the excel worksheet

**Comment by Naresh-chandanbatve** [comment]
Add message on email
   uba.gcoen@gmail.com

**Comment by Naresh-chandanbatve** [comment]
@rahulaarora
