### ISSUE TITLE
Search functionality is not working

### ISSUE THREAD

**Issue by crocmons** [UBA-GCOEN/StichHub#120]
**Search functionality is not working also the UI of the text in search bar is black color it should be white text color so that it's visible to the user what they are typing in the searchbar.**
![Screenshot (344)](https://github.com/UBA-GCOEN/StichHub/assets/106610322/36d30222-4188-4e84-8571-9b806da98f53)

**Comment by Naresh-chandanbatve** [comment]
Go for it @crocmons
