### ISSUE TITLE
Adding Hover Effects to the Cards in Our Services Section

### ISSUE THREAD

**Issue by SakshiShah29** [UBA-GCOEN/StichHub#127]
**Description:**

I want to update the styling of the cards in our services section and add some hover effects on the button and the card as well

**Reason for Change:**
The current styling does not show  any effects upon hovering

**Current Styling:**
The current styling does not include any hover effects

![image](https://github.com/UBA-GCOEN/StichHub/assets/65860201/e5977ae3-2349-44d2-822a-4fca3174caca)

**Proposed Styling:**
the styling can be changed a bit more by creating a hover effect on the button

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High
I would request you to assign me the issue under GSSoC'23

**Comment by Siddhant-Patil0203** [comment]
Hey @SakshiShah29 
this issue is already created, check issue #96
Therefore I am adding this issue under Duplicate.

thank you for raising the issue though 🙂
