### ISSUE TITLE
Add on hover animation to landing page buttons

### ISSUE THREAD

**Issue by hrshtmlng** [UBA-GCOEN/StichHub#13]
![Web capture_21-5-2023_124058_stichhub-chi vercel app](https://github.com/UBA-GCOEN/StichHub/assets/101478591/f6571b03-c147-4685-81b9-2655d918bb41)
I'm having an idea that we can add some sort of animations on the buttons of navbar when we will hover over it. It will glow kinda

**Comment by Naresh-chandanbatve** [comment]
@hrshtmlng go for it
But thed added effect must be matched with the theme and it should not look contradictory
An underline effect would be preferable.

**Comment by SaurabhBarde-007** [comment]
can you elaborate about the feature you wanted to include in the website

**Comment by hrshtmlng** [comment]
Yeah sure I was thinking that if I could add glowing color when i hover over it must looks better

**Comment by SaurabhBarde-007** [comment]
@hrshtmlng  Where exactly are you expecting the glow effect because the website already contains glow spots in it.

**Comment by hrshtmlng** [comment]
At the place of Home, Our services, How it works, etc.

**Comment by Naresh-chandanbatve** [comment]
Sure you can if it looks good

If it doesn't then simply add underline erfect

**Comment by hrshtmlng** [comment]
Okay so, I'm working on it :)

**Comment by Siddhant-Patil0203** [comment]
@hrshtmlng what's the status ?
