### ISSUE TITLE
[STYLE CHANGE] Tailler-Customer signUp page

### ISSUE THREAD

**Issue by Soulpurr** [UBA-GCOEN/StichHub#130]
**Description:**
I would like to change ui of signUp page for customer and tailer

**Reason for Change:**
They are not that great looking and not that responsive

**Current Styling:**

![scrnli_25_05_2023_20-55-48](https://github.com/UBA-GCOEN/StichHub/assets/92094765/caa42efc-2039-4c88-a6ef-238a74e7031f)

**Comment by Soulpurr** [comment]
@Naresh-chandanbatve pls assign this issue to me under gssoc 23

**Comment by Siddhant-Patil0203** [comment]
Hey @Soulpurr 
Can you pls explain how you are planning to change the UI/UX of the signup page?

**Comment by Soulpurr** [comment]
![login_form_prototype](https://github.com/UBA-GCOEN/StichHub/assets/92094765/da49c751-fa37-4138-9be4-ba39b102a3bd)

Kind of this .
Or you can provide a reference as the original signUp page looks messed up

**Comment by UBA-GCOEN** [comment]
Ok go for it @Soulpurr 
dont change theme and colorings
Just change the height with sizes fonts and make it like the screenshot you provide without changing any content

**Comment by Soulpurr** [comment]
Okk
