### ISSUE TITLE
[STYLE CHANGE] Modify "How it works " Timeline.

### ISSUE THREAD

**Issue by harshit-002** [UBA-GCOEN/StichHub#132]
**Description:**

- Improve styling of the timeline in "How it Works for Customers" and "How it Works for Tailors."
- Reduce the margins for mobile/tablet displays.
- Make a vertical timeline for "How it Works for Customers" and "How it Works for Tailors." sections for Mobile displays for better UI.

[SCREENSHOTS]
<img width="467" alt="Screenshot 2023-05-26 115917" src="https://github.com/UBA-GCOEN/StichHub/assets/95224348/6f1ce255-f6c1-4255-8010-cbd50cfb875c">

<img width="216" alt="Screenshot 2023-05-26 120759" src="https://github.com/UBA-GCOEN/StichHub/assets/95224348/8a50a05b-fb23-4641-9297-6a8a3906f524">

**Comment by Siddhant-Patil0203** [comment]
Hey @harshit-002 
This looks interesting. 
You can start working on this.

**Comment by Siddhant-Patil0203** [comment]
Hey @harshit-002 ,
Is this issue comes under GSSOC'23 ?

**Comment by harshit-002** [comment]
> Hey @harshit-002 , Is this issue comes under GSSOC'23 ?

Yes
