### ISSUE TITLE
Adding 404 Error Page 

### ISSUE THREAD

**Issue by PatilHarshh** [UBA-GCOEN/StichHub#134]
It seems this website not contain 404 error page which is destroing the user experience
![Screenshot (62)](https://github.com/UBA-GCOEN/StichHub/assets/120102234/03a5eb42-a44d-4066-bcf7-cf9ac8d51aa7)

**Comment by PatilHarshh** [comment]
@UBA-GCOEN  please assign it to me

**Comment by Siddhant-Patil0203** [comment]
Hey @PatilHarshh 
I am Assigning this issue to you, you can start working on it 🧑‍💻

**Comment by Siddhant-Patil0203** [comment]
Hey @PatilHarshh 
Does this issue comes under GSSoC'23 ?

**Comment by PatilHarshh** [comment]
yes @Siddhant-Patil0203

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 please add proper label here

**Comment by PatilHarshh** [comment]
gssoc23 must be added @Siddhant-Patil0203
