### ISSUE TITLE
Adding light-dark mode.

### ISSUE THREAD

**Issue by akshaysoni10** [UBA-GCOEN/StichHub#137]
## Description

**Describe the solution you'd like**
I would like to add attractive light-dark mode to make website more creative.

Please give me this task under GSSOC 23.

**Comment by Siddhant-Patil0203** [comment]
Hey @akshaysoni10 
You will be adding a light/dark mode button on the website and the site will be showing the light/dark mode according to that button. I am right?

**Comment by akshaysoni10** [comment]
Yes, that what I meant.

**Comment by Siddhant-Patil0203** [comment]
Sound Cool,
Hey, @akshaysoni10 you can start working on this.

**Comment by M-A-N-I-K** [comment]
@Siddhant-Patil0203 i would like to continue working on this issue. It seems he is not active right now
