### ISSUE TITLE
[BUG] Text not visible in our services

### ISSUE THREAD

**Issue by Soulpurr** [UBA-GCOEN/StichHub#138]
## Description
The text is not visible in our services
**Describe the bug:**
After logging in the text in our services is not visible .I think the text is not there. So please tell me what you want there.

![scrnli_26_05_2023_16-45-47](https://github.com/UBA-GCOEN/StichHub/assets/92094765/8f2b8338-fd99-441e-9a8e-b60ec622946f)

Please assign this to me under gssoc23

**Comment by Siddhant-Patil0203** [comment]
Hey @Soulpurr 

Actually, this was the temporary navbar used,
Can you just add the navbar used on the home page to this page?
I am a Screenshot of home page here :
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/9823f923-41ed-496e-9f1b-da88fbd6f88e)

Can you use the navbar used in the above homepage in this page ?

**Comment by Soulpurr** [comment]
So you want me to replace the navbar of the screenshot that I share with the navbar of screenshot that you shared right?

**Comment by Siddhant-Patil0203** [comment]
> So you want me to replace the navbar of the screenshot that I share with the navbar of screenshot that you shared right?

Yup, Exactly

**Comment by Soulpurr** [comment]
Okk you can assign this to me

**Comment by Siddhant-Patil0203** [comment]
Hey @Soulpurr 
I have assigned you this issue 
You can start working on it.
