### ISSUE TITLE
Website not responsive for big screen

### ISSUE THREAD

**Issue by avnigoyal25** [UBA-GCOEN/StichHub#14]
![Screenshot (105)](https://github.com/UBA-GCOEN/StichHub/assets/91952706/73a631e8-549c-4298-aa42-0a9fcb8f8de1)

i want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
Can you describe which part is not responsive exactly?

**Comment by avnigoyal25** [comment]
i have already put the screenshot

**Comment by Naresh-chandanbatve** [comment]
The issue for navbar has already raised 
Its a good practice to check if the issue is already opened before opening new one.
