### ISSUE TITLE
Landing page css style improvisation

### ISSUE THREAD

**Issue by Vanshika1703** [UBA-GCOEN/StichHub#141]
The text alignment needs to be fixed

**Screenshots or Design Mockups (optional):**![IMG_20230524_220146_771.jpg](https://github.com/UBA-GCOEN/StichHub/assets/122121020/3d86e0d1-5043-494c-898b-1e3d6ae73475)

**Comment by Vanshika1703** [comment]
Please assign me this issue under gssoc2023

**Comment by Siddhant-Patil0203** [comment]
@Naresh-chandanbatve Check this out

**Comment by UBA-GCOEN** [comment]
Can you check it on laptop does the problem is still occurring or not
Then It can be assigned.

**Comment by Vanshika1703** [comment]
Now its ok

**Comment by Naresh-chandanbatve** [comment]
👍 issue can be closed now
