### ISSUE TITLE
[FEATURE REQUEST] : Modifying the form in GET IN TOUCH section and it's integration with formSubmit

### ISSUE THREAD

**Issue by dev-AshishRanjan** [UBA-GCOEN/StichHub#142]
## Description
 **Is your feature request related to a problem? Please describe.** 
The problem is if someone wanted to contact your team, they have to use another email services like gmail, outlook etc.
 
 **Describe the solution you'd like** 

In  GET IN TOUCH form we take some inputs :
 
 - name
 - email
 - phone no
 - message : using non-resizable textarea.
 
 After someone fills this form and click submit button the email is sent directly to your official email.
 We integrate the form using ***formsubmit***.

 ## Additional Information

 **Context**
For reference you can visit - https://www.krashish.live/contact
 
 **Potential Implementation** (optional)
 
 **Screenshots or Mockups** (optional)
 
 **Priority** (optional)
 *Medium*

**Additional Notes** (optional)

**Comment by dev-AshishRanjan** [comment]
I have provided a detailed solution and have implemented the solution myself - https://www.krashish.live/contact

So, if you can assign this to me (under GSSoC'23) I can start working for this site too.

**Comment by Siddhant-Patil0203** [comment]
Hey @dev-AshishRanjan 
You can go ahead with this Issue

Use this Mail Id: uba.gcoen@gmail.com
