### ISSUE TITLE
[BUG] Remove unnecessary package-lock.json file created.

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [UBA-GCOEN/StichHub#143]
## Description

**Describe the bug:**
During development some unnecessary files are added in the project. Like package-lock.json in root folder as well as in /client folder

Remove this two files shown in screenshots

## Screenshots
![Screenshot_20230526_233004](https://github.com/UBA-GCOEN/StichHub/assets/70953218/3016e88b-1488-4c56-961b-55e268051d91)
![Screenshot_20230526_232934](https://github.com/UBA-GCOEN/StichHub/assets/70953218/2ad0f847-90da-439b-9d9d-54a0cb97a901)

**Comment by sil-samriddha** [comment]
I want to contribute under GSSOC'23
Please assign me

**Comment by Naresh-chandanbatve** [comment]
@sil-samriddha go for it
