### ISSUE TITLE
[BUG] Apply input validation

### ISSUE THREAD

**Issue by kailashchoudhary11** [UBA-GCOEN/StichHub#148]
## Description

**Describe the bug:**
I'm able to keep the password field empty while registering
**Expected behavior:**
There should be validation of password and email 
**Actual behavior:**
I should see error messaging saying password field cannot be empty.

**Comment by Siddhant-Patil0203** [comment]
Hey @kailashchoudhary11 
Can you pls provide the steps to reproduce this bug?

**Comment by kailashchoudhary11** [comment]
> Hey @kailashchoudhary11 Can you pls provide the steps to reproduce this bug? and provide screenshot or video, so that I can under it better.

The password thing is working fine but, when I go to register customer page. The email validation is not done. For example if I enter email as Kai@k it is still considered valid but it is invalid.

**Comment by Siddhant-Patil0203** [comment]
> > Hey @kailashchoudhary11 Can you pls provide the steps to reproduce this bug? and provide screenshot or video, so that I can under it better.
> 
> The password thing is working fine but, when I go to register customer page. The email validation is not done. For example if I enter email as Kai@k it is still considered valid but it is invalid.

Can pls tell me how are you going to validate the email?

**Comment by kailashchoudhary11** [comment]
> > > Hey @kailashchoudhary11 Can you pls provide the steps to reproduce this bug? and provide screenshot or video, so that I can under it better.
> > 
> > 
> > The password thing is working fine but, when I go to register customer page. The email validation is not done. For example if I enter email as Kai@k it is still considered valid but it is invalid.
> 
> Can pls tell me how are you going to validate the email?

Ofcourse by creating a list of popular email domains and checking whether the domain provided by user exists in that list.

**Comment by Siddhant-Patil0203** [comment]
Okay @kailashchoudhary11  Go for it
