### ISSUE TITLE
[STYLE CHANGE] Adding scale property

### ISSUE THREAD

**Issue by Monson2002** [UBA-GCOEN/StichHub#149]
**Description:**

I am proposing adding a "scale" css class instead of width increase on hovering over navbar items

**Reason for Change:**

This change will run independently instead of how it was earlier as it won't affect the other navbar items' position

**Screenshots or Design Mockups (optional):**

Before changes
https://github.com/UBA-GCOEN/StichHub/assets/91113152/8b50da95-64b9-42f4-996c-def8f8781640
After changes
https://github.com/UBA-GCOEN/StichHub/assets/91113152/8701845c-2078-4d74-a55d-5f2030d4424c

**Priority Level (optional):**

- [x] Low
- [ ] Medium
- [ ] High

**Comment by Monson2002** [comment]
@Naresh-chandanbatve please review it

**Comment by Siddhant-Patil0203** [comment]
Okay @Monson2002 
Go ahead
