### ISSUE TITLE
[BUG] Preloader loading issue 

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [UBA-GCOEN/StichHub#151]
## Description

**Describe the bug:**
Currently the preloader is defined using CSS so it is not waiting for threejs model to load

**Expected behavior:**
Preloader should stop loading when threejs model is fully loaded 

**Actual behavior:**
Preloader is working only for css loading and stops early before loading threejs model

## Reproduction Steps

**Steps to reproduce the behavior:**

1. Go to 'stichhub-chi.vercel.app'
2. And see the loading behaviour

**Comment by SINJINI-G** [comment]
Hello @Naresh-chandanbatve !! I am willing to work on this issue.. Can you please assign this issue to me under gssoc?

**Comment by Naresh-chandanbatve** [comment]
Go for it @SINJINI-G

**Comment by Dev79844** [comment]
Hey @Naresh-chandanbatve! If someone is not working on this issue, can you assign it to me under GSSOC'23?

**Comment by Naresh-chandanbatve** [comment]
Go for it @Dev79844

**Comment by Dev79844** [comment]
Hey @Naresh-chandanbatve! Can you tell me from where can I get this key: VITE_GOOGLE_CLIENT_ID

**Comment by UBA-GCOEN** [comment]
@sil-samriddha 
Drop the blog link here to get client id

**Comment by Siddhant-Patil0203** [comment]
> Hey @Naresh-chandanbatve! Can you tell me from where can I get this key: VITE_GOOGLE_CLIENT_ID

hey @Dev79844 
checkout this article https://www.balbooa.com/gridbox-documentation/how-to-get-google-client-id-and-client-secret for creating your client id
