### ISSUE TITLE
[FEATURE REQUEST] mailing system

### ISSUE THREAD

**Issue by SINJINI-G** [UBA-GCOEN/StichHub#153]
## Description

**Problem**
There is no mailing system when new user sign up.

**Solution**
I will create an automatic mailing system that will send a customized mail to every new user when he/she signs up.

Can you please assign this issue to me under gssoc?

**Comment by VardaPanchal005** [comment]
I would like to work on this issue

**Comment by UBA-GCOEN** [comment]
> ## Description
> **Problem** There is no mailing system when new user sign up.
> 
> **Solution** I will create an automatic mailing system that will send a customized mail to every new user when he/she signs up.
> 
> Can you please assign this issue to me under gssoc?

Hey @SINJINI-G 
Which mailing service will you be using?

**Comment by SINJINI-G** [comment]
I will use nodemailer

**Comment by Siddhant-Patil0203** [comment]
Okay @SINJINI-G 
Go for it

**Comment by Siddhant-Patil0203** [comment]
Hey @SINJINI-G 
It seems you are already assigned to #154, So kindly Complete that issue first and then work on this issue

**Comment by Aryan20022003** [comment]
Greeting sir ,
sir I would love to work on this feature please assign this to me . I will be using nodeMail to implement it .

- thankyou

**Comment by Siddhant-Patil0203** [comment]
> Greeting sir , sir I would love to work on this feature please assign this to me . I will be using nodeMail to implement it .
> 
> * thankyou

Hey @Aryan20022003 ,
@SINJINI-G is already working on this issue, So I would like to check her progress on this first.
@SINJINI-G Can you pls tell your progress on this issue ?

**Comment by SINJINI-G** [comment]
Hi @Siddhant-Patil0203 !! I have been working on it since yesterday and the work is almost done. Will make a PR by tomorrow.

**Comment by Siddhant-Patil0203** [comment]
> Hi @Siddhant-Patil0203 !! I have been working on it since yesterday and the work is almost done. Will make a PR by tomorrow.

Alright 👍
