### ISSUE TITLE
[FEATURE REQUEST] forgot password in signin

### ISSUE THREAD

**Issue by SINJINI-G** [UBA-GCOEN/StichHub#154]
## Description

**Problem**
There is no forgot password in sign in page

**Solution**
I will add the forgot password button and its functionality.

Please assign this issue to me under gssoc.

## to do issues
- [x] #518
- [ ] otp verification
- [ ] reset password.

**Comment by Naresh-chandanbatve** [comment]
@SINJINI-G i think you are working on other issue
Comment on this issue if you complete previous one i will assign you this one

**Comment by SINJINI-G** [comment]
> @SINJINI-G i think you are working on other issue Comment on this issue if you complete previous one i will assign you this one

Yeah sure.. but that issue would take some time.. but this issue wouldn't take long, already the setup is done.. so I can do this issue first and then start working on that.. will that be fine?

**Comment by Naresh-chandanbatve** [comment]
Ok I will unassign you from that issue which one it was?

**Comment by SINJINI-G** [comment]
> Ok I will unassign you from that issue which one it was?

Is it that I can be assigned only one issue at a time?

**Comment by Naresh-chandanbatve** [comment]
Yes, because it doesn't create confusion.

**Comment by SINJINI-G** [comment]
ok then.. I want to work on this issue first.. you may unassign me from issue #151

**Comment by Naresh-chandanbatve** [comment]
@SINJINI-G have you started working on other issues

**Comment by Naresh-chandanbatve** [comment]
I have added tasks list to follow up issues.

**Comment by Naresh-chandanbatve** [comment]
@niteshtiwari52 it will be assigned to you if @SINJINI-G does not reply till tommorrow.

**Comment by niteshtiwari52** [comment]
Sir please assign this issue to any other developer. I am not able to start due to my other commitment. 
Sorry for inconvenience.
