### ISSUE TITLE
3 feature requests-Design inspiration gallery, Fabric Donations and tutorial for new tailors

### ISSUE THREAD

**Issue by VardaPanchal005** [UBA-GCOEN/StichHub#156]
Educational Resources: Provides resources and guides for aspiring tailors, such as pattern-making tutorials, sewing techniques, and business tips. This fosters a supportive environment and encourages more individuals to pursue their passion for fashion.

or 

Design Inspiration Gallery: Create an online gallery where customers can explore and get inspired by different designs and styles. This can include a collection of fashion look books, runway trends, and customer-submitted photos.(I would like to discuss and then implement the feature for more clarity).

or 

Fabric Donations and Upcycling: Encourage customers to donate their unused fabrics or clothing materials to tailors. The tailors can then upcycle these materials into unique garments, promoting sustainability and reducing waste.

I would like to work on these issues.

**Comment by UBA-GCOEN** [comment]
Go for it you van create task list for these task
To keep track.

**Comment by VardaPanchal005** [comment]
I've been busy with college placements for a while. I will  update it as soon as I get time
