### ISSUE TITLE
UI/UX improvements in DEMO section 

### ISSUE THREAD

**Issue by whodivyanshu** [UBA-GCOEN/StichHub#16]
The bottom buttons are not quite usable and that will hide in smaller screens
![image](https://github.com/UBA-GCOEN/StichHub/assets/86732198/3392c26e-6aa2-4850-b116-18fc76ac5744)

 I will change the UI for that so, any user will be able to see and click button easily
 
 Please Assign me this issue

**Comment by Naresh-chandanbatve** [comment]
Go for it @whodivyanshu 
It must be matching with the theme
