### ISSUE TITLE
[STYLE CHANGE] : On hover of header item, there is a layout shift

### ISSUE THREAD

**Issue by shubhamku044** [UBA-GCOEN/StichHub#161]
**Description:**

When we hover over any of the list items of the header navbar, there is a little layout shift.

**Reason for Change:**

Due to the shift in layout, the user experience may not look. Because also there is not any kind of transition applied.

**Current Styling:**

Currently, on hover, you are increasing the font size.

**Proposed Styling:**

But instead of increasing the font size, we can scale it and add a small transition for a good user experience.

**Comment by shubhamku044** [comment]
Hey, Can you please assign this issue to me, I will fix it.

**Comment by Siddhant-Patil0203** [comment]
Hey @shubhamku044 
I am Assigning this issue to you

**Comment by Siddhant-Patil0203** [comment]
Hey @shubhamku044 
There is already the same issue i.e #149 
Therefore I am marking this issue as a duplicate.
Thankyou for raising the issue though
