### ISSUE TITLE
[Documentation Update] Add Domain Section in README

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/StichHub#162]
Add All the Domains to Preview the Project in the Readme.

The Domains are :
1) https://stichhub.vercel.app
2) https://www.uba-gcoen.com

3) Backend Domain: https://stichhub-backend.vercel.app

**Comment by SakshiShah29** [comment]
I would like to contribute to this issue under GSSoC'23

**Comment by Siddhant-Patil0203** [comment]
Hey @SakshiShah29 
Go Ahead
