### ISSUE TITLE
[Documentation Update] Update Maintainers Section in README

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/StichHub#164]
## Issue ‼️ :
Currently the [Maintainer](https://github.com/UBA-GCOEN/StichHub#maintainers-) Section is like this :
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/984fb713-a83d-49ab-89bc-296dd5e860aa)

## How it should be ✅: 
1) Update the Title from **Maintainers** to **Project Admin**
2) There should be a proper Profile Photo and name of the project admins
3) After Clicking it should Redirect to the Project admin's Social Profile.

## Resources 📃:

1) Project Admins Social Profile links :
  - Siddhant Patil (Project Lead) 
     - Github: https://github.com/Siddhant-Patil0203 
     - LinkedIn: https://www.linkedin.com/in/sidd0203
     - Instagram: https://www.instagram.com/sidd.0203/
     - Twitter: https://twitter.com/Sidd0203
  - Naresh Chandanbatve 
     - Github: https://github.com/Naresh-chandanbatve
     - LinkedIn: https://www.linkedin.com/in/naresh-chandanbatve
     - Instagram: https://www.instagram.com/naresh_chandanbatve/
     - Twitter: https://twitter.com/NareshChandanb1
  - Harshal Lade 
     - Github: https://github.com/LadeHarshal
     - LinkedIn: https://www.linkedin.com/in/harshal-lade-08749a214/
     - Instagram: https://www.instagram.com/harshallade2/
     - Twitter: https://twitter.com/Sidd0203
  - Vishal Kesharwani 
     - Github: https://github.com/vishal10kesharwani
     - LinkedIn: https://www.linkedin.com/in/vishal-kesharwani-1004vs/
     - Instagram: https://www.instagram.com/dev.vishalvsk/
     - Twitter: https://twitter.com/Vishal46255005
  - Saurabh Yadav 
     - Githbu: https://github.com/Saurabb-coder
     - LinkedIn: https://www.linkedin.com/in/saurabh-yadav-469323208/
     - Instagram: https://www.instagram.com/saurabh739/
     - Twitter: https://twitter.com/Sidd0203

_**Note 📝:  Search for the best Readme Admin Template from other repositories or the internet.**_

**Comment by Tushar98644** [comment]
I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Okay @Tushar98644 
Go ahead
