### ISSUE TITLE
[Bug]  Navbar Navigation bug with sections in landing page

### ISSUE THREAD

**Issue by kailashchoudhary11** [UBA-GCOEN/StichHub#174]
We can create separate pages for each of the sections like AboutUs, ContactUs, etc

**Comment by Siddhant-Patil0203** [comment]
> We can create separate pages for each of the sections like AboutUs, ContactUs, etc

Hey @kailashchoudhary11 
Why do you think we should create separate pages for the sections mentioned by you?
What will be its benefits?
Will it improve the user experience ?

**Comment by Naresh-chandanbatve** [comment]
@kailashchoudhary11

**Comment by kailashchoudhary11** [comment]
Yes, It will improve the user experience. As you can see in the below screenshots, the navigations are not working properly. 
![image](https://github.com/UBA-GCOEN/StichHub/assets/75559082/e860f974-e8db-4ca6-9eb8-f82cbbac4407)
![image](https://github.com/UBA-GCOEN/StichHub/assets/75559082/8cb1e04f-eaee-4658-9e2b-f07998ca0540)

**Comment by Siddhant-Patil0203** [comment]
We can adjust the UI of the section with respect to the navbar, and I don't think creating different pages will be a great idea because the section content is not big enough that we should create different pages for them.
And single page websites are more user-friendly for mobile as well as desktop users.
So, we will be not creating a separate page for the sections on the landing page as of now.

thank you for your suggestion @kailashchoudhary11 🙂

**Comment by Siddhant-Patil0203** [comment]
> Yes, It will improve the user experience. As you can see in the below screenshots, the navigations are not working properly. ![image](https://user-images.githubusercontent.com/75559082/241558284-e860f974-e8db-4ca6-9eb8-f82cbbac4407.png) ![image](https://user-images.githubusercontent.com/75559082/241558297-8cb1e04f-eaee-4658-9e2b-f07998ca0540.png)

@kailashchoudhary11 Would you like to fix this UI issue of the navbar navigation and section?

**Comment by kailashchoudhary11** [comment]
@Siddhant-Patil0203 You can assign this to someone else who comments first below this issue.

**Comment by ManavMalhotra** [comment]
I would like to work on this issue and fix the Navbar Navigation bug with sections in the landing page

**Comment by Siddhant-Patil0203** [comment]
Hey @ManavMalhotra 
go for it

**Comment by ManavMalhotra** [comment]
@Siddhant-Patil0203 Please review #248
