### ISSUE TITLE
Desgin gallery

### ISSUE THREAD

**Issue by Vanshika1703** [UBA-GCOEN/StichHub#179]
Can create a gallery where customers can explore  more desgins

**Comment by Siddhant-Patil0203** [comment]
hey @Vanshika1703 
Can you elaborate on your idea? and provide some reference images of how the gallery will look like.

**Comment by Naresh-chandanbatve** [comment]
@Vanshika1703

**Comment by kunal-2002** [comment]
I understand what has to be done here, so assign me this issue under GSSOC'23

**Comment by Siddhant-Patil0203** [comment]
> I understand what has to be done here, so assign me this issue under GSSOC'23

Hey @kunal-2002 
Can you elaborate on what are you planning to do ??
