### ISSUE TITLE
[BUG] main landing page have some glitch

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [UBA-GCOEN/StichHub#18]
The main landing page stucks sometimes while scrolling.

Steps to produce:
      1) run the app on the given hosted link
      2) try to scroll on main landing page

**Comment by SaurabhBarde-007** [comment]
Hello Naresh , I am a GSSOC contributor, could you please assign me this issue.

**Comment by Naresh-chandanbatve** [comment]
Sure go fot it @SaurabhBarde-007

**Comment by iasadk** [comment]
Hello Naresh, I am new to open source but have a good knowledge of full-stack dev so, could you please assign me this issue?

**Comment by SaurabhBarde-007** [comment]
@iasadk bro I am already working on it.

**Comment by iasadk** [comment]
ok bro :)

**Comment by vk20july** [comment]
sir i want to work on this issue under gssoc'23

**Comment by Naresh-chandanbatve** [comment]
Any progress @SaurabhBarde-007

**Comment by vk20july** [comment]
> Any progress @SaurabhBarde-007

sir should I do this as he is not replying

**Comment by Naresh-chandanbatve** [comment]
ok got for it @vk20july

**Comment by vk20july** [comment]
@Naresh-chandanbatve sir can you send the video 
because from my end scrolling button is working fine

**Comment by vk20july** [comment]
> Look at the video it stops at perticular point when scrolled fast
> 
>  landingGlitch.mp4

ok sir got it

**Comment by vk20july** [comment]
> Look at the video it stops at perticular point when scrolled fast
> 
>  landingGlitch.mp4

sir can you assign this issue to someone 
sorry for the inconvenience

**Comment by ManavMalhotra** [comment]
It could be related to the hardware problem or the website loading too many resources. For example, the website has a 3D model and perhaps has large images that take time to load.

**Comment by ManavMalhotra** [comment]
Please assign this task I can work on this issue 

I will try optimizing the images or figure out something else which will fix this issue

**Comment by Naresh-chandanbatve** [comment]
Ok go for it 
@ManavMalhotra

**Comment by ManavMalhotra** [comment]
@Naresh-chandanbatve 
I tried recreating the issue and found that the bug occurs on low-end devices or when the phone can’t handle 3D model processing. This results in a blank screen being displayed for milliseconds when scrolling.

One possible fix I came up with is to replace the 3D models with PNG images for mobile devices only. 

I am working on trying different approaches. If you have any suggestions, please let me know

**Comment by Naresh-chandanbatve** [comment]
3d models are the main factor inour ui so removing it is not a nice option.
look for other aproaches
