### ISSUE TITLE
Feature: Apply input validation on frontend

### ISSUE THREAD

**Issue by kailashchoudhary11** [UBA-GCOEN/StichHub#186]
We can do input validation on the front end as well. This will help us not make unnecessary requests to the backend if the inputs are not valid.

**Comment by Siddhant-Patil0203** [comment]
@Naresh-chandanbatve What do you think?

I think if it's real-time i.e. it shows errors while typing, then it will be great

**Comment by UBA-GCOEN** [comment]
> @Naresh-chandanbatve What do you think?
> 
> I think if it's real-time i.e. it shows errors while typing, then it will be great

Yes @kailashchoudhary11 
Integrate real time frontend input validation.
