### ISSUE TITLE
Readme Updation

### ISSUE THREAD

**Issue by shraddha761** [UBA-GCOEN/StichHub#191]
Add name of admin and mentor ad badges in readme make other contributor to find easily

**Comment by Siddhant-Patil0203** [comment]
I didn't understand what exactly you wanted to say? Can you pls elaborate on your issue ?

**Comment by shraddha761** [comment]
![image](https://github.com/UBA-GCOEN/StichHub/assets/106100728/2600a17f-9929-4b1d-b039-5a0a7878d31c)

We can add name of project admin and mentor in this badges so it will help other to know about admin and mentor

**Comment by Siddhant-Patil0203** [comment]
@shraddha761 
We are adding a project admin section in readme, and the issue is already created for this, check issue #164
