### ISSUE TITLE
[BUG] Spelling error in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aishjahan** [UBA-GCOEN/StichHub#198]
I have reviewed the text and identified some minor spelling mistakes. Here are the corrections with the respective line numbers:

Line 43: "unwelcomed" should be "unwelcome"
Line 60: "warnign" should be "warning"
Line 85: "ban" should be "banned"

Please assign me this issue under GSSoC

**Comment by Siddhant-Patil0203** [comment]
Okay @Aishjahan go for it
