### ISSUE TITLE
Add a preloader to the landing page...

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [UBA-GCOEN/StichHub#2]
It should not be contradictory to landing page theme
mostly use lotte file animated svg

**Comment by sil-samriddha** [comment]
I would like to contribute to this project by adding a pre-loader to the landing page under GSSOC'23.
Please assign this issue to me.

**Comment by Rutujeet** [comment]
I kindly request your consideration in assigning Issue #2 to me. I am eager to take on this task and contribute to the project's success.

**Comment by sil-samriddha** [comment]
Thanks
