### ISSUE TITLE
Adding scroll to Top feature

### ISSUE THREAD

**Issue by Deepanshu0703** [UBA-GCOEN/StichHub#20]
Few long pages must have scroll to Top options i found this issue so solved it and already made a PR .

**Comment by Naresh-chandanbatve** [comment]
It is not good practice to rais pr directly.
You should create an issue and get assigned to it and give reference to issue in your pr.

**Comment by Deepanshu0703** [comment]
Understood, I'll remember that for future reference. Thanks for the suggestion. I will raise this PR again.

**Comment by Abhishek-00** [comment]
Hii,
Can you assign this issue to me.

**Comment by Deepanshu0703** [comment]
Sorry @Abhishek-00 I have already made PR regarding that

**Comment by promise-dash** [comment]
Hey, @Naresh-chandanbatve I would like to solve this issue.
Could you please assign me this?
