### ISSUE TITLE
Interactive Elements Effect

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#203]
**Description:**
Adding some effects like physical state appearance change on hovering the interactive elements like button.

**Reason for Change:**

Currently on-site, there are many interactive elements but on hovering them there is no change which does noy give the proper user experience of interactive elements. Interactive elements suppose to change state on hover

**Current Styling:**

Currently, there is no change on hovering over buttons or other interactive elements other than the appearance of cursor pointer but we can make it change state like background color or add animations.
![WhatsApp Image 2023-05-29 at 6 36 11 PM](https://github.com/UBA-GCOEN/StichHub/assets/86224794/b774398a-0865-459e-b59f-3a7a36102b0c)

**Screenshots or Design Mockups (optional):**

https://github.com/UBA-GCOEN/StichHub/assets/86224794/cbba16a9-8453-4e21-ae90-de04ff3bba1f

**Additional Information (optional):**
I would like to implement the above-like animation on the hover of all buttons on the site. I can implement it for all the buttons to give a consistent look.

**Request** - If you think that the changes will make a difference please assign me this issue under **GSSoC'23** label.

**Comment by Siddhant-Patil0203** [comment]
Hey @AlfiyaSiddique 
Thank you for raising the issue, 
But we have this issue raised already, 
Check issue #96

**Comment by AlfiyaSiddique** [comment]
Okay @Siddhant-Patil0203, So should I close this issue under Close as not a planned option?

**Comment by ayush02av** [comment]
@AlfiyaSiddique Yes please, you can close this issue as not planned.
Thank you.
