### ISSUE TITLE
[STYLE CHANGE]  Enhancing Navbar and Hamburger Menu Links Interaction on Hover and Focus

### ISSUE THREAD

**Issue by Amitavpanda** [UBA-GCOEN/StichHub#210]
**Description:**

The current styling of the navbar links and hamburger menu links lacks visual feedback on hover and focus states, which can significantly enhance the user experience and improve usability. By implementing appropriate styling changes, we can create a more engaging and intuitive navigation experience for our users.

**Reason for Change:**

Providing visual cues on hover and focus states is crucial for several reasons. Firstly, it helps users understand the interactive nature of the links, ensuring they can easily differentiate between static and interactive elements. Secondly, it improves accessibility by assisting users who navigate through keyboard or assistive technologies. Lastly, incorporating consistent and aesthetically pleasing styling can contribute to the overall branding and polish of our project.

**Current Styling:**

Currently, the navbar links and hamburger menu links do not exhibit any visual changes on focus states, and on hover it changes only the text color of the navbar links. This lack of feedback might lead to confusion among users, potentially affecting their navigation experience. 

**Proposed Styling:**

We propose implementing a subtle yet noticeable change to the navbar and hamburger menu links on hover and focus states. The suggested styling could include a change in text color, background color, underline, or any other visually distinguishable effect that aligns with the project's design principles and style guide.

**Priority Level (optional):**

- [ ] Low
- [x] Medium
- [ ] High

**Timeline (optional):**

We aim to have these styling changes implemented within the next two days.

**Possible Implementation Approach (optional):**

Since our project utilizes Tailwind CSS, we can leverage its utility classes and built-in features to implement the hover and focus styling changes for the navbar links and hamburger menu links. Here's a suggested implementation approach:

- Identify the HTML elements representing the navbar links and hamburger menu links.
- Utilize Tailwind CSS utility classes such as `hover:text-[color]` and `focus:text-[color]` to modify the text color on hover and focus states.
- Apply appropriate background color classes, such as `hover:bg-[color]` and `focus:bg-[color]`, to create visual feedback on hover and focus states.
- If desired, utilize additional Tailwind CSS classes or custom CSS to incorporate underline effects or any other desired styling changes.
- Test the implementation across different browsers and devices to ensure consistent behavior and visual appeal.

**I would like to work on this issue under GSSOC'23.**

**Comment by Amitavpanda** [comment]
@Siddhant-Patil0203 I would like to work on this issue under GSSOC'23. Can u please assign this issue to me?

**Comment by ayush02av** [comment]
@Amitavpanda Can you refer to the issue #174 , similar changes are requested in that as well.

**Comment by Amitavpanda** [comment]
@ayush02av No, I gone through the issue, I want to change the styling on hover and focus of navbar links and hamburger menu links, in issue #174, was about to create different pages for different sections.

**Comment by ayush02av** [comment]
@Amitavpanda Yes the issue was originally for creating different pages, but that part was resolved (won't be adding new pages).
But later in the issue thread, UI navigation of the navbar was asked to fix. Can you check that part and comment if your issue relates with that.

**Comment by ayush02av** [comment]
Also, refer to issue #13 for guidelines on the hover effect.

**Comment by Amitavpanda** [comment]
After reviewing issue #13, I am confident that I can handle this task. I assure you that any changes I make will be in line with the current styling of the web app. Please assign this task to me.

**Comment by ayush02av** [comment]
@Naresh-chandanbatve Have gained info on this issue for enhancing the navbar, its navigation and styling.
I believe it's ready to assign, can you please review.

**Comment by Amitavpanda** [comment]
Today I started working on the issue. I have some queries.
![Screenshot (91)](https://github.com/UBA-GCOEN/StichHub/assets/56599943/c74c390b-659d-435c-8a9b-db8d0918bc1a)

how can I get the google client id and stripe key?

**Comment by Naresh-chandanbatve** [comment]
You have to create you Google auth id 
You don't need stripe key

**Comment by Naresh-chandanbatve** [comment]
You have to create you Google auth id 
You don't need stripe key

**Comment by Siddhant-Patil0203** [comment]
Hey @Amitavpanda 
Pls. refer this to get you google auth client id :
https://www.balbooa.com/gridbox-documentation/how-to-get-google-client-id-and-client-secret

@ayush02av pls. make a note of this, and pls share this who ask this in discord or any issues.

**Comment by ayush02av** [comment]
> Hey @Amitavpanda Pls. refer this to get you google auth client id : https://www.balbooa.com/gridbox-documentation/how-to-get-google-client-id-and-client-secret
> 
> @ayush02av pls. make a note of this, and pls share this who ask this in discord or any issues.

Sure, made a note of it.

**Comment by Amitavpanda** [comment]
> Hey @Amitavpanda Pls. refer this to get you google auth client id : https://www.balbooa.com/gridbox-documentation/how-to-get-google-client-id-and-client-secret
> 
> @ayush02av pls. make a note of this, and pls share this who ask this in discord or any issues.

Yeah Sure👍

**Comment by ayush02av** [comment]
@Amitavpanda Can you please check this PR #252

**Comment by AlfiyaSiddique** [comment]
Hello @Naresh-chandanbatve 

I will like to work on this issue if it is not assigned to anyone.

Also can you please review my submitted PRs!!  There are three PRs.

**Comment by Naresh-chandanbatve** [comment]
@AlfiyaSiddique 
sure you can work on it 
changes done by @Amitavpanda are here in pr #252 
you can do further changes.

> Also can you please review my submitted PRs!! There are three PRs.
sure they will be reviewed

**Comment by AlfiyaSiddique** [comment]
Hey @Naresh-chandanbatve 
Assigned issues are easier to keep in account and navigate, can you please assign it to me!!

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve working on this issue, here's what I have implemented so far


https://github.com/UBA-GCOEN/StichHub/assets/86224794/b2c133bb-df30-4315-b6e1-177c3b80c621


**Please provide your suggestions**

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve 
@Siddhant-Patil0203 
Please provide your feedback on this
