### ISSUE TITLE
[FEATURE REQUEST] adding proper footer section on the website

### ISSUE THREAD

**Issue by Iamdivyak** [UBA-GCOEN/StichHub#211]
## Description

there is no footer section available on the website

**Describe the solution you'd like**
I designed this footer section for this site
<img width="1440" alt="footer design" src="https://github.com/UBA-GCOEN/StichHub/assets/102896170/0886846c-3a27-4063-a42b-1a01b5b1e306">

I would like to add this design to your website's footer section

## Additional Information

**Context**
Additionally, I will add some hover effects in the links. and the logo will redirect to the main page

**Additional Notes** (optional)
if you provide me with more social links, I will add that too.

kindly assign this task to me under GSSOC'23 contributor

**Comment by ayush02av** [comment]
@Naresh-chandanbatve Please review this issue, for adding a footer section, I believe it's ready to assign.

**Comment by Siddhant-Patil0203** [comment]
Hey @Iamdivyak 
Go ahead
