### ISSUE TITLE
[BUG] Fix Text in the Landing Page

### ISSUE THREAD

**Issue by Sriparno08** [UBA-GCOEN/StichHub#215]
## Description

I have noticed some typos in the landing page.

## Screenshots

![Screenshot 2023-05-30 185310](https://github.com/UBA-GCOEN/StichHub/assets/89148144/e8f0a228-3fab-476e-8972-62f6bf66f269)

Here are the fixes that need to be applied:

- `whom who want` -> `whom you want`
- `cutomer-base` -> `customer-base`

## Additional Information

**Device (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 113

**Additional context:**

I would like to contribute as part of GSSoC'23.

**Comment by ayush02av** [comment]
Hey @Sriparno08 thank you for noticing and raising this issue.

**Comment by ayush02av** [comment]
@Naresh-chandanbatve This is a minor bug fix, ready to assign. Please review.

**Comment by Michelle031** [comment]
Please can be assigned this issue, I will deliver today. Thank you

**Comment by Siddhant-Patil0203** [comment]
Okay @Sriparno08 ,
I am Assigning you this issue go for it
