### ISSUE TITLE
BUG - Dead page | Explore now | For Customers

### ISSUE THREAD

**Issue by RashakDude** [UBA-GCOEN/StichHub#22]
Hello @Naresh-chandanbatve, 

<img width="75%" alt="Screenshot 2023-05-21 at 10 28 42 PM" src="https://github.com/UBA-GCOEN/StichHub/assets/45696541/106b6d5c-7731-47d2-9e5a-a81540c7bded">

I found out that the customer's page is dead and doesn't respond.
This needs handling of state which is not done properly.
Would like to take this issue for GSSOC.

**Comment by Naresh-chandanbatve** [comment]
@RashakDude go for it
Make the page as active as possible
You can make task lists to track progress if you want

- [x] Navbar mobile button
- [ ] Task 2
- [ ] Task 3
- [ ]  #3

**Comment by vk20july** [comment]
sir I want to work on this issue under gssoc'23

**Comment by Siddhant-Patil0203** [comment]
@RashakDude What is your status?

**Comment by Siddhant-Patil0203** [comment]
> sir I want to work on this issue under gssoc'23

@vk20july Go for it

**Comment by vk20july** [comment]
@Siddhant-Patil0203 sir can you tell me in detail what functionality you need on customer page?

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 sir can you tell me in detail what functionality you need on customer page?

@LadeHarshal Pls look into this

**Comment by Naresh-chandanbatve** [comment]
> @Siddhant-Patil0203 sir can you tell me in detail what functionality you need on customer page?

Make the buttons and linkes active and working.
Also make page as active as possible.

**Comment by vk20july** [comment]
ok sir

**Comment by Naresh-chandanbatve** [comment]
any progress ?
@vk20july @RashakDude
