### ISSUE TITLE
Add Facebook Authentication for Login and Register. {GSSoC '23} 

### ISSUE THREAD

**Issue by youraj-08** [UBA-GCOEN/StichHub#220]
## Description

**The problem addressed by adding Facebook Authentication is the complexity and security risks associated with traditional authentication systems, and the feature aims to simplify the registration process and enhance security for users.**

**Describe the solution you'd like**
The feature entails enabling users to authenticate using their Facebook account with the assistance of Auth0. By implementing this functionality, we can enhance the user experience and provide a seamless onboarding process.

**Describe alternatives you've considered**
 As an alternative one can offer authentication options using other popular social media platforms like Microsoft, Twitter, or GitHub. This allows users to choose the platform they are most comfortable with for logging in and registering.

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Siddhant-Patil0203** [comment]
@youraj-08 
Go ahead

**Comment by LadeHarshal** [comment]
@youraj-08 What is the progress on this one?
