### ISSUE TITLE
[BUG]  Contact form accepting empty inputs

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [UBA-GCOEN/StichHub#221]
#### Steps to reproduce:

1. Go to website
2.  Click on contact us
3.  Without filling the form click on send
4.  Redirects to captcha
5.  Got message "form submitted successfully"

#### I'd like to work on this issue, could you please assign this to me under Gssoc'23 

https://github.com/UBA-GCOEN/StichHub/assets/71914071/1463fa79-c58d-4d4a-85bc-83efe862eede

**Comment by Siddhant-Patil0203** [comment]
Okay @SoundaryaKoutharapu 
I am Assigning you this issue, go ahead

**Comment by rahulaarora** [comment]
Hey, @SoundaryaKoutharapu it has been solved already in #118
