### ISSUE TITLE
[STYLE CHANGE] Redesign Tailor Dashboard UI 

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/StichHub#222]
# Current Tailor Dashboard :

## Desktop View :
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/b5d677b6-1d91-463f-b66c-8eafc18ca6ab)

## Mobile View :
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/0504ae7a-a5e2-44f9-b860-aeffeb42815c)

- I Want someone to Redesign this Dashboard's UI/UX and make it more modern and simplistic, the user should be able to easily use this.
- The Design theme should match with the website theme.
- Sign in to see more dashboard feature 
- to check the ongoing order and order request kindly request an order to your tailor from the customer side i.e. from https://www.stichhub.vercel.app/home

I can assign this issue under **GGSoC'23** ,
Kindly Comment below who all are intrested

**Comment by Siddhant-Patil0203** [comment]
@Parijatkumar 
Go for it, and make amazing design 🙌🤩

**Comment by Parijatkumar** [comment]
hi @Siddhant-Patil0203   In Login Page there should be forgot password section should i go ahead and add that.
![image](https://github.com/UBA-GCOEN/StichHub/assets/84337847/5f1c81da-067b-4678-8421-03850314d799)

**Comment by Parijatkumar** [comment]
Hi @Siddhant-Patil0203    I created the new UI for the registration and login pages. Please review and inform me of any modifications needed.

<img width="1440" alt="Screenshot 2023-06-14 at 6 55 01 PM" src="https://github.com/UBA-GCOEN/StichHub/assets/84337847/52843ee9-ce0e-48de-a76b-8190fec9e90c">

<img width="1440" alt="Screenshot 2023-06-14 at 6 55 10 PM" src="https://github.com/UBA-GCOEN/StichHub/assets/84337847/e8a3baf2-9225-4fb9-8fdb-d966cddab166">

**Comment by Siddhant-Patil0203** [comment]
Hey @Parijatkumar this issue is regarding redesigning the Tailor dashboard, why have you designed the registration page?

**Comment by Parijatkumar** [comment]
hi @Siddhant-Patil0203 I have redesign the dashboard page also 

<img width="1440" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/84337847/c088ed91-c9bc-43a0-9557-c2afaac9a47f">

**Comment by Siddhant-Patil0203** [comment]
Can you design it for dark mode also?

**Comment by Parijatkumar** [comment]
> Hey @Parijatkumar this issue is regarding redesigning the Tailor dashboard, why have you designed the registration page?

I understand your concern. The reason for designing the registration page is to ensure consistency and a seamless user experience throughout the Tailor dashboard. By designing the registration page to match the overall **theme** and **style** of the dashboard, we aim to provide users with a cohesive visual experience.

Maintaining a consistent theme across all pages, including the registration page, helps create a sense of continuity and professionalism. It contributes to the overall aesthetics and usability of the application, making it visually appealing and enhancing user engagement.

If you have any specific requirements or suggestions regarding the design of the Tailor dashboard or the registration page, please feel free to provide more details, and I'll do my best to address your concerns.

**Comment by Parijatkumar** [comment]
> Can you design it for dark mode also?
The light icon just before the notification is for mode change

<img width="1440" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/84337847/09099cb4-6712-496b-8075-fdc0e48d439d">

**Comment by Parijatkumar** [comment]
Hi @Siddhant-Patil0203 I have also redesign the profile and ongoing page

**Comment by Siddhant-Patil0203** [comment]
@Parijatkumar Looks Good
can you start developing Dashboard Pages ?

**Comment by Siddhant-Patil0203** [comment]
> > @Parijatkumar Looks Good can you start developing Dashboard Pages?
> 
> Yes, sure, the UI Is ready. I just need your confirmation. Also, can I get the API Details so that I can add the API to the code? And Let me know the requirements in detail, and I will add them.

Yup, work only on dashboard pages for now, don't work on registration or signup pages as of now, 
@Naresh-chandanbatve Will be guiding you with the requirements.

API details -> just create your own temporary credentials for development for now.

@Naresh-chandanbatve Please look through this and provide the requirements for the dashboard

**Comment by Parijatkumar** [comment]
> > > @Parijatkumar Looks Good can you start developing Dashboard Pages?
> > 
> > 
> > Yes, sure, the UI Is ready. I just need your confirmation. Also, can I get the API Details so that I can add the API to the code? And Let me know the requirements in detail, and I will add them.
> 
> Yup, work only on dashboard pages for now, don't work on registration or signup pages as of now, @Naresh-chandanbatve Will be guiding you with the requirements.
> 
> API details -> just create your own temporary credentials for development for now.
> 
> @Naresh-chandanbatve Please look through this and provide the requirements for the dashboard

@Naresh-chandanbatve   Please share the requirements for the dashboard.

**Comment by Siddhant-Patil0203** [comment]
@Naresh-chandanbatve Pls look into this

**Comment by Parijatkumar** [comment]
> @Naresh-chandanbatve Pls look into this

Please share the requirements for the dashboard.

**Comment by Parijatkumar** [comment]
> > @Naresh-chandanbatve Pls look into this
> 
> Please share the requirements for the dashboard.

Kindly close the task as I have redesigned the tailor dashboard UI.
