### ISSUE TITLE
[FEATURE REQUEST] Footer Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [UBA-GCOEN/StichHub#224]
## Description

**Is your feature request related to a problem? Please describe.**
There is no Footer section in the website . This website needs a good Footer Section . 

**Describe the solution you'd like**
I will make a Footer Section . Which will have Quick links section , Social Media section and other section .  

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by parthpathakpp1** [comment]
Can you assign me this issue under GSSOC'23 .

**Comment by ayush02av** [comment]
Hey @parthpathakpp1 thanks for raising this issue.
But an issue regarding this has already been assigned and is in progress.
Please refer #211 .
Thanks.
