### ISSUE TITLE
[FEATURE REQUEST] Hovering Effect 

### ISSUE THREAD

**Issue by parthpathakpp1** [UBA-GCOEN/StichHub#225]
## Description

**Is your feature request related to a problem? Please describe.**
There is no hovering effect on the cards and buttons . When hover it does not show any effect . 

**Describe the solution you'd like**
I will add hovering effect and animations which will make them it look good .

**Describe alternatives you've considered**

## Additional Information

**Context**

https://github.com/UBA-GCOEN/StichHub/assets/85991449/630c22c5-78d8-4e72-8dc0-c872554fcffc

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by ayush02av** [comment]
Hey @parthpathakpp1 Please refer issue #13 as it refers to same feature, which is already in progress.
Thanks for raising this issue.
