### ISSUE TITLE
[FEATURE REQUEST] ClothesCategory Hovering 

### ISSUE THREAD

**Issue by parthpathakpp1** [UBA-GCOEN/StichHub#227]
## Description

**Is your feature request related to a problem? Please describe.**
There is lot of places where there is no hovering effect . So when somebody hovers it does not show any effect . 

**Describe the solution you'd like**
I will add hovering effect and some cool animations .

**Describe alternatives you've considered**

## Additional Information

**Context**

https://github.com/UBA-GCOEN/StichHub/assets/85991449/145e83fc-10ae-428b-9761-845fec30b6d2

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Siddhant-Patil0203** [comment]
Alright @parthpathakpp1 go for it

**Comment by parthpathakpp1** [comment]
I have raise a PR https://github.com/UBA-GCOEN/StichHub/pull/253 . Please Check .
