### ISSUE TITLE
[FEATURE REQUEST] Hover Effect 

### ISSUE THREAD

**Issue by parthpathakpp1** [UBA-GCOEN/StichHub#229]
## Description

**Is your feature request related to a problem? Please describe.**
There is no hovering effect on the images in How it Works section . 

**Describe the solution you'd like**
I can add some hovering effect and animations to make them look good . 

**Describe alternatives you've considered**

## Additional Information

**Context**

https://github.com/UBA-GCOEN/StichHub/assets/85991449/92b29ba6-c8c6-43f8-b2c7-4333c8f109af

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Siddhant-Patil0203** [comment]
Okay @parthpathakpp1 go ahead

**Comment by parthpathakpp1** [comment]
I have raise a PR https://github.com/UBA-GCOEN/StichHub/pull/255 . Please Check .
