### ISSUE TITLE
[BUG] Links not working 

### ISSUE THREAD

**Issue by parthpathakpp1** [UBA-GCOEN/StichHub#230]
## Description

**Describe the bug:**
When we click on the social media icons . It redirects us to to same page . 

**Expected behavior:**
It should redirect to to their respective page . 

**Actual behavior:**
When clicked on the Social Media icons . It redirects to the same page . 

## Reproduction Steps

**Steps to reproduce the behavior:**

**Expected result:**
It should redirect to their respective Social Media platforms . 

**Actual result:**
A clear and concise description of what actually happened at each step.

## Screenshots
![stichlabissue4](https://github.com/UBA-GCOEN/StichHub/assets/85991449/7588f911-8ed5-4cb0-8b7b-eec4b861650a)

## Additional Information

**Device (please complete the following information):**
- OS: [Windows
- Browser [Chrome]
- Version [e.g., 22]

**Additional context:**

**Comment by Siddhant-Patil0203** [comment]
Hey @parthpathakpp1 , Currently We are not having all the social media accounts, so you can:
1.  remove the instagram, Twitter , whatsapp icon from there
2. For **Email icon** -> add this: **mailto:uba.gcoen@gmail.com** 
3. For **youtube icon** -> add this link : **https://youtu.be/EV6m7hZ4RKU**  

I am assigning you this issue.

**Comment by parthpathakpp1** [comment]
> Hey @parthpathakpp1 , Currently We are not having all the social media accounts, so you can:
> 
> 1. remove the instagram, Twitter , whatsapp icon from there
> 2. For **Email icon** -> add this: **[mailto:uba.gcoen@gmail.com](mailto:uba.gcoen@gmail.com)**
> 3. For **youtube icon** -> add this link : **https://youtu.be/EV6m7hZ4RKU**
> 
> I am assigning you this issue.

@Siddhant-Patil0203 Could you help me to setup the project locally . I am unable to setup it locally .

**Comment by parthpathakpp1** [comment]
I have raised a PR https://github.com/UBA-GCOEN/StichHub/pull/254 . Please Check .

**Comment by Komallamba17** [comment]
i would like to work on this project. please assign it to me.

**Comment by Siddhant-Patil0203** [comment]
> i would like to work on this project. please assign it to me.

Hey @Komallamba17 ,
@parthpathakpp1 is already working on this issue and has almost resolved it.
Pls checkout other issues or find bug on our website stichhub.vercel.app , Thank you 👨‍💻
