### ISSUE TITLE
[FEATURE REQUEST] Creating an FAQ section

### ISSUE THREAD

**Issue by abhi03ruchi** [UBA-GCOEN/StichHub#236]
## Description

**Is your feature request related to a problem? Please describe.**
I would like to create a FAQ section for site, which answers the basic Qs of the user. 
It would be redirected to the contact us page

**Describe the solution you'd like**
Sample :-> 
<img width="712" alt="Screenshot 2023-06-01 at 8 30 07 AM" src="https://github.com/UBA-GCOEN/StichHub/assets/105661636/ab8b21d2-9bc9-4c52-b8ec-562537de541c">

If you have any other questions or need further assistance, Please don't hesitate to _**contact**_ our customer support team. We are here to help you!

**Describe alternatives you've considered**
Plz assign this task to me under gssoc'23.

**Comment by Siddhant-Patil0203** [comment]
Hey @abhi03ruchi Go for it, and design a nice one ✨😍
