### ISSUE TITLE
[STYLE CHANGE] Imporve the footer of ClothesCategory page

### ISSUE THREAD

**Issue by dhrumishah** [UBA-GCOEN/StichHub#237]
The current styling of footer in ClothesCategory page needs to be aligned well with the rest of the page

![image](https://github.com/UBA-GCOEN/StichHub/assets/84569241/cf9c180b-ecd2-4b42-8f46-eb78398887fd)

**Comment by Siddhant-Patil0203** [comment]
Hey @dhrumishah 
It is also not responsive : 
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/637ebb09-239a-4d1b-bc9b-927f6e45f484)


So kindly,
1. **Align it** and,
2. Also make it **responsive**.

I am assigning you this task.

**Comment by LadeHarshal** [comment]
@dhrumishah What is the current status?
