### ISSUE TITLE
[FEATURE REQUEST] add role based access control

### ISSUE THREAD

**Issue by muttaqin1** [UBA-GCOEN/StichHub#241]
hello i am interested to implement this feature.

**Comment by Siddhant-Patil0203** [comment]
Hey @muttaqin1 , kindly elaborate on your issue. So that I can get a brief idea of your issue

**Comment by Siddhant-Patil0203** [comment]
Hey @Naresh-chandanbatve Check this out

**Comment by muttaqin1** [comment]
@Naresh-chandanbatve  @Siddhant-Patil0203  can you please delete this issue?

**Comment by Siddhant-Patil0203** [comment]
> @Naresh-chandanbatve @Siddhant-Patil0203 can you please delete this issue?

You have already closed the issue, no need to delete it
