### ISSUE TITLE
[BUG] cloth category section 

### ISSUE THREAD

**Issue by Soulpurr** [UBA-GCOEN/StichHub#244]
## Description

**Describe the bug:**
Scroll in x axis is getting out of page
Or we can overflow in x axis in cloth section 

https://github.com/UBA-GCOEN/StichHub/assets/92094765/8244638c-3636-4dee-a998-089b95100db1

https://github.com/UBA-GCOEN/StichHub/assets/92094765/e64a089c-7513-4874-a2e5-f18d640822d9

This issue arises in mobile devices
Pls assign this to me under gssoc23

**Comment by Siddhant-Patil0203** [comment]
Hey @Soulpurr 
I checked the issue, so it does not happen with all mobile devices, but happens with some of them,
Kindly make it responsive for all mobile devices.
I am assigning you these issues.
