### ISSUE TITLE
[STYLE CHANGE]: Improve Navbar Styling and Spacing

### ISSUE THREAD

**Issue by khairalanam** [UBA-GCOEN/StichHub#247]
**Description:**

The styling of the website has inconsistent spacing as well as a rough user experience. I am thinking of improving the website styling starting with the navigation bar.

**Reason for Change:**

As mentioned above, the website looks clunky and needs better styling.

**Current Styling:**

> The padding of the website is set as per individual elements and not as the whole navigation bar.
> The hover states for the nav elements are not smooth.
> Same applies to the "Get Started" button plus the issues with spacing

**Proposed Styling:**

> Remove the padding and margin for the individual elements and set the same for the whole nav element.
> Add transition duration for the default states in the nav elements
> Add the transition duration for the button.
> Change the padding of the button

**Comment by khairalanam** [comment]
I would like this issue to be assigned to me.

**Comment by ayush02av** [comment]
Hey @khairalanam  thanks for raising this issue.
Can you please refer issue #210 . Navbar styling and hover effects is an issue that's already being worked on.
Can you explain how different is your issue in terms of that?

**Comment by khairalanam** [comment]
I have gone through the issue and I would say the aspects of dealing with hover effects are the same. However, it doesn't address the issues of the improper spacing of the elements in the navbar. What I mean to say is that, going through the code for the Navbar component, the margin and padding are set based on the logo and the "Get Started" button respectively, and not the navbar as a whole. I wanted to set the spacing for the navbar for the parent element (i.e navbar) instead of setting it based on the child elements.

**Comment by khairalanam** [comment]
There are no performance issues. Just the minor user interface issues.

**Comment by ayush02av** [comment]
Okay I'm assigning you this issue. Go ahead for it.

**Comment by khairalanam** [comment]
Thank you so much! Just forgot to say I am doing this as part of GSSoC.

**Comment by LadeHarshal** [comment]
@khairalanam Has the issue been resolved?
