### ISSUE TITLE
Lower text is not visible in "Configurator" Page

### ISSUE THREAD

**Issue by imdebamrita** [UBA-GCOEN/StichHub#25]
The page :
![image](https://github.com/UBA-GCOEN/StichHub/assets/108591503/94e984d4-2156-48ad-8563-211de316cdba)

The portion of text which is not visible there:
![image](https://github.com/UBA-GCOEN/StichHub/assets/108591503/984fe57c-7065-4be7-9af0-a0f3ba513919)

Please assign me to this issue.

**Comment by Naresh-chandanbatve** [comment]
Go for it @imdebamrita

**Comment by vk20july** [comment]
I want to work on this issue under gssoc'23

**Comment by Siddhant-Patil0203** [comment]
This Issue has been resolved @imdebamrita , thank you raising the issue
