### ISSUE TITLE
[STYLE CHANGE] :The website is missing hover effect on button

### ISSUE THREAD

**Issue by HimanshuNarware** [UBA-GCOEN/StichHub#251]
**Description:**
The button of the website is missing a hover effect, the hover effect is important for  the website's readability, and I want to   work on this issue kindly assign me this issue

**Reason for Change:**
It will improve the readability as well as UI of the website
**Current Styling:**
Missing hover effect on button

[Describe the current styling that needs to be changed.]

**Proposed Styling:**
I want to give a decent hover effect on the button, which is based on the theme of the website

**Screenshots or Design Mockups (optional):**

https://github.com/UBA-GCOEN/StichHub/assets/83147410/5ba94dc2-98b9-4e2d-bab2-8cf142694ccb

- [ ] Low
- [ ] Medium
- [x] High

**Timeline (optional):**
it take only 1 day

**Comment by ayush02av** [comment]
Hey @HimanshuNarware thanks for raising this issue but hover effects are already being worked on. I'll check on the progress of those issues. Will inform you if this issue needs to be dropped.
