### ISSUE TITLE
Need to create attractive Logo for StichHub

### ISSUE THREAD

**Issue by MohamedMafaz** [UBA-GCOEN/StichHub#258]
Hey there!
I'm Mohamed Mafaz P R. An UI UX Designer & Graphic designer with 3+ Years of Experience. I'm 11th Grade School student, also working as a part-time graphic designer in canadian real estate agency. So, please assign me this issue.

**Comment by ayush02av** [comment]
Hey thanks for showing interest and raising this issue for the website logo.
The logo is the face of a website and a project in general, and changing it would need many iterations before coming to a final logo. And its impact area will also be quite large, all the places elsewhere the logo is being used will have to be changed.
So I would first request you to share screenshots of some sample logos that you've designed earlier and if any ideas for this one.

**Comment by ayush02av** [comment]
@MohamedMafaz Any updates?

**Comment by Naresh-chandanbatve** [comment]
@MohamedMafaz

**Comment by kunal-2002** [comment]
I understand what has to be done here, so assign me this issue under GSSOC'23

**Comment by ayush02av** [comment]
@kunal-2002 Can you share some samples or ideas that you might use?
