### ISSUE TITLE
Adding your profile

### ISSUE THREAD

**Issue by Aakash441** [UBA-GCOEN/StichHub#259]
## Description
After signing in as customer, after clicking on your profile nothing happens. 

**Describe the solution you'd like**
I can add the feature if your profile so that on clicking the customer can see its profile

You can brief me about what you expect in my profile page and I will design it accordingly.

**Comment by ayush02av** [comment]
Hey, thanks for raising this issue.
I request you to please elaborate on your solution.
What type of profile card are you willing to integrate?

Also, if you make a profile section then you also need to give the 'Edit Profile' feature, for that you'll need to integrate with the backend as well, so will you be able to handle that?

**Comment by Aakash441** [comment]
I am thinking at first I would create a basic page which will show the user image, user name, user's measurement if that is appropriate to add. Yes, I can add the edit profile feature too, as I am comfortable working with backend.

**Comment by ayush02av** [comment]
@Naresh-chandanbatve @Siddhant-Patil0203 Can you please look into this issue?
Do we need this user profile section?

**Comment by Siddhant-Patil0203** [comment]
> @Naresh-chandanbatve @Siddhant-Patil0203 Can you please look into this issue? Do we need this user profile section?

@ayush02av  yup sounds cools

**Comment by Siddhant-Patil0203** [comment]
@Aakash441 
Sound Great !! Go ahead with it, and design **your profile** page according to you as of now, then we can modify it 🙂👨‍💻

**Comment by LadeHarshal** [comment]
@Aakash441 How is the progress on this one?

**Comment by Siddhant-Patil0203** [comment]
@Aakash441  ??
