### ISSUE TITLE
Overflow in the trailor resistration form

### ISSUE THREAD

**Issue by HimanshuNarware** [UBA-GCOEN/StichHub#26]
The trailor registration form has overflow issue in it
kindly assign me this issue
![overflow](https://github.com/UBA-GCOEN/StichHub/assets/83147410/442a0109-4fbf-47ee-966a-dae12a5de424)

**Comment by Naresh-chandanbatve** [comment]
Go for @HimanshuNarware 
It should be resolved for all devices please check it
