### ISSUE TITLE
[STYLE CHANGE] Get in Touch Section (Gssoc'23)

### ISSUE THREAD

**Issue by harshit-002** [UBA-GCOEN/StichHub#268]
**Description:**

The current "Get in Touch" Section isn't properly visible completely in the desktop page , we need to scroll down to view it completely.  So, for a better UI I think it should not be required to scroll and the whole section should be visible 

**Current Page:**
<img width="960" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/95224348/5ca65dcc-b1ef-4cbb-9f8a-22cc308aa23d">
(in this ss we can see that some portion of "Get in Touch" Section is cut.

**Comment by harshit-002** [comment]
@ayush02av I meant to reduce the scale of this"Get in Touch" section such that the whole section(from the heading "get in touch" to the send button) is visible without scrolling. Currently, if the heading "Get in Touch" is at the top, then I can't see the send button and I need to scroll.   [ It depends on the screen size so in other devices it may not be an issue ].
Or I should close this issue as it ain't a major UI/UX change?

**Comment by ayush02av** [comment]
@harshit-002 Okay understood your issue now.
So yes this does seem to be a minor issue, but I don't think we should close this right away.
The 'Send' button is a bit out of proportion, and the font size can also be reduced slightly, even the padding of the input fields.
It will make the whole thing compact.

It's good to go from my side but let me confirm with the admin.
@Siddhant-Patil0203 Can you check if this issue makes sense and should be worked on.

**Comment by Siddhant-Patil0203** [comment]
@harshit-002 
Okay go ahead and make it **fit to 100vh** almost all the desktop devices. i.e. it should be responsive 😄
