### ISSUE TITLE
Design Fix for "HOW IT WORKS FOR CUSTOMERS" section

### ISSUE THREAD

**Issue by iasadk** [UBA-GCOEN/StichHub#27]
Hello @Naresh-chandanbatve I would like to give a suggestion for the design of **"HOW IT WORKS
FOR CUSTOMERS ?"** and **"HOW IT WORKS FOR TAILORS ?"** sections. 
Currently, The design of both sections is looking like this which has too many empty areas and looks somewhat abnormal
![image](https://github.com/UBA-GCOEN/StichHub/assets/89456039/3ed3309a-8171-4573-a8fd-34e016c66131)

This is what I'm thinking :
![image](https://github.com/UBA-GCOEN/StichHub/assets/89456039/4a0579c1-5383-48a1-a888-daf499309350)

For responsive Design this will be my approach: 
- On-screen having width <= 768 is currently in grid format so I will hide these lines on those screens
- On-screen having width > 768 is currently in an in-line format so I will display these lines on those screens only

And this is matching with your current design too or do you have any other suggestions??

**Comment by iasadk** [comment]
Kindly Assign this fix to me

**Comment by Harshajny** [comment]
I would like to work on it. Kindly assign this issue to me.

**Comment by iasadk** [comment]
I have already raised the PR for this Issue
