### ISSUE TITLE
[Enhancement] : Add a  footer [GSSOC'23]

### ISSUE THREAD

**Issue by itsmohit097** [UBA-GCOEN/StichHub#270]
## Description
There is no better footer.

**Describe the solution you'd like**
A better footer will enhance the overall website user interface.

**Design of the footer**
![Green and White Photographic Blogger Bio-Link Website](https://github.com/UBA-GCOEN/StichHub/assets/125040386/22fc7b9a-f5f9-4bf3-9815-db36c09a4640)

**Describe alternatives you've considered**
While coding the design i think to make it transparent and have a box shadow to look more better

**Comment by itsmohit097** [comment]
@ayush02av  I was not aware of that issue was already raised regarding this. But still i am seeing that there is no progress of footer added to the website. If no one is working i can do this within 1 day and also design it better than now.

**Comment by ayush02av** [comment]
@itsmohit097 Okay it might not be merged with the main branch, but it must be in progress.
Let me check on the status of those issues and get back to you on this later.

**Comment by itsmohit097** [comment]
@ayush02av  okay let me know whatever the situation is.
