### ISSUE TITLE
Adding Hover Effects in buttons [GSSOC'23]

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [UBA-GCOEN/StichHub#274]
## Description

**Describe the bug:**
There are no hover effect in some buttons

**Expected behavior:**
I will be adding a minimal hover in the buttons

**Actual behavior:**
No hover

## Screenshots
![image](https://github.com/UBA-GCOEN/StichHub/assets/85278243/5d62e308-96df-4757-86fc-a69682875c7c)
![image](https://github.com/UBA-GCOEN/StichHub/assets/85278243/8d1904f9-fb37-43eb-9247-03b428baa903)

Please assign me this issue under GSSOC'23

**Comment by ayush02av** [comment]
Hey thanks for raising this issue, but hover effects issue is already being worked on.

**Comment by Swapnil-Singh-99** [comment]
Ok
