### ISSUE TITLE
Log out feature of the navbar does not work

### ISSUE THREAD

**Issue by ar-ag** [UBA-GCOEN/StichHub#28]
The Log out feature of inside the <code>Navbardark.jsx</code> is redirecting to '#' rather than performing logging out.

I can solve the problem, so could the team please assign me this issue

**Comment by Naresh-chandanbatve** [comment]
Can you provide steps to produce the bug..?

**Comment by ar-ag** [comment]
When we register as a 'tailor' onto the website, we are directed to the 'TailorProfileVerification'

The 'Log Out' button located in the Navbar, during these verification steps does not work because in the codebase it is simply <code>a</code> tag with <code>href</code> set to '#'.

![image](https://github.com/UBA-GCOEN/StichHub/assets/96348217/43e4dfd4-e721-47f3-842b-dd272a168b44)

In this page.

**Comment by ar-ag** [comment]
@Naresh-chandanbatve is the question answered?

**Comment by Naresh-chandanbatve** [comment]
Ok go fir it @ar-ag 
Make logout feature working there.
And redirect it to appropriate location
