### ISSUE TITLE
[BUG] Make the profile image in leftview.jsx dynamic

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [UBA-GCOEN/StichHub#281]
Make the profile image in leftview.jsx dynamic
      
    if someone does not have profile then add default one

_Originally posted by @Naresh-chandanbatve in https://github.com/UBA-GCOEN/StichHub/issues/233#issuecomment-1585739997_

**Comment by ar-ag** [comment]
@Naresh-chandanbatve I can resolve this issue, please assign this to me.
