### ISSUE TITLE
The About Us & our services are not properly seen

### ISSUE THREAD

**Issue by shimmer12** [UBA-GCOEN/StichHub#282]
**Description:**

the The About Us & our services are not properly seen when clicked from the task bar 

**Reason for Change:**

the The About Us & our services are not properly seen when clicked from the task bar 

**Current Styling:**

![Screenshot 2023-06-10 230615](https://github.com/UBA-GCOEN/StichHub/assets/92056170/a9c9cf54-5d19-4f58-ba08-3b0544b3eb26)
![Screenshot 2023-06-10 230603](https://github.com/UBA-GCOEN/StichHub/assets/92056170/721c5be0-3ae1-400f-8c14-c194873767f1)

**Proposed Styling:**

I would like to align it to be properly formatted

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by shimmer12** [comment]
please assign me under gssoc label

**Comment by ayush02av** [comment]
Hey thanks for raising this issue.
As far I've understood this one, it seems that the headings are note properly visible at once when you click on the links, right?
It's possible due to the navbar height and can be solved by adding some space on the top of each of the mentioned sections which will make it more visible.

Am I right? Or which other approach are you considering to solve this issue?

**Comment by shimmer12** [comment]
Yes, @ayush02av I am also thinking of the same solution by adding more space as you described or I can explore the option of reducing the navbar size also. 
Let me work on this and raise the request.

**Comment by ayush02av** [comment]
Noted. Just one thing. Don't change the navbar size, that might have another various dependencies. Just tweak the section heading/spacing.
Go for it, I'm assigning this issue to you.

**Comment by Siddhant-Patil0203** [comment]
hey @ayush02av this issue has already been resolved, check the website and pls. this issue if resolved
