### ISSUE TITLE
[FEATURE REQUEST] Add icons to social

### ISSUE THREAD

**Issue by sumitkr2000** [UBA-GCOEN/StichHub#283]
## Description

**Is your feature request related to a problem? Please describe.**
I want to add icons to the social. Please assign me this issue. Thank you!

**Describe the solution you'd like**
Add icons of github and twitter.

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Siddhant-Patil0203** [comment]
hey @sumitkr2000 where do you want to add the social icons?

**Comment by sumitkr2000** [comment]
I want to add it here in the red part of the screenshot:-

![Screenshot 2023-06-12 224920](https://github.com/UBA-GCOEN/StichHub/assets/100675296/80963b51-b562-4e4e-8bdb-e1fdfa94f8ee)

**Comment by Siddhant-Patil0203** [comment]
@sumitkr2000  okay go ahead

**Comment by sumitkr2000** [comment]
@Siddhant-Patil0203 Bro docker compose is not running in my terminal. I will be not able to work on this project. sorry.

**Comment by sumitkr2000** [comment]
is it necessary to setup odcker to run frontend only?
