### ISSUE TITLE
[FEATURE REQUEST] Add testimonial section

### ISSUE THREAD

**Issue by sumitkr2000** [UBA-GCOEN/StichHub#284]
## Description

**Is your feature request related to a problem? Please describe.**
I want to add a testimonial section where customers and tailors can give testimonials about how this website has helped them.

**Describe the solution you'd like**
Add testimonial section

**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by Siddhant-Patil0203** [comment]
hey @sumitkr2000 where will you be adding the testimonial section, is it on the Main landing page?

**Comment by sumitkr2000** [comment]
Where ever you say...if you want it on the landing page I can add it on the landing page else I can create a new page for testimonials.

**Comment by Siddhant-Patil0203** [comment]
@sumitkr2000  okay go ahead and add it to a landing page

**Comment by LadeHarshal** [comment]
@sumitkr2000 How is work on testimonial section going?

**Comment by sumitkr2000** [comment]
@Siddhant-Patil0203 i told you to help me to go through the code....i added the testimonials section but it's not showing. Can you help me?

**Comment by sumitkr2000** [comment]
@Siddhant-Patil0203 Can you get connected on discord for 2 minutes?

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 i told you to help me to go through the code....i added the testimonials section but it's not showing. Can you help me?

Sure

**Comment by sumitkr2000** [comment]
Are u free rn?

**Comment by Siddhant-Patil0203** [comment]
I joined the Duo channel, but i guess you where not online at that moment.
Can you describe what exactly you are facing with the issue?

**Comment by Siddhant-Patil0203** [comment]
hey @sumitkr2000 can you pls pin me your forked repository and tell me where this issue is arising ?

**Comment by sumitkr2000** [comment]
> hey @sumitkr2000 can you pls pin me your forked repository and tell me where this issue is arising ?

The problem is solved now. It's almost done. I will create the pr today.
