### ISSUE TITLE
[FEATURE REQUEST] Implement lazy loading to the pages

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#285]
## Description

**Is your feature request related to a problem? Please describe.**
Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience.

**Describe the solution you'd like**
I would like to implement lazy loading for all the pages of the website

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Siddhant-Patil0203** [comment]
Okay @Avinash905 
Go for it 
and can you also add some website-related or theme-related loading animation ??

**Comment by Avinash905** [comment]
> Okay @Avinash905 Go for it and can you also add some website-related or theme-related loading animation ??

ok
