### ISSUE TITLE
Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#286]
## Description

**Is your feature request related to a problem? Please describe.**
The website does not have meta tags like open graph, twitter, etc. This means that the website is less likely to be visible in search results, and users are less likely to click on the website's links.

**Describe the solution you'd like**
Add important meta tags. This will help the website rank higher in search results and attract more visitors.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Siddhant-Patil0203** [comment]
Sound Appropriated 📈
@Avinash905 Go ahead
