### ISSUE TITLE
[STYLE CHANGE] Change the style of the filter modal

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#289]
**Description:**

The modal that appears when the filter button is clicked is too big in size but the contents occupy very less space which does not look visually good from a perspective of a user.

**Proposed Styling:**

I would like to improve the styling of the current modal similar to the website's design.

**Screenshots:**
The current view looks like this:
![Screenshot (477)](https://github.com/UBA-GCOEN/StichHub/assets/56786344/39139a30-59db-4df9-bb19-e4b56644befd)

**Comment by Siddhant-Patil0203** [comment]
@Avinash905 
go for it
