### ISSUE TITLE
Contact us UI improvements 

### ISSUE THREAD

**Issue by yashpreet2707** [UBA-GCOEN/StichHub#29]
I will improve the buttons ( currently it is not looking good ) (not user retaining ig ) and some minor changes in the form given.
Please assign me this issue under GSSoC'23. Really looking forward to contribute to it.

<img width="1408" alt="Screenshot 2023-05-22 at 12 55 23 AM" src="https://github.com/UBA-GCOEN/StichHub/assets/111020648/f62f98fc-6ee8-4d99-a89b-22581b188418">

**Comment by Harshajny** [comment]
I would like to work on this issue. Please do assign me to it.

**Comment by Naresh-chandanbatve** [comment]
Wich buttons exactly
Navbar is already being resolved
#38

**Comment by yashpreet2707** [comment]
@Naresh-chandanbatve I was actually suggesting to change the icons before 
Your name 
Email 
Phone number etc.
They are not looking professional

**Comment by Harshajny** [comment]
Are you hoping to do it in a creative way?   I didn't understand.

**Comment by yashpreet2707** [comment]
Yes I'll try, and if it suits your view than, you can merge the PR else you can close it.

**Comment by Naresh-chandanbatve** [comment]
Ok @yashpreet2707 go for it

**Comment by yashpreet2707** [comment]
@Naresh-chandanbatve, I'm having some issues setting up this project locally, I haven't used docker before, can you please help me out.

**Comment by Siddhant-Patil0203** [comment]
@Naresh-chandanbatve check this issue

**Comment by yashpreet2707** [comment]
hey @Naresh-chandanbatve, I am having some issues setting up the project locally. Can you please help me with that? I've sent you a DM on Discord as well.

**Comment by yashpreet2707** [comment]
hey @Naresh-chandanbatve, I think it is already updated now. Someone has fixed it already
