### ISSUE TITLE
Create Issue forms

### ISSUE THREAD

**Issue by dakshsinghrathore** [UBA-GCOEN/StichHub#295]
## Description

Currently the contributor has to raise an issue from ground zero without any ***prebuilt forms***, to gain a better understanding of the issue raised we can create ***custom issue forms*** which will be ***visually appealing*** as well as be ***hassle free*** for the contributor to express their concern in an ***ordered manner*** .

**Is your feature request related to a problem? Please describe.**

My feature request isn't related to a problem but in the hindsight if we don't introduce issue forms to your repo, it might get cumbersome of a task to read the markdown.

**Describe the solution you'd like**

Currently 👇
![Screenshot 2023-06-13 at 23-28-28 New Issue · UBA-GCOEN_StichHub](https://github.com/UBA-GCOEN/StichHub/assets/115932772/83c45088-add0-44dd-a5a9-6fb4d30f9c74)
 
Coming 👇

![Screenshot 2023-06-13 at 23-28-00 New Issue · priyankarpal_ProjectsHut](https://github.com/UBA-GCOEN/StichHub/assets/115932772/ddab78a8-99ad-4c78-ad35-525a7d30e89b)

**Describe alternatives you've considered**

## Additional Information

**Context**

I will be deleting all the existing .md for the issuetemplates and add ***yaml code*** for the respective forms.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

**Comment by dakshsinghrathore** [comment]
Kindly assign this issue to me @UBA-GCOEN

**Comment by Naresh-chandanbatve** [comment]
Go for it @dakshsinghrathore
