### ISSUE TITLE
[FEATURE REQUEST] Typewriter effect in the main text

### ISSUE THREAD

**Issue by Anshika-Jain02** [UBA-GCOEN/StichHub#304]
## Description

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
*We can add a typewriter effect in the below heading to give a dynamic effect and to improve the visual appearance of the overall website.*

**Screenshots or Mockups** (optional)
![image](https://github.com/UBA-GCOEN/StichHub/assets/104912087/ee2e2259-a390-4be0-a4d2-02c7ea403f42)

@Naresh-chandanbatve please assign me this issue under gssoc'23

**Comment by ayush02av** [comment]
Hello @Anshika-Jain02 Thanks for raising this issue. Which library are you planning to use for this? Or can you do this with custom scripts?

**Comment by LadeHarshal** [comment]
@Anshika-Jain02 Are you working on this one? Whats the status here?

**Comment by Siddhant-Patil0203** [comment]
> Hello @Anshika-Jain02 Thanks for raising this issue. Which library are you planning to use for this? Or can you do this with custom scripts?

@Anshika-Jain02 pls ans this

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 Hi. Sorry for the delayed response. I am planning to use the Typewriter library from the 'typewriter-effect' but if this doesnot work i will try some other techniques.

Alright 🙌, Go for it
