### ISSUE TITLE
Contact Form validation [BUG] 

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#308]
## Description

**Describe the bug:**
I can submit the contact form even with an empty message in **describe your issue** field and also there is no validation constraints in the form, for example, I can submit a form in which the phone number field contains alphabets instead of the number

**Expected behavior:**
The form must only be submitted when valid inputs are provided like a proper phone number and a proper description of the issue. I would also like to add inline validation in this form as in the sign-in and register form to maintain the validation system consistency.

## Scrrenshot
<img width="869" alt="1" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/eed6d697-f34a-4e33-9e00-5e2ba1de93aa">

## Conclusion
The **describe your issue** field should have a limit of 20 to 100 words in my opinion, let me know if you want to change this constraint.

If you find this worth implementing please assign me this issue under gssoc label.

**Comment by its-vikash** [comment]
Great! @AlfiyaSiddique
I am assigning this issue to you.
