### ISSUE TITLE
feat: password visibility toggle

### ISSUE THREAD

**Issue by SINJINI-G** [UBA-GCOEN/StichHub#31]
I will add the password visibility toggle feature in customer and tailor authentication pages.

Can you assign this issue to me for gssoc?

# After update 
![Screenshot (5)](https://github.com/UBA-GCOEN/StichHub/assets/98143022/0163b359-ef79-495d-9a84-675efe1c4b51)

**Comment by Naresh-chandanbatve** [comment]
Go for it @SINJINI-G

**Comment by SINJINI-G** [comment]
Can you please put the level tag? @Naresh-chandanbatve
