### ISSUE TITLE
[FEATURE REQUEST] Add 404 error component

### ISSUE THREAD

**Issue by abhi03ruchi** [UBA-GCOEN/StichHub#311]
## Description

**Is your feature request related to a problem? Please describe.**
RightNow, No error message is displayed for unknown routes.I would like to add a 404 page for unknown routes.

## Additional Information
Plz, assign this issue to me under gssoc'23.

**Comment by ayush02av** [comment]
Hey @abhi03ruchi thanks for raising this issue. Can you share some examples or ideas you have planned for the error page?

**Comment by abhi03ruchi** [comment]
Sample : 

- I will customize the page based on the project.
- Add back to the home button on it. 

<img width="1434" alt="Screenshot 2023-06-17 at 11 55 02 AM" src="https://github.com/UBA-GCOEN/StichHub/assets/105661636/cad74710-7f5e-4878-b258-2d05ea4c2b27">

**Comment by ayush02av** [comment]
Cool this looks good. @Naresh-chandanbatve Can you check this?

**Comment by its-vikash** [comment]
@abhi03ruchi Create a page showing disconnection or error using things related to Stiching like scissors, measuring tapes,, buttons, clothes, cut pieces of remaining clothes etc...Organize all these things on a single page and try to make ERROR 404 using all above mentioned objects so that is should resemble the shop of tailor and try to make it creative.

**Comment by its-vikash** [comment]
@abhi03ruchi  You can add these messages too on error page :
1."Oops! Looks like the thread got tangled!"
2."Measure twice, cut once, but we seem to have lost our way!"
3."Sorry, it seems the button came undone, and this page is nowhere to be found!"
4."Oh no! Our tape measure snapped, and this page has gone missing!"

**Comment by Siddhant-Patil0203** [comment]
Hey @abhi03ruchi we already have a 404 page **check https://stichhub.vercel.app/xysdfsdf**

**Comment by Siddhant-Patil0203** [comment]
> @abhi03ruchi You can add these messages too on error page : 1."Oops! Looks like the thread got tangled!" 2."Measure twice, cut once, but we seem to have lost our way!" 3."Sorry, it seems the button came undone, and this page is nowhere to be found!" 4."Oh no! Our tape measure snapped, and this page has gone missing!"

This is Cool @its-vikash ,

@abhi03ruchi Update the existing 404 page with this msg displaying randomly

**Comment by akanksha984** [comment]
@Naresh-chandanbatve please assign this to me
