### ISSUE TITLE
Adding Auto_comment.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [UBA-GCOEN/StichHub#314]
*We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance*

@Naresh-chandanbatve Please assign me this issue under gssoc'23

**Comment by Naresh-chandanbatve** [comment]
@Anshika-Jain02  it is already integrated
