### ISSUE TITLE
[FEATURE REQUEST] FilterSection Filter is not funtcional.

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#315]
## Description

**Is your feature request related to a problem? Please describe.**
The **filter dropdown in the tailor's dashboard is not functional**. It does not filter based on the provided category. Also, the dropdown does not close automatically on clicking on one of the category which is expected as default behaviour of any dropdown.

**Describe the solution you'd like**
I want to make the dropdown filter functional. I will implement it using react states and by adding some category tag to each tailor if enough tailor info is not there. I will test it thoroughly to make sure everything works fine.

## Screenshot
<img width="222" alt="1" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/d7eaa96a-dd55-459b-9aea-30c058e4ad55">

If you find this feature worth implementing please assign me this issue under the gssoc'23 label.

**Comment by Siddhant-Patil0203** [comment]
Okay @AlfiyaSiddique Go for it
