### ISSUE TITLE
[STYLE CHANGE] Enhance the Footer Design 

### ISSUE THREAD

**Issue by abhi03ruchi** [UBA-GCOEN/StichHub#318]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

I would like to improve the design of the footer. 

### Reason for Change:

- The Footer contains a Links section, which is redundant and not required as a sticky navbar is present. 
- Improve the overall UI of the footer.

### Current Styling:

<img width="1284" alt="Screenshot 2023-06-18 at 8 46 10 AM" src="https://github.com/UBA-GCOEN/StichHub/assets/105661636/52b75996-378b-49b3-86e3-2d8c448d8c18">

### Proposed Styling:

Sample:- 

<img width="638" alt="Screenshot 2023-06-18 at 8 58 37 AM" src="https://github.com/UBA-GCOEN/StichHub/assets/105661636/3af3ebf8-7086-4752-80aa-8abe9bf564e5">

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by its-vikash** [comment]
Go for it @abhi03ruchi
