### ISSUE TITLE
On navbar get started button is not align properly

### ISSUE THREAD

**Issue by SubhamB2003** [UBA-GCOEN/StichHub#319]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Hey, on the navbar the GET STARTED button is not aligned properly. 

If you think it needs to be fixed then please assign it to me under GSSOC'23.

### Reason for Change:

N/A

### Current Styling:

you can see here 

![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/ec865745-b108-4d60-9353-d4efdbf7bf62)

### Proposed Styling:

It should be align like this 

![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/1ec098e2-177a-41b8-8716-e6c0a34211c3)

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Okay @SubhamB2003 go for it
