### ISSUE TITLE
BUG:text not visible in customer page search bar

### ISSUE THREAD

**Issue by Soulpurr** [UBA-GCOEN/StichHub#321]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Text is not visible in customer page search bar.
Pls assign this to me under gssoc23

### Add ScreenShots

[scrnli_18_06_2023_22-11-52.webm](https://github.com/UBA-GCOEN/StichHub/assets/92094765/60eed139-c3af-4c2e-bc95-bc1b11107b3f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by its-vikash** [comment]
@Soulpurr please go for it.
I am assigning this issue to you
