### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by SubhamB2003** [UBA-GCOEN/StichHub#326]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Hey, I want to improve the tailor details cards. 

### Reason for Change:

It's not looking good that much. The button is too close to each other 
![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/1ad9ecf0-b603-47c1-825b-ec09a1f07984)

Also the text alignment is not proper
![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/1c641ac9-2d9b-4446-bac1-0362305b9d21)
,

### Current Styling:

![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/789dab60-1a99-4e74-80d9-aca05de67e21)

### Proposed Styling:

I am willing to contribute to it can you please assign it to me under GSSOC'23?

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
hey @SubhamB2003 
Go for it
