### ISSUE TITLE
Feat: Hover effect on Get started button in navbar.

### ISSUE THREAD

**Issue by akshaysoni10** [UBA-GCOEN/StichHub#327]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add hover effect on Get Started button.

### Add Screenshots

Add catchy hover effect.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Okay @akshaysoni10 
Go for it
