### ISSUE TITLE
Feat: Add hover effect on Register and Sign in button in Customer & Tailor.

### ISSUE THREAD

**Issue by akshaysoni10** [UBA-GCOEN/StichHub#328]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add hover effect on Sign in and Register button in Customer & Tailor registration form.

### Add Screenshots

![Screenshot (111)](https://github.com/UBA-GCOEN/StichHub/assets/109035961/19de8c29-3e9e-48f6-9d7d-e98faafb9bf0)
![Screenshot (112)](https://github.com/UBA-GCOEN/StichHub/assets/109035961/a3f4fea0-373d-478f-a317-cf9aa5e8ed5a)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@akshaysoni10 
Go ahead
