### ISSUE TITLE
[STYLE CHANGE]Tailer verification page not responsive 

### ISSUE THREAD

**Issue by Soulpurr** [UBA-GCOEN/StichHub#329]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

The tailer verification page is not yet optimised for mobile screens .
![Screenshot_2023-06-20-12-50-34-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/UBA-GCOEN/StichHub/assets/92094765/ce851089-fe27-4c00-a5f8-4cd25bbde3ff)

### Reason for Change:

Page should be responsive.

### Current Styling:

We need to change the styling to make it responsive for smaller screens

### Proposed Styling:

Adding styling for a particular breakpoint will help.

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Go for it @Soulpurr
