### ISSUE TITLE
Add Pull request template

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [UBA-GCOEN/StichHub#33]
Add a good template including all essential information required to make a Pull Request
In .github/pull_request_template.md

**Comment by Laxmankohar** [comment]
Hey @Naresh-chandanbatve , I would like to work on this issue under GSSoc23. Can you assign it to me?

**Comment by rahulaarora** [comment]
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots

## Before

## After

**Include video if needed**
