### ISSUE TITLE
BUG: Not Proper linking (Buttons are not working

### ISSUE THREAD

**Issue by PatilHarshh** [UBA-GCOEN/StichHub#330]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Buttons not working

### Add ScreenShots

![Screenshot (88)](https://github.com/UBA-GCOEN/StichHub/assets/120102234/0b02eaf3-6647-44d9-823e-61bd66c56115)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 please assign me

**Comment by PatilHarshh** [comment]
![Screenshot (89)](https://github.com/UBA-GCOEN/StichHub/assets/120102234/3115eaf2-f54c-4d66-8aac-b75f4cc30b02)
@Siddhant-Patil0203 what you want to add here

**Comment by Siddhant-Patil0203** [comment]
> ![Screenshot (89)](https://user-images.githubusercontent.com/120102234/247076973-3115eaf2-f54c-4d66-8aac-b75f4cc30b02.png) @Siddhant-Patil0203 what you want to add here

@PatilHarshh 
Here We are thinking to add a List of tailor shops where people can alter their clothes

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 please assign me

@PatilHarshh 
Okay Go for it

**Start Stitching** Button must take you to /home route
**Try now** button should take you to /configurator route

**Comment by PatilHarshh** [comment]
> > ![Screenshot (89)](https://user-images.githubusercontent.com/120102234/247076973-3115eaf2-f54c-4d66-8aac-b75f4cc30b02.png) @Siddhant-Patil0203 what you want to add here
> 
> @PatilHarshh Here We are thinking to add a List of tailor shops where people can alter their clothes

May i Proceed to this issue as well? @Siddhant-Patil0203 ??

**Comment by PatilHarshh** [comment]
by creating issue ?

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 need figma design for it (for Above)

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 need figma design for it (for Above)

We haven't Designed this page yet,
For now, you can design it on your own 

You can take a reference from this though
![Tailor_List-Sidd-Dark](https://github.com/UBA-GCOEN/StichHub/assets/77800620/9441e5a6-f165-461b-91c8-7cd3e055c2e3)
