### ISSUE TITLE
[STYLE CHANGE] Hovering Effect 

### ISSUE THREAD

**Issue by PatilHarshh** [UBA-GCOEN/StichHub#331]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Want to add Hovering Effect Here

### Reason for Change:

Makes Pretier

### Current Styling:

non-Hovering Effects

### Proposed Styling:

Hovering Outlines

### Screenshots or Design Mockups (optional):

![Screenshot (90)](https://github.com/UBA-GCOEN/StichHub/assets/120102234/0233523d-1512-44a1-8407-a51c04437af6)

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 please assign me

**Comment by Siddhant-Patil0203** [comment]
@PatilHarshh Go for it

**Comment by LadeHarshal** [comment]
@PatilHarshh How is the progress on this issue?
