### ISSUE TITLE
BUG: footer link 

### ISSUE THREAD

**Issue by mandliyarajendra11** [UBA-GCOEN/StichHub#333]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

after sign in/cloth category footer-section  when we click on about us contact us social media link and any other section of footer  then 
we navigate to the other website like tailwind css etc

### Add ScreenShots

![Screenshot (124)](https://github.com/UBA-GCOEN/StichHub/assets/119125519/51b571b5-a975-412d-a606-82553d0654e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Okay @mandliyarajendra11 fix this
