### ISSUE TITLE
[STYLE CHANGE] after sign up

### ISSUE THREAD

**Issue by mandliyarajendra11** [UBA-GCOEN/StichHub#334]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

After signing in, you are directed to a new page. Why not add that new page to the old navbar (before signing up) with the name "Cloth Page"? This way, the previous home page and other sections will still be accessible, and the new page will also be included. The navbar after signing up, which includes the search box, filters, etc., can be transformed into a left sidebar and placed in the Cloth Page

### Reason for Change:

we cant access the old page after sign up and new page header and footer is not looking good not accessable in some pages

### Current Styling:

before sign page header and footer looking good and we can access other section also 

but after sign up we cant access other pages of the website

### Proposed Styling:

The navbar after signing up, which includes the search box, filters, etc., can be transformed into a left sidebar and placed in the Cloth Page
and cloth page we can add after the contact us in navbar 

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@mandliyarajendra11 Can you please elaborate more, I am not able to understand your issue

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11 Can you please elaborate more, I am not able to understand your issue

ok we can connect on discord vc ??

**Comment by Siddhant-Patil0203** [comment]
> > @mandliyarajendra11 Can you please elaborate more, I am not able to understand your issue
> 
> ok we can connect on discord vc ??

Yeah, sure
