### ISSUE TITLE
[STYLE CHANGE] mobile responsive

### ISSUE THREAD

**Issue by mandliyarajendra11** [UBA-GCOEN/StichHub#335]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

after sign up  new home page is not responsive

### Reason for Change:

Mobile devices, such as smartphones and tablets, have become the primary means of accessing the internet for many people. It's crucial to cater to this large user base and provide an optimal experience for them.
Users expect websites to be accessible and functional on their mobile devices.

### Current Styling:

scrollbar left to right
width of navbar more than 100vw

### Proposed Styling:

page should be mobile responsive

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @mandliyarajendra11 Can you please share the Screenshots of this please.

**Comment by mandliyarajendra11** [comment]
> Hey @mandliyarajendra11 Can you please share the Screenshots of this please?

![Screenshot (127)](https://github.com/UBA-GCOEN/StichHub/assets/119125519/9426dede-af42-471f-a005-8837ba94fd77)

**Comment by mandliyarajendra11** [comment]
> Hey @mandliyarajendra11 Can you please share the Screenshots of this please?

sorry i did not update my local repo
so this issue already solved
