### ISSUE TITLE
Feat: Add Testimonial page

### ISSUE THREAD

**Issue by smty2018** [UBA-GCOEN/StichHub#337]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Want to add a testimonials page to the website.

### Add Screenshots

want to add testimonials after the faq and before the about us section.
![image](https://github.com/UBA-GCOEN/StichHub/assets/74114936/05b9e522-a3a9-40a0-aa45-bb592058d3c4)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by smty2018** [comment]
@Siddhant-Patil0203 please assign me this issue under gssoc'23

**Comment by Siddhant-Patil0203** [comment]
Hey @smty2018 
Issue #284 has already been raised for the testimonial Section,
Check issue #284 and pin me if you want to work on issue #284
