### ISSUE TITLE
BUG:  Text overflows in the card

### ISSUE THREAD

**Issue by thezeeshann** [UBA-GCOEN/StichHub#338]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

In the customer and tailor section **Already a user?  sign in** the text overflows in the card.

I want to work on this issue. Please assign me. @Siddhant-Patil0203 @Naresh-chandanbatve @LadeHarshal @Saurabb-coder @vishal10kesharwani 

### Add ScreenShots

![screencapture-stichhub-vercel-app-auth-tailor-2023-06-20-21_51_02](https://github.com/UBA-GCOEN/StichHub/assets/88139550/c1f5bf26-358b-4d67-a0ef-f19d4db4f7eb)
![screencapture-stichhub-vercel-app-auth-customer-2023-06-20-21_50_34](https://github.com/UBA-GCOEN/StichHub/assets/88139550/e961330b-09d9-410c-8b00-07d5e4db89b3)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
In which device you are seeing this,
It is not overflowing in most of the devices

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 Laptop. but on my device I see text overflowing.

Okay @thezeeshann make it responsive for all the devices and dimensions
