### ISSUE TITLE
BUG: Tailor Verification Steps are not mandotory

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#343]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Problem
Tailor Verification steps are not mandatory. I can just click on proceed buttons without inserting any data into asked fields and in the end, the tailor is verified successfully without even providing any data.

## Proposed solution
I want to make the functionality such that the user can proceed to the next step only once he/she has filled in the detail of the current steps properly. In this way, we will get the proper data from the tailor and the tailor will be verified properly. I will also add inline validation in all the input fields where required.

### Add ScreenShots

https://github.com/UBA-GCOEN/StichHub/assets/86224794/ba2c79e3-3503-4968-913b-4eed4ef4805a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
hey @AlfiyaSiddique , sounds great
Go for it.

**Comment by AlfiyaSiddique** [comment]
Hey @Siddhant-Patil0203, I am implementing the following constraints for different fields in tailorverification.

**Country:** can't be empty and Min 4 characters (cause the country with the smallest name has 4 characters in it)
**street address:** can't be empty Or (Here we can add min 3 words requirement as well, what do you say?)
**Town City:** can't be empty 
**State:** can't be empty
**Pin code:**  can't be empty


**Personal Identity Verification:** Making all the fields required.

**Add your Description or bio:** Min 10 and Max 50 words
**Confirm Specialit**ies:  can't be empty
**Select your Price Range:** can't be empty

If you think any of the constraints of the above field should be different then let me know.

**Comment by Siddhant-Patil0203** [comment]
> Hey @Siddhant-Patil0203, I am implementing the following constraints for different fields in tailorverification.
> 
> **Country:** can't be empty and Min 4 characters (cause the country with the smallest name has 4 characters in it)
> **street address:** can't be empty Or (Here we can add min 3 words requirement as well, what do you say?)
> **Town City:** can't be empty 
> **State:** can't be empty
> **Pin code:**  can't be empty
> 
> 
> **Personal Identity Verification:** Making all the fields required.
> 
> **Add your Description or bio:** Min 10 and Max 50 words
> **Confirm Specialit**ies:  can't be empty
> **Select your Price Range:** can't be empty
> 
> If you think any of the constraints of the above field should be different then please let me know.
>  

@AlfiyaSiddique great go ahead with it and make the street address as it can't be empty
