### ISSUE TITLE
Feat: Verifying Phone Number

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#344]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Problem
In the tailor verification first step the phone number is just asked from the user but not actually verified. We can actually verify the phone number by implementing sms functionality in nodejs. We can use free sms API for this purpose.

## Proposed Idea
We can use OTP functionality for verifying phone numbers. The OTP will be sent to the phone number provided by the user and the user has to insert the OTP in an input field and if the opt matched then the phone number is verified.

### Add Screenshots

..

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @AlfiyaSiddique 
Which SMS API are your planing to use?

**Comment by AlfiyaSiddique** [comment]
Hello @Siddhant-Patil0203 
I am planning for using either **[MessageBird](https://messagebird.com/)** or **[TextLocal](https://www.textlocal.in/)**.

MessageBird provides a free account with a limited number of credits.

TextLocal has a free service of 10 messages per Bundle

<img width="830" alt="5" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/37dc87b2-e3a9-4d0c-ab52-c99d71628c44">

Most probably there is no API with a complete free SMS service. Every free service has some limitations.
So I guess to start with we can use one of these free services.

 What do you say?

**Comment by Siddhant-Patil0203** [comment]
@AlfiyaSiddique, yup we can start with any of these services.
Go ahead and make this verification working, tag me if you need any help or have a query.

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique, yup we can start with any of these services. Go ahead and make this verification working, tag me if you need any help or have a query.

Sure, Thank you👍🏻

**Comment by AlfiyaSiddique** [comment]
Hey @Siddhant-Patil0203 

I have started working on this issue but unfortunately, the messagebird API no longer provides free credits and the textlocal API requires DLT registration to use it so most probably we can't use it either.

But the good thing is I have tried one more API called **Twilio** and it gives limited $16.0 free credits. I have implemented it and it's working perfectly but once the credits are consumed we have to buy it again.

So can I go ahead with this Twilio API?

**Comment by AlfiyaSiddique** [comment]
@Siddhant-Patil0203 can you please share your suggestions on the above 👆🏻

**Comment by Siddhant-Patil0203** [comment]
> Hey @Siddhant-Patil0203
> 
> I have started working on this issue but unfortunately, the messagebird API no longer provides free credits and the textlocal API requires DLT registration to use it so most probably we can't use it either.
> 
> But the good thing is I have tried one more API called **Twilio** and it gives limited $16.0 free credits. I have implemented it and it's working perfectly but once the credits are consumed we have to buy it again.
> 
> So can I go ahead with this Twilio API?

@AlfiyaSiddique Alright Go ahead with it
