### ISSUE TITLE
[STYLE CHANGE] : TAILOR DETAILS UI 

### ISSUE THREAD

**Issue by Hemant2335** [UBA-GCOEN/StichHub#345]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

As of now the Tailor details page is now looking that pleasant , so i wanted to give it a try to make it more better

please assign this issue to me under gssoc

thank you

here ss
 
![Screenshot (159)](https://github.com/UBA-GCOEN/StichHub/assets/85656999/a261a2b5-5947-4b3a-b42b-677e66c6b916)

### Reason for Change:

the current styling is not correctly align and also not that good.

### Current Styling:

There are some basic changes which are completely need to be changed.

### Proposed Styling:

I would like to completely design this to a new one 

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Alright @Hemant2335 Go for it

**Comment by Hemant2335** [comment]
Ok l'm on it
