### ISSUE TITLE
BUG: ClothesCategory page footer wrong link

### ISSUE THREAD

**Issue by SubhamB2003** [UBA-GCOEN/StichHub#346]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Hey, In this ClothesCategory page, the footer section links are wrong they all are linked to the tailwind CSS website or flowbite.
And I think it needs to be changed

https://github.com/UBA-GCOEN/StichHub/assets/94003231/76c8a6d7-d62e-464c-8c1a-b4c67e0576ff

Also, this section's search bar text is also not visible

https://github.com/UBA-GCOEN/StichHub/assets/94003231/58838d82-8839-4381-bf76-08d18f7d119f

@Siddhant-Patil0203 I want to fix both of them can you please assign it to me under GSSOC'23?
And if it is possible can you add a level 2 label

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey, @SubhamB2003 Go for it.
also, this issue comes under the Level 1 category

**Comment by SubhamB2003** [comment]
> Hey, @SubhamB2003 Go for it. also, this issue comes under the Level 1 category

Ok😓Can I also change the logo bcz it's not properly visible
You can see here
![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/f8446ff0-f8a9-425f-a484-39f325a3e84c)

**Comment by Siddhant-Patil0203** [comment]
> > Hey, @SubhamB2003 Go for it. also, this issue comes under the Level 1 category
> 
> Ok😓Can I also change the logo bcz it's not properly visible You can see here ![image](https://user-images.githubusercontent.com/94003231/247918473-f8446ff0-f8a9-425f-a484-39f325a3e84c.png)

Yup Go ahead
@SubhamB2003

**Comment by SubhamB2003** [comment]
> > > Hey, @SubhamB2003 Go for it. also, this issue comes under the Level 1 category
> > 
> > 
> > Ok😓Can I also change the logo bcz it's not properly visible You can see here ![image](https://user-images.githubusercontent.com/94003231/247918473-f8446ff0-f8a9-425f-a484-39f325a3e84c.png)
> 
> Yup Go ahead @SubhamB2003

Hey, can you please review my previous PR #347

**Comment by mandliyarajendra11** [comment]
> Hey, @SubhamB2003 Go for it. also, this issue comes under the Level 1 category

bro i already did it ......

**Comment by mandliyarajendra11** [comment]
> > Hey, @SubhamB2003 Go for it. also, this issue comes under the Level 1 category
> 
> bro i already did it ......

check issue
#333 and i already send pr for footer

**Comment by Siddhant-Patil0203** [comment]
> > > Hey, @SubhamB2003 Go for it. also, this issue comes under the Level 1 category
> > 
> > 
> > bro i already did it ......
> 
> check issue #333 and i already send pr for footer

@mandliyarajendra11 , Yup I have checked your PR and will be merged soon

**Comment by SubhamB2003** [comment]
> > > > Hey, @SubhamB2003 Go for it. also, this issue comes under the Level 1 category
> > > 
> > > 
> > > bro i already did it ......
> > 
> > 
> > check issue #333 and i already send pr for footer
> 
> @mandliyarajendra11 , Yup I have checked your PR and will be merged soon

Hey, then I only made those two changes Navbar Icon and search bar text
