### ISSUE TITLE
UI/UX Frontend Improvments

### ISSUE THREAD

**Issue by Malay-dev** [UBA-GCOEN/StichHub#35]
UI/UX improvements -

### Adding a scroll to this section would be better - 
<img src="https://github.com/UBA-GCOEN/StichHub/assets/91375797/916ad582-653e-4220-8c9b-5ebc6e83b3b0" width="300">

### In the desktop view, on the configurator page option buttons are not visible -
<img src="https://github.com/UBA-GCOEN/StichHub/assets/91375797/fab7a1a8-6839-49ec-b463-c9f7779f07f1" width="700">

### On the measurements page, in Choose your measurements section a horizontal scroll is present, it would be better to remove it.
<img src="https://github.com/UBA-GCOEN/StichHub/assets/91375797/397d292f-5888-45b7-8479-cb3f6e353237" width="300">

**Comment by Malay-dev** [comment]
I would like to work on this issue, please assign it to me under GSSOC'23

**Comment by Naresh-chandanbatve** [comment]
Go fir it @Malay-dev
