### ISSUE TITLE
BUG: wrongs filter method

### ISSUE THREAD

**Issue by shobhitexe** [UBA-GCOEN/StichHub#350]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

The "Price range" and "Tailor rating" filter methods should be of radio buttons instead of multiselect 

multiselect here doesnt makes that much sense 

Ex: see in below SS price should be under 1000 & above 15000!!

![image](https://github.com/UBA-GCOEN/StichHub/assets/29349136/e3e437b0-e441-4b25-b03b-2fc980fc30fa)

### Add ScreenShots

![image](https://github.com/UBA-GCOEN/StichHub/assets/29349136/1286a5c5-9c85-4cdc-bed2-9d645b0707c4)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @shobhitexe, it makes sense
make that filter in the radio, I am assigning this issue.

**Comment by Siddhant-Patil0203** [comment]
Just to Crosscheck, Are you contributing as GSSoC'23 Contributor?

**Comment by shobhitexe** [comment]
> @shobhitexe Just to Crosscheck, Are you contributing as GSSoC'23 Contributor?

Kindaa you can assign Gssoc tag but
