### ISSUE TITLE
Backend: improvement/refining after stiching needed by customer

### ISSUE THREAD

**Issue by SnehaJaiswal123** [UBA-GCOEN/StichHub#351]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

There are cases when the final order delivered has issues so to request for its restiching and improvement/refining is must. This is a must feature required by user for their positive response.
I will be creating an API for the customer to hit and request for required improvement.

### Add Screenshots

Not found an image to show, basically there will be an improvement button in the order section like refund.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @SnehaJaiswal123 Go for it.
