### ISSUE TITLE
Feat: Add a Prettier Linter Workflow

### ISSUE THREAD

**Issue by abhinav-m22** [UBA-GCOEN/StichHub#352]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

To ensure proper and consistent linting of the codebase, include the prettier linter.

For a project with many contributors to ensure greater code readability for users, a proper linting style must be upheld.

Automated linting checks using the prettier linter in GitHub activities are an ideal way to accomplish this.

### Add Screenshots

I want to work on this issue.
Please assign me the task under GSSoC'23.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @abhinav-m22 Go ahead
