### ISSUE TITLE
Feat: Missing proper alt attributes on img tags

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#356]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Many people just write one or two words explaining about the image in alt attributes which is not the correct way to describe the image.

**Benefits of enhancing the alt attributes include:**

Accessibility: Alt attributes provide essential information to individuals who cannot see the images directly, allowing them to understand the visual content through alternative text descriptions.

Compliance: By following best practices and guidelines, such as those outlined in the Web Content Accessibility Guidelines (WCAG), we can ensure our project meets accessibility standards, which is important for inclusivity and legal compliance.

SEO (Search Engine Optimization): Meaningful alt attributes can improve search engine rankings by providing search engines with more context about the images. This can result in increased visibility and organic traffic to our project.

### Add Screenshots

![Screenshot (518)](https://github.com/UBA-GCOEN/StichHub/assets/56786344/7c84736c-4650-4f86-af78-daa17df97ca0)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Siddhant-Patil0203** [comment]
hey @Avinash905 Go for it
