### ISSUE TITLE
Feat: Optimize Performance by Adding Lazy Loading to Image Tags

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#357]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

As part of optimizing the project's performance, we need to implement lazy loading for the <img> tags used throughout the project. Lazy loading is a technique that defers the loading of images until they are about to be displayed on the user's screen, reducing the initial load time and improving the overall user experience.

To accomplish this, we need to modify the existing <img> tags and add the loading attribute with the value of "lazy". This attribute instructs the browser to delay the loading of the image until it becomes visible within the viewport.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Siddhant-Patil0203** [comment]
Hey @Avinash905 you have already implemented it, check your issue #285, What is the difference between this issue and issue #285

**Comment by Avinash905** [comment]
> Hey @Avinash905 you have already implemented it, check your issue #285, What is the difference between this issue and issue #285

That was for the pages/components and this is for the images

**Comment by Siddhant-Patil0203** [comment]
> > Hey @Avinash905 you have already implemented it, check your issue #285, What is the difference between this issue and issue #285
> 
> That was for the pages/components and this is for the images

Ohh,
@Avinash905 Okay go for it then

**Comment by Avinash905** [comment]
@Naresh-chandanbatve Why did you unassign me?

**Comment by Naresh-chandanbatve** [comment]
it was by mistake

**Comment by Avinash905** [comment]
> it was by mistake

ok no problem
