### ISSUE TITLE
BUG: Convert PNG Images to WebP Format for Improved GitHub Project Performance

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#358]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Currently, the images in our GitHub project are stored in the PNG image format. However, I would like to convert them to the more efficient WebP format. This conversion will help us reduce file sizes while maintaining image quality, leading to improved website performance and faster loading times. This issue aims to update the entire project's image assets from PNG to WebP format.

In order to optimize our project's image assets and enhance user experience, I propose converting all the PNG images to WebP format.

### Add ScreenShots

![Screenshot (519)](https://github.com/UBA-GCOEN/StichHub/assets/56786344/1f1ab95f-54be-4522-9aa2-3d390cd90d01)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Siddhant-Patil0203** [comment]
Hey, @Avinash905 Go for it, 
Just don't change the logo folder, the logos should be in png format.
