### ISSUE TITLE
Bug: '+6 More Measurement' button does not work as expected

### ISSUE THREAD

**Issue by Malay-dev** [UBA-GCOEN/StichHub#36]
### Bug
The '+6 More measurement' button on this section redirects to a blank page - route /Mainpage
<img src="https://github.com/UBA-GCOEN/StichHub/assets/91375797/4b46dff7-aca7-4b7c-adea-de4ce9e2d005" width="450">

Redirected Page:
<img src="https://github.com/UBA-GCOEN/StichHub/assets/91375797/a9166994-7b77-443c-a4b3-23f168ce37ce" width="500">

this unexpected behavior should be fixed.

To reproduce the bug - 
1 - Go through the demo section
2 - Next through the configurator 
3 - Create a new Measurement 
4 - Calculate the measurement - Calculate Button
5 - Now click '+6 Measurement'

**Comment by Malay-dev** [comment]
Hey @Naresh-chandanbatve, I would like to resolve this bug, Please assign it to me under GSSOC'23

**Comment by Naresh-chandanbatve** [comment]
What are gou supposed to add ...

**Comment by Malay-dev** [comment]
So there are a total of 9 Measurements - Chest, Waist, Seat, Bicep, Shirt Length, Shoulder Width, Sleeve Length, Cuff Circumference, and Collar Size for a Shirt (Ref. [https://www.ratioclothing.com/help/measure-a-shirt](Link)). Since already 6 Measurements are placed, we can convert that '+6 Measurements' Button to the '+3 Measurements' Button, which on clicking would display all the 9 Measurements.

**Comment by Naresh-chandanbatve** [comment]
And also solve routing issue 
@Malay-dev go for it..
