### ISSUE TITLE
BUG: customer page menu bug

### ISSUE THREAD

**Issue by mandliyarajendra11** [UBA-GCOEN/StichHub#363]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

https://stichhub.vercel.app/CustomersPage 

max-width 1022

we see navbar icon `≡`

but its not working

### Add ScreenShots

![Screenshot (131)](https://github.com/UBA-GCOEN/StichHub/assets/119125519/acaf4919-f194-4e45-a065-9504e0512ab5)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
This page is dead 
There is already issue where it will be resolved.
#22
