### ISSUE TITLE
Feat:Integrating chat bot in form of chat gpt.

### ISSUE THREAD

**Issue by Soulpurr** [UBA-GCOEN/StichHub#367]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to integrate chat gpt chat bot in home page.

### Add Screenshots

..

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @Soulpurr Go ahead

**Comment by Soulpurr** [comment]
Hey @Siddhant-Patil0203 don't you think it should be level three as it's a entirely new feature?
