### ISSUE TITLE
Change required in img width of "Contact Us" section 

### ISSUE THREAD

**Issue by Monson2002** [UBA-GCOEN/StichHub#37]
Currently "Get in Touch" section of the page looks disproportionately thinner when compared to the image beside it

<img width="960" alt="Screenshot 2023-05-22 085441" src="https://github.com/UBA-GCOEN/StichHub/assets/91113152/c187e68c-afd5-466a-9925-dabc8bffa4cb">

I can decrease the hardcoded width of "p" tag from w-800 to w-400, tom make it look better. After the change it looks like:

<img width="960" alt="updated" src="https://github.com/UBA-GCOEN/StichHub/assets/91113152/5ed049ec-5a85-4ee3-9b2d-e7d5ee329546">

**Comment by Monson2002** [comment]
@Naresh-chandanbatve please assign this issue to me as a part of GSSOC '23.

**Comment by Naresh-chandanbatve** [comment]
Go cor it @Monson2002
