### ISSUE TITLE
Feat: Delete Account Feature

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#374]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Proposed Feature
As a user requires a **delete account option** when he/she decided to no longer use an application.
But, Currently, there is no delete button option on both sides customers and tailors. I want to implement the delete account option and implement the delete operation in the backend which removes the user account and all the data related to that user. I will implement the backend delete operation for both the customer and the tailor.

## Method
We can do this as follows: 
When the user clicks on the delete button, an input will be prompted in which he has to put his/her username to confirm that the button is not clicked by mistake. If the correct user name is given then the delete operation will trigger in the backend.

In the input box that appears after clicking the delete button, we can give any other statement to enter by the user instead of a username for example "Don't Say Goodbye! Stay with Us" just to make the site a little fun. 

Please provide your suggestions on this if you agree to implement this feature!

### Add Screenshots

..

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@AlfiyaSiddique Sound good,
go ahead with it
