### ISSUE TITLE
[STYLE CHANGE] Change the Major Feature text style

### ISSUE THREAD

**Issue by MisterMickey** [UBA-GCOEN/StichHub#378]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

I want to change the Major Feature text style

### Reason for Change:

The Major feature text is making the website out and inconsistent.

### Current Styling:

It's too small and very different

### Proposed Styling:

To make it consistent with whole page design

### Screenshots or Design Mockups (optional):

![Screenshot from 2023-06-23 11-19-04](https://github.com/UBA-GCOEN/StichHub/assets/93720428/08273618-8a12-4b7a-ad12-7fd8db719c72)

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MisterMickey** [comment]
@Siddhant-Patil0203 According to me, this change is better, what you say?
# Old
![Screenshot from 2023-06-27 13-01-22](https://github.com/UBA-GCOEN/StichHub/assets/93720428/1a189467-2f74-446c-aee5-f76bbbe0d151)

# New


![Screenshot from 2023-06-27 13-02-27](https://github.com/UBA-GCOEN/StichHub/assets/93720428/8afe621a-3b86-4ef8-b078-1bb9e809c7e4)

**Comment by MisterMickey** [comment]
@Siddhant-Patil0203 I want to make additional UI change too in the project to enhance it, Should I create a new issue for that or should work in this issue only, you can increase the level of this issue only then.

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 I want to make additional UI change too in the project to enhance it, Should I create a new issue for that or should work in this issue only, you can increase the level of this issue only then.

@MisterMickey 
Create Another issue for it
