### ISSUE TITLE
[STYLE CHANGE] Fix the alignment of different sections of website

### ISSUE THREAD

**Issue by MisterMickey** [UBA-GCOEN/StichHub#379]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Fix the alignment of different sections of website

### Reason for Change:

Current the sections are not aligned vertically which is not good for UI

### Current Styling:

Disturbed alignment

### Proposed Styling:

Make alignment synchronised/consistent.

### Screenshots or Design Mockups (optional):

https://github.com/UBA-GCOEN/StichHub/assets/93720428/ea8aa57e-cb2c-4f6b-b77f-0d76575cc0c6

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@MisterMickey Go ahead
