### ISSUE TITLE
[STYLE CHANGE] Fix FAQ section alignment

### ISSUE THREAD

**Issue by MisterMickey** [UBA-GCOEN/StichHub#380]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Fix FAQ section alignment

### Reason for Change:

to make UI better

### Current Styling:

some answers are left aligned some are not

### Proposed Styling:

Left alignment for all answers of FAQ

### Screenshots or Design Mockups (optional):

![Screenshot from 2023-06-23 11-26-47](https://github.com/UBA-GCOEN/StichHub/assets/93720428/e9014e8b-0290-47d2-9acf-c25d7c9d40ed)

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@MisterMickey 
Go for it.
