### ISSUE TITLE
Feat: Add icon to describe issue input

### ISSUE THREAD

**Issue by MisterMickey** [UBA-GCOEN/StichHub#381]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

It's a icon that describe the input field as issue description

### Add Screenshots

![Screenshot from 2023-06-23 11-29-57](https://github.com/UBA-GCOEN/StichHub/assets/93720428/7484751d-6b05-4d7c-9197-045a1824306d)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Okay @MisterMickey Go ahead
