### ISSUE TITLE
Feat: Making Tailor Page

### ISSUE THREAD

**Issue by PatilHarshh** [UBA-GCOEN/StichHub#384]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Making Page for list of tailors in it 

### Add Screenshots

![Screenshot (89)](https://github.com/UBA-GCOEN/StichHub/assets/120102234/5d15a6b1-01ff-4c33-9923-f5b658b092dc)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@PatilHarshh go for it

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 this is feature implementation why level one brother,  i am adding new page to your website and this is not ui/ux

**Comment by PatilHarshh** [comment]
![Screenshot (102)](https://github.com/UBA-GCOEN/StichHub/assets/120102234/b81e823b-77a9-413f-9498-f0581cf50ff2)
