### ISSUE TITLE
BUG: Footer HyperLink Issue

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [UBA-GCOEN/StichHub#385]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Hello Project Admin,
### Add ScreenShots

![Screenshot from 2023-06-23 21-49-24](https://github.com/UBA-GCOEN/StichHub/assets/121503426/241e8bea-46a1-4fee-881d-ea06d6a1f634)

### What browser are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Riyazul555** [comment]
Hey @SyedImtiyaz-1  and @UBA-GCOEN  I want to work on this issue ....please assign it to me under GSSOC 23

**Comment by Siddhant-Patil0203** [comment]
Hey @SyedImtiyaz-1 issue #382 is already been raised for this
