### ISSUE TITLE
BUG: Unexpected text displayed

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [UBA-GCOEN/StichHub#386]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Hello Project Admin,
Here is a Unexpected text displayed after we login the page.

### Add ScreenShots

![Screenshot from 2023-06-23 21-48-46](https://github.com/UBA-GCOEN/StichHub/assets/121503426/c06f1e2c-68c1-494a-94b8-39f4b077d45e)

### What browser are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@SyedImtiyaz-1 
Did you mean this [],
Nice observation 👀, 
Go for it and fix this
