### ISSUE TITLE
BUG: Sign in tailor Button is disable

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#390]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Sign in tailor button is disabled even with valid input 

### Add ScreenShots

https://github.com/UBA-GCOEN/StichHub/assets/86224794/c995d453-7c64-44e3-8fc0-6504f07609cd

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by AlfiyaSiddique** [comment]
@Siddhant-Patil0203 I apologize for mentioning you directly,  but this bug is really urgent because it's causing difficulty in development and testing. Can you please review it

**Comment by Siddhant-Patil0203** [comment]
@AlfiyaSiddique pls resolve this
