### ISSUE TITLE
[Bug]: Positioning of show password icon

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#391]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Issue
The show password eye icon is dispositioned when the error message is displayed.

## Solution
I want to position the eye icon in such a way, so that it does not get dispositioned.

### Add ScreenShots

<img width="226" alt="5" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/fe1ce936-aed2-484f-90f5-6f2762257c9e">

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by neeravbhaskarla** [comment]
@AlfiyaSiddique resolved

**Comment by AlfiyaSiddique** [comment]
Hello @neeravbhaskarla 
I opened this issue for myself.  I don't think without assignments PR's are accepted. Let's see what the maintainers have to say. @Siddhant-Patil0203 can you please look into this matter?

**Comment by neeravbhaskarla** [comment]
can I get it assigned?

**Comment by AlfiyaSiddique** [comment]
> Can I get it assigned?

Issues are assigned on first come first serve basis as I have created this one, so if they approve this issue then most probably maintainers will assign this one to me. 

But yes you are free to create new issues, the maintainers will review them and assign them to you.
Good Luck  👍🏻

**Comment by Naresh-chandanbatve** [comment]
@AlfiyaSiddique you will be assigned this after you complete your other assigned issues

When you feel this issue should be assigned to someone else
Comment here.

**Comment by AlfiyaSiddique** [comment]
Hello **@Naresh-chandanbatv**e 

I have submitted the PR for two of my assigned issues and 2 issues are remaining. 
Can you please assign this issue to me?
I'll fix it first as it is a small frontend bug.
