### ISSUE TITLE
[Add animation on text:{SHARE YOUR WAY} in home page.]

### ISSUE THREAD

**Issue by akshaysoni10** [UBA-GCOEN/StichHub#394]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

I want to add animation on text: {SHARE YOUR WAY}.

### Reason for Change:

So that it looks more attractive.

### Current Styling:

It's simply a text.

### Proposed Styling:

I want to add animation.

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@akshaysoni10 You mean STITCH YOUR WAY ??

**Comment by akshaysoni10** [comment]
@Siddhant-Patil0203 Yes

**Comment by Siddhant-Patil0203** [comment]
@akshaysoni10 Go for it
