### ISSUE TITLE
BUG: choice font is merging and its not responsible

### ISSUE THREAD

**Issue by techmannih** [UBA-GCOEN/StichHub#397]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

hello @UBA-GCOEN  ,
I found an issue in your website  " StichHub" f which is not responsive after on click get started or moblie and tablet devices please check it
And I want to work on this issue ...please assign me of this issue

### Add ScreenShots

![2023-06-24-20_43_46-screenshot](https://github.com/UBA-GCOEN/StichHub/assets/125847751/5c66eea0-db4b-4d75-bffe-c710e21443f2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@techmannih Alright make it responsive

**Comment by techmannih** [comment]
sure , work in progress
