### ISSUE TITLE
 Responsiveness issue in ClothesCategory page

### ISSUE THREAD

**Issue by Mudassirkhan2** [UBA-GCOEN/StichHub#4]
Responsiveness issue in ClothesCategory page. 
ScreenShot attached below.
![Screenshot 2023-05-20 092535](https://github.com/UBA-GCOEN/StichHub/assets/106579572/4e57f834-0dd5-4a69-b80c-c26445010baa)
I would like to work on this issue -GSSoc

**Comment by Naresh-chandanbatve** [comment]
Go for it @Mudassirkhan2
