### ISSUE TITLE
[Style Change] : 3D Configurator UI Update for Desktop 

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/StichHub#401]
# Problem 🤔 :
The Current UI for the [3D Configurator](https://stichhub.vercel.app/Configurator) is Mobile Friendly, this UI should be updated for Desktop.

## Current UI :
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/0d3cd678-b702-4e69-9852-4fcd80e61fda)

## The Figma Design for Desktop Mode is : 
![3D-Configurator](https://github.com/UBA-GCOEN/StichHub/assets/77800620/4960f931-508a-4906-8dc8-b5b112739153)

## Note 📃:
The developer Must make a new react component for desktop display and the existing one will be used for mobile display.

## Contributing : 
Anyone who is interested in developing this page can tag me in this issue

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 Please assign me i want to do this task !!

**Comment by Siddhant-Patil0203** [comment]
@PatilHarshh 
Go for it and design a good one 🚀
