### ISSUE TITLE
[Style Update] : Footer UI Updated & Adding Youtube Video

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/StichHub#402]
The Current Style of the Footer is : 
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/4e7150ec-cbf6-4a3c-99c3-d6afb3193815)
This UI should be Updated 

The Footer should contain : 
1. This Youtube video: https://www.youtube.com/watch?v=dE3RYo23eSY
2. Social Media Handle : Email | Github | Youtube | Instagram | Twitter | Discord
    - Email: stichhub.office@gmail.com
    - Github : https://github.com/UBA-GCOEN/StichHub
    - Youtube: https://www.youtube.com/@StichHub_YT
    - Instagram: https://www.instagram.com/stichhub_/
    - Twitter : https://twitter.com/StichHub_
    - Discord : keep it blank as of now
3. Privacy Policy: use a standard template for now
4. Terms and Condition: use a standard template for now
5. License: https://github.com/UBA-GCOEN/StichHub/blob/main/LICENSE

You free to design and style the footer on your own, 
Checkout [Dribbble](https://dribbble.com/search/shots/popular/web-design?q=footer) Site for design inspiration

### Those who are interested in working this can tag me.

**Comment by Riyazul555** [comment]
Hey @Siddhant-Patil0203 I want to work on this issue...... please assign me this

**Comment by PatilHarshh** [comment]
@Siddhant-Patil0203 i am intrested to to it asap !! please assign me

**Comment by Siddhant-Patil0203** [comment]
Okay @Riyazul555 Go for it and Make a good one

**Comment by Siddhant-Patil0203** [comment]
@PatilHarshh You can work on this to
