### ISSUE TITLE
Feat: Add customer review section

### ISSUE THREAD

**Issue by Pragati-3003** [UBA-GCOEN/StichHub#404]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I would like to add the customer review section fot the website .
So,please assign this issue to me under gssoc'23.

### Add Screenshots

.........

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @Pragati-3003 Do you Mean Testimonial Section

**Comment by Pragati-3003** [comment]
> Hey @Pragati-3003 Do you Mean Testimonial Section ?

Yes...

**Comment by Siddhant-Patil0203** [comment]
@Pragati-3003 Okay Go ahead

**Comment by Siddhant-Patil0203** [comment]
Hey @Pragati-3003 
this issue already exists, check #284 .
thank you for raising the issue, 
you can check the website for any other bugs or features and contribute to this project.
