### ISSUE TITLE
BUG: Button Not working

### ISSUE THREAD

**Issue by shraddha761** [UBA-GCOEN/StichHub#408]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

The button in explore section is not working of sleeves, short sleeves...

### Add ScreenShots

![image](https://github.com/UBA-GCOEN/StichHub/assets/106100728/66342d6a-4380-4775-a32f-7cf3c4dd0c5f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@shraddha761 Actually this dummy thing, 
But you can add this  component there
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/0f5d58e4-d9d7-489d-96e5-4e3f8b5e7b0d)
This is on main landing page - https://stichhub.vercel.app

Will you be able to do this ??

**Comment by shraddha761** [comment]
> @shraddha761 Actually this dummy thing, But you can add this component there ![image](https://user-images.githubusercontent.com/77800620/249038533-0f5d58e4-d9d7-489d-96e5-4e3f8b5e7b0d.png) This is on main landing page - https://stichhub.vercel.app
> 
> Will you be able to do this ??

Will you please elaborate I want to add this component in main page ?

**Comment by shraddha761** [comment]
@Siddhant-Patil0203 yahh I'll do it
