### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by SubhamB2003** [UBA-GCOEN/StichHub#409]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Hey, some section text is not visible properly you can see below. Can you please assign this task to me under GSSOC'23?

### Reason for Change:

Better user experience

### Current Styling:

![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/7c385347-d350-4754-9185-54f46c512edd)

![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/d041763d-b4aa-42a2-964e-1e7e2d3a091e)
![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/ef29d1cd-20bc-4081-b078-bceb24a0f0bc)

Also, there is a conflict between two-component
![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/04d4fa68-a632-4888-b4ad-80bc692564cc)

### Proposed Styling:

It should look like this
![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/68588f26-5798-457d-bda2-99452eef8370

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @SubhamB2003 Go ahead with it
