### ISSUE TITLE
Fix the Customer register page and add some styles in the form

### ISSUE THREAD

**Issue by rishuraj1** [UBA-GCOEN/StichHub#41]
I strongly believe that the customer register page needs to be fixed, there are bugs and it is not aligned properly.

![Screenshot (102)](https://github.com/UBA-GCOEN/StichHub/assets/47839626/b46f4f1d-a703-4a4f-b3cd-769512aebbf7)

we can see that the sign in with google button is not aligned properly and is out of its place. We do not want to give user hassle in registration.
We can fix it by aligning it with the form correctly.

proposed idea:

![Screenshot (101)](https://github.com/UBA-GCOEN/StichHub/assets/47839626/fd96474d-e769-4ec1-81b5-50bf73946b06)

Also, we can make some changes to the registration form in order to make it more attractive and more user friendly as shown in the above snapshot.

P.S:  I really want to contribute to this wonderful project. So can you please assign me to this task under GSSoC '23. Thank You!

**Comment by Naresh-chandanbatve** [comment]
This issue is already being solved...
#26
