### ISSUE TITLE
Feat: Captcha verification backend

### ISSUE THREAD

**Issue by SnehaJaiswal123** [UBA-GCOEN/StichHub#410]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Adding API for captcha verification in server using Google v2 recaptcha.
This code will proceed the further request if captcha is verified while registering or signing and help in server scripting.

### Add Screenshots

Not found appropriate image.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by SnehaJaiswal123** [comment]
Hey @Siddhant-Patil0203 , Please review and assign me this issue?

**Comment by Siddhant-Patil0203** [comment]
Hey @SnehaJaiswal123 We already have custom Captcha verification while registering or signing, do this issue any different from that ??

**Comment by SnehaJaiswal123** [comment]
> Hey @SnehaJaiswal123 We already have custom Captcha verification while registering or signing, do this issue any different from that ??
I have not seen the captcha verification from the backend side in your code and the captcha need to be verified from the backend.This is my issue.
