### ISSUE TITLE
Feat: sitemap addition for website 

### ISSUE THREAD

**Issue by NikhilRaikwar** [UBA-GCOEN/StichHub#415]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Yes, the feature request is related to a problem. The problem is that the current website lacks a sitemap. Without a sitemap, it becomes challenging for search engines and users to navigate and discover all the pages and content on the site. This can result in lower search engine rankings, decreased visibility, and a poor user experience.

### Add Screenshots

![stich](https://github.com/UBA-GCOEN/StichHub/assets/70462831/e611c97f-2715-47a0-a313-6ffdc03e3a95)

In the attached screenshot, I have highlighted the website name with the expected presence of a sitemap.xml file. However, upon inspection, it is evident that the sitemap is not being displayed. This screenshot underscores the problem of the current website lacking a visible sitemap, further emphasizing the need for its implementation.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
hey @NikhilRaikwar 
we have client/StichHub/sitemap.xml, check it properly and add this feature.
I am assigning you this

**Comment by NikhilRaikwar** [comment]
Thank you @Siddhant-Patil0203 for assigning this issue to me.

**Comment by NikhilRaikwar** [comment]
@Siddhant-Patil0203 Hey I'm done with my work. Pls review and check the PR.
