### ISSUE TITLE
Feat: Make navbar items transition smooth

### ISSUE THREAD

**Issue by MisterMickey** [UBA-GCOEN/StichHub#427]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to make the transition on hover for navbar items smooth so that do not abruptly scale up and down

### Add Screenshots

https://github.com/UBA-GCOEN/StichHub/assets/93720428/770104e9-dbd7-47f8-b7a4-ee00fb8677d7

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @MisterMickey Go ahead
