### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Sar-thak-3** [UBA-GCOEN/StichHub#428]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

I think the buttons in "/Configurator" page below of Sleeve, Collar etc are not alligned with the line shown below them to display which option is selected. As you can see in the below image, the Collar is selected but the underlined option in Sleeve. 

If you believe this is the issue, kindly assign me under GSSoC 2023. Else feel free to close the issue.

### Add ScreenShots

![image](https://github.com/UBA-GCOEN/StichHub/assets/100359818/50b6f564-72f7-40d8-bb22-9b1a0de00d2f)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Safari, Arc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @Sar-thak-3 
The line below the Sleeve denotes that it has been visited and completed.
Therefore, there is no need to change this.
