### ISSUE TITLE
Feat: Your cart forms can be skipped 

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#429]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Issue
Your cart 2nd step (Delivery part) has forms but a user can go ahead without filling these fields as shown in the below video.

https://github.com/UBA-GCOEN/StichHub/assets/86224794/7af97d68-7065-4b66-a3f8-390bc11dee10

## Solution
I want to implement inline validation in these forms and prevent the user from going ahead if the fields are empty.

### Add Screenshots

...

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@AlfiyaSiddique Go ahead
