### ISSUE TITLE
Feat: Add custom price range in filter section

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#430]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to add inputs in the filter for custom price ranges that can be given by users. I will add this feature along with functionality.

### Add Screenshots

I want to add custome price range feature in filter box similar to the one in amazon's site, as shown below:
<img width="260" alt="6" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/a0ca1a8c-750e-4ee8-92ca-b58c10b609a3">

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@AlfiyaSiddique Go for it
