### ISSUE TITLE
[STYLE CHANGE] Tailor Profile Container Overflow (Redesign)

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#435]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Issue

The tailor profile section has a container that overflows the parent container, as shown in the below image:
<img width="736" alt="2" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/f43993d7-fbc8-4e88-abc3-bb77a6022509">

Also, the alignment and layout of the profile form container are not proper and this section is not fully responsive. The sizes of elements are also inconsistent. I want to work on the layout and design of this section.

### Reason for Change:

Inconsistent style properties

### Current Styling:

https://github.com/UBA-GCOEN/StichHub/assets/86224794/5f0ae374-516a-479f-89b2-ce85c7f9cc33

### Proposed Styling:

I will implement consistent space use.
I will add a better layout and implement responsiveness.

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@AlfiyaSiddique Go for it.
