### ISSUE TITLE
Feat: Footer on the home page

### ISSUE THREAD

**Issue by sumitkr2000** [UBA-GCOEN/StichHub#436]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Hey, There is no footer on the home page. Please assign me this issue. Thank you!

### Add Screenshots

![image](https://github.com/UBA-GCOEN/StichHub/assets/100675296/149f77ad-5c02-403e-9ef9-40e239bc5568)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @sumitkr2000 go for it
