### ISSUE TITLE
BUG: Remove all console.log Statements from the Project

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#437]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Currently, the project contains several instances of the console.log statements scattered throughout the codebase.

**Removing console.log statements will have the following benefits:**

- **Improved performance:** Unnecessary logging can slow down the application, especially when executed in loops or frequently-called functions.
- **Enhanced code readability:** By eliminating debug logs, the codebase becomes cleaner and easier to understand, reducing cognitive load for developers.
- **Reduced noise in the console:** With fewer log statements, it will be easier to identify relevant messages and warnings during debugging.
- **Enhanced security:** Logging sensitive information like API keys, passwords, or user data can pose a security risk. Removing console.log statements helps mitigate this risk.

### Add ScreenShots

![Screenshot (562)](https://github.com/UBA-GCOEN/StichHub/assets/56786344/4e89c2ea-c0a9-4362-b956-03cc01f756d3)
![Screenshot (564)](https://github.com/UBA-GCOEN/StichHub/assets/56786344/6174172f-3e95-4c4f-9a2d-dd7644fc9894)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Siddhant-Patil0203** [comment]
@Avinash905 Go ahead
