### ISSUE TITLE
[STYLE CHANGE] Change the colour of gmail

### ISSUE THREAD

**Issue by sumitkr2000** [UBA-GCOEN/StichHub#439]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Hey, the hover effect on the mail icon is not the same as the Gmail official color and it is not looking formal. Please assign me this issue. Thank you!

![Screenshot (885)](https://github.com/UBA-GCOEN/StichHub/assets/100675296/5f27f512-10ba-42c5-80a8-92059011cbd6)

### Reason for Change:

Bad UI

### Current Styling:

Green colour on Gmail icon

### Proposed Styling:

Official color of Gmail on the Gmail icon.

### Screenshots or Design Mockups (optional):

![Screenshot (887)](https://github.com/UBA-GCOEN/StichHub/assets/100675296/5d2ee53e-3d38-43e9-99ef-878181ef0647)

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @sumitkr2000 go for it
