### ISSUE TITLE
The dashboard UI

### ISSUE THREAD

**Issue by Hemant2335** [UBA-GCOEN/StichHub#44]
The UI of dashboard looks quite out of trend , but I can design you a new dashboard

therefore , Please assign me this task under GSSOC'23

Thank you

**Comment by Naresh-chandanbatve** [comment]
Go for it @Hemant2335 
Design it in better user experience and matching theme with current one

**Comment by Hemant2335** [comment]
Thanks I'm on it

**Comment by Naresh-chandanbatve** [comment]
This is big problem you can create lists of tasks for it 
While you are working on this there may be some new changes to this files be ready for that keep in mind the values that are dynamic like name email image etc..
Dont change completely 180 but just minor changes which will enahance Ui and UX as well
