### ISSUE TITLE
Feat: Implement show password on confirm password

### ISSUE THREAD

**Issue by sumitkr2000** [UBA-GCOEN/StichHub#440]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

Hey, Currently show password is not implemented on the confirm password input field. I want to implement it on the confirm password also so that sure can see the password if it matches the original one. Please assign m this issue. Thank you!

### Add Screenshots

![image](https://github.com/UBA-GCOEN/StichHub/assets/100675296/7c03b591-0a75-47a3-a359-4138fbaecc30)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @sumitkr2000 , 
Thank you for bringing it up, but it is currently not necessary.

**Comment by sumitkr2000** [comment]
Okay bro np @Siddhant-Patil0203
