### ISSUE TITLE
Code Refactor of Cart Component.

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#442]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

**Description**

I want to perform a code Refactor on the Cart.js file because the file contains lots of variables and codes that have never been used and also some parts are rewritten even though the reusable components are present.

I will remove all the unnecessary parts of codes from this file and try to follow the DRY (Don't Repeat Yourself) principle and use reusable components wherever they can possibly be implemented. 

### Add Screenshots

..

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Go ahead @AlfiyaSiddique
