### ISSUE TITLE
Feat: Heading "Our services" improvement

### ISSUE THREAD

**Issue by ShreyaDhiman24** [UBA-GCOEN/StichHub#448]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

![image](https://github.com/UBA-GCOEN/StichHub/assets/98320971/3d7de677-d844-4522-ad15-25db767f7275)

![image](https://github.com/UBA-GCOEN/StichHub/assets/98320971/d2282f6f-72b4-440e-b9cc-9cb97d6262ca)

### Add Screenshots

Adding line in our services page as per given in 2nd image.

wish to solve this under GSSoC'23

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @ShreyaDhiman24
Thank you for raising the issue,
We Don't Require this feature as of now,
You can check out other issues or create another issue or feature.

Happy Contributing 🧑‍💻
