### ISSUE TITLE
Navbar Improvement

### ISSUE THREAD

**Issue by SubhamB2003** [UBA-GCOEN/StichHub#45]
@Naresh-chandanbatve Hey, the navbar is not looking good whenever I scroll the page it meshes up with other components so I have an idea to make it look great.
Here it is,

Previous
![image](https://github.com/UBA-GCOEN-23/StichHub/assets/94003231/a64117da-1e07-4cd4-9bf8-ef7b44aacebb)

After Change
![image](https://github.com/UBA-GCOEN-23/StichHub/assets/94003231/c7e38744-da0b-4fe0-b5aa-e00847b5e45e)
Adding a blur effect

Please assign this task to me under GSSOC 23. I would love to work on it.

**Comment by Naresh-chandanbatve** [comment]
It is already being resolved
Here #9

**Comment by SubhamB2003** [comment]
> It is already being resolved Here #9

Hey, can I work on that?
I add the glass morphic effect in the navbar it looks good.
