### ISSUE TITLE
[Bug]: Tailor and customer with same email

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#451]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

## Description

I can create tailor and customer account with the same email which is generally not a common practice on websites that have two types of user.  For example, on the freelancing site **Fiverr** we cannot create a buyer and a seller account with the same Email. Similarly, it should not happen on our site too.

## Solution
We can prevent this behavior by implementing logic in the backend. I would like to solve this issue. 
If you find this worth implementing then please assign me this under the gssoc23 label.

### Add ScreenShots

**User Registration**

https://github.com/UBA-GCOEN/StichHub/assets/86224794/629ec50f-ca2c-4bfb-9866-db5e4962ffb4

**Tailor registration**

https://github.com/UBA-GCOEN/StichHub/assets/86224794/c38c2c49-b290-40a8-964d-1512bf18dff5

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
Hey @AlfiyaSiddique ,
I appreciate you bringing this to my attention. I will assign this issue to you.
