### ISSUE TITLE
[STYLE CHANGE]

### ISSUE THREAD

**Issue by NomikaGajula** [UBA-GCOEN/StichHub#453]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

I want to change the ui of the customer signup page (here the signup with google option is not visible)

### Reason for Change:

The reason for change is for making users easily login with the help of google sign up

### Current Styling:

The current styling does not show the signup with google option and we cannot scroll down to see it

### Proposed Styling:

I will make it visible to all type of screens so that anyone can easily see it with out any difficulty

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
hey @NomikaGajula 
I think it is visible can you please provide screenshots and 
exact detailed changes you are going to do

**Comment by NomikaGajula** [comment]
When we zoom out in our browser it is showing but the default is 100%
percent at this stage it is not showing. even the scroll just stops at a
point and it does not go

[image: image.png]
