### ISSUE TITLE
Feat: Contact Field Improvement

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#454]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

I want to change the contact fields simply from the type tel text field to a dropdown where there is a list of all countries with their country codes. Currently, the validation for contact fields only validates for Indian-length phone numbers i.e. 10 digits, and not for others. Using the dropdown we can validate different country's phone numbers dynamically.

I will change all the contact fields present in different forms with the dropdown format.

I want to implement a feature similar to below:

### Add Screenshots

<img width="274" alt="1" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/6f99220b-3aa1-4cb8-b6a1-6522d36c054b">

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
go for it 
@AlfiyaSiddique
