### ISSUE TITLE
Feat: Enhancing Social Anchor Accessibility in Footers

### ISSUE THREAD

**Issue by Avinash905** [UBA-GCOEN/StichHub#456]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

This feature aims to improve the accessibility of social anchors within the footer by implementing a comprehensive solution for screen reader users.
The focus of this enhancement is on providing enhanced accessibility information through the effective utilization of both the aria-label and title attributes. By incorporating these attributes, we can offer a more inclusive experience for individuals relying on screen readers.

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Naresh-chandanbatve** [comment]
go for it @Avinash905
