### ISSUE TITLE
[STYLE CHANGE] 'Our Services' Heading Alignment Enhancement

### ISSUE THREAD

**Issue by iamRabia-N** [UBA-GCOEN/StichHub#457]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Alignment of heading from left-sided to central aligned to enhance the design of overall section and website.

### Reason for Change:

To improve user experience.

### Current Styling:

Heading left-aligned.

### Proposed Styling:

Central alignment of heading.

### Screenshots or Design Mockups (optional):

Current Alignment
![stitch-project (2)](https://github.com/UBA-GCOEN/StichHub/assets/115794049/8ea03578-5f0e-445e-83bf-46319b0502fc)

Expected Updated Alignment
![stitch-project (1)](https://github.com/UBA-GCOEN/StichHub/assets/115794049/0c4a9672-aa39-42fb-9775-c62cfb32f738)

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
go for it @iamRabia-N
