### ISSUE TITLE
Valid Data Insertion

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#46]
## Issue
Currently, in the Customer Registration, the fields name and password are even accepted with single characters. For example, I can create an account with the name D which is just a single-character invalid name. Similar issue in the password field as shown in the below image.

## Screenshot
<img width="940" alt="desktop" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/3ff67848-85ce-484f-9181-6c1496b4e94c">

## Solution 
We can check inserted data length and then after validating insert it into the database. According to me, the following constraints can be applied.
Name - Minimum 6 characters
Password- minimum 8 characters with numbers and special symbol

## Request
If you find this issue worth implementing, please assign me this issue under the gssoc'23 label as I am a gssoc'23 contributor.

**Comment by AlfiyaSiddique** [comment]
@Naresh-chandanbatve Can you please give feedback on this issue so that I can start working on it.

**Comment by Naresh-chandanbatve** [comment]
Go for it 
@AlfiyaSiddique
