### ISSUE TITLE
Refactor MainLandingPage component for improved code organization. ⚡

### ISSUE THREAD

**Issue by Nishitbaria** [UBA-GCOEN/StichHub#470]
### **Description:** 

The `MainLandingPage.jsx` component located at `client/StichHub/src/pages/MainLandingPage.jsx` would benefit from refactoring to improve code organization and maintainability. The current implementation could be optimized for better readability and separation of concerns.

### **Refactoring Goals:**

- Improve the import statements to enhance code readability.
- Remove unused imports and variables to reduce clutter.
- Review the usage of hooks and state to ensure it aligns with best practices.
- Apply consistent formatting and naming conventions to improve code consistency.
- Eliminate any code duplication or unnecessary repetition.
- Consider implementing component splitting or reusability where appropriate.

### **Proposed Changes:**

1. Update the import statements in `MainLandingPage.jsx` to import components individually for better clarity and maintainability.
2. Remove unused imports and variables that are not being utilized in the component.
3. Review the usage of hooks and state, ensuring they are used correctly and according to best practices.
4. Apply consistent formatting and naming conventions throughout the component to improve code consistency.
5. Identify any code duplication or repetitive patterns and refactor them to promote reusability and reduce redundancy.

**Expected Outcome:**
The refactored `MainLandingPage.jsx` component should have improved code organization, readability, and maintainability. By addressing the above-mentioned goals, the component will be easier to understand and maintain for future development tasks.

**Comment by Naresh-chandanbatve** [comment]
@Nishitbaria go for it
