### ISSUE TITLE
Content Overflow

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#471]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

There is content overflow in register and login page of both the user and customer at 100% default zoom value. 

### Reason for Change:

The register button and some contents are not visible.

### Current Styling:

**Register**

<img width="953" alt="4" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/5d098e3e-04d8-4a22-b1a9-4952275e4a45">

**Login**
<img width="949" alt="5" src="https://github.com/UBA-GCOEN/StichHub/assets/86224794/a9cfa34e-8085-4334-80f5-382c181126f7">

### Proposed Styling:

There are two ways we can tackle this design problem, these are as follows:

1. By increasing the parent size so that the screen can be scrolled and the content can be appear
2. By reducing the form field sizes.
Let me know which way to use to solve this problem.

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
go for it @AlfiyaSiddique
