### ISSUE TITLE
BUG: Social Media links in the footer of the site are opening in the same tab as current tab

### ISSUE THREAD

**Issue by tmsagarofficial** [UBA-GCOEN/StichHub#473]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

I would like to point out that when social media icons / social links are clicked at the bottom of the website i.e. at the footer user is redirected to that social page in the same tab.

Fixing this to open on a new tab would not hamper the flow of navigation for the user.

Let me know when I can work on a fix for this issue @UBA-GCOEN 

### Add ScreenShots

<img width="443" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/110724849/52cfbc8b-7222-4879-9144-409c257da023">

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
go for it @tmsagarofficial

**Comment by tmsagarofficial** [comment]
Thanks for assigning @Naresh-chandanbatve. Will start working on this.

**Comment by tmsagarofficial** [comment]
hey, @Naresh-chandanbatve  needed some help with this bro.
Let me know when u can answer my query

**Comment by tmsagarofficial** [comment]
> 'hey @{assignee}, It has been seen that you haven't responded to this issue since long ago, Please update the tatus or reply to this message else will be assigned to someone else.' @{author}, @{reviewer}'

hey sorry for the delay @Naresh-chandanbatve  I'll resume working on this again, but i might need some queries to be resolved as mentioned in my recent most comment.

**Comment by tmsagarofficial** [comment]
But as of checking this issue now. It has been resolved already.
