### ISSUE TITLE
Feat: create a new issue form for enhancement

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [UBA-GCOEN/StichHub#475]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

currently there are forms for bug feature and style in issue form.
create a new form for enhancement which should contains relavent feilds.

search the internet for good enhancement issue forms.

### Add Screenshots

can get on internet

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [ ] I want to work on this issue

**Comment by MeenuyD** [comment]
I would like to work on this issue can you please assign this to me

**Comment by Naresh-chandanbatve** [comment]
sure go fot it @MeenuyD
