### ISSUE TITLE
BUG: UI Improvement

### ISSUE THREAD

**Issue by SubhamB2003** [UBA-GCOEN/StichHub#476]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Hey, I want to add responsiveness to the below page. Can you please assign it to me? 

![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/82cb916f-92af-46c0-a584-bf10a0f95b87)

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
go for it @SubhamB2003
