### ISSUE TITLE
Issue with hover effect

### ISSUE THREAD

**Issue by akanksha984** [UBA-GCOEN/StichHub#477]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

I would like to fix the hover issue in which line is also scaling.
Please assign it to me under gssoc'23. I would like to work upon this issue.

### Add ScreenShots

![image](https://github.com/UBA-GCOEN/StichHub/assets/97845909/8147f5e8-08b4-4f3a-b058-9709becb9ec7)
![image](https://github.com/UBA-GCOEN/StichHub/assets/97845909/d5e779cc-e83b-4f7c-82ab-6d7517c0da5f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
@Naresh-chandanbatve  please assign this to me

**Comment by Naresh-chandanbatve** [comment]
@akanksha984 
go for it

**Comment by akanksha984** [comment]
How do we start with project It is showing package.json not found while doing npm i in the client folder.. ? @Naresh-chandanbatve

**Comment by Naresh-chandanbatve** [comment]
Client folder is actually client/StichHub
Everything is present in client/StichHub folder
Do cd StichHub again to go to the client folder

**Comment by akanksha984** [comment]
Yes I got it now

**Comment by akanksha984** [comment]
@Naresh-chandanbatve please check #528
