### ISSUE TITLE
Add typing effect

### ISSUE THREAD

**Issue by akanksha984** [UBA-GCOEN/StichHub#478]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

I would like to add typing effect in the hero section
![image](https://github.com/UBA-GCOEN/StichHub/assets/97845909/4d5fde19-5713-4eb4-8312-b1d760a098fb)

### Reason for Change:

I would look good

### Current Styling:

Simple text

### Proposed Styling:

Typed text

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
@Naresh-chandanbatve please assign this to me

**Comment by Naresh-chandanbatve** [comment]
go for it @akanksha984 
but do not add very fast make it bit slower
