### ISSUE TITLE
BUG: Change different fonts and remove hover effect

### ISSUE THREAD

**Issue by SubhamB2003** [UBA-GCOEN/StichHub#479]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Hey, the below section hover effect is not looking good. I want to remove it. You can see below
![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/e9215f67-0bb4-4ef8-8fd2-d923c9133851)

Also, there is a different type of font used that does not match with other fonts.
![image](https://github.com/UBA-GCOEN/StichHub/assets/94003231/5c609847-44af-4495-b972-12dd54eeb7f3)

### Add ScreenShots

Please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Brucedevnairobi** [comment]
Heyy,,Id like to work on this. Give it to me
