### ISSUE TITLE
need a fix in t-shirt

### ISSUE THREAD

**Issue by sandeep0009** [UBA-GCOEN/StichHub#48]
one of your t-shirt have no hover effect that need to be fixed

**Comment by Naresh-chandanbatve** [comment]
Can you add screenshot and more detailed description

**Comment by sandeep0009** [comment]
<img width="160" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/63727946/b5b2faa0-e7c7-44ee-ba2e-6a46131d1913">
when im hoevring over other they are changing but when im hovering over this one it is not working 
<img width="133" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/63727946/034c48ef-1f8c-4887-a712-d1db5dfaecc8">

**Comment by Naresh-chandanbatve** [comment]
I think it is resolved can you checj?..

**Comment by kunal-2002** [comment]
I understand what has to be done here, so assign me this issue under GSSOC'23

**Comment by its-vikash** [comment]
> I understand what has to be done here, so assign me this issue under GSSOC'23

The already selected clothes cannot be hovered (the one that cannot be hovered means it is selected one ), once you change the clothe, the other two remaining clothes can be hovered to perform selection operation. So, there is no need to change anything, you can add new feature like More clothe option, which can open box or container that may contain more different types of clothes.
