### ISSUE TITLE
Feat : Navbar adjustment

### ISSUE THREAD

**Issue by KaKashi1210** [UBA-GCOEN/StichHub#5]
I think if we shift the navbar in demo section to top that will be more convenient and would look nice 

![Screenshot from 2023-05-20 15-10-38](https://github.com/UBA-GCOEN/StichHub/assets/97914006/544abf81-5772-45a8-9b01-f355a51d6a41)

I would like to work on this issue -GSSoc

**Comment by Naresh-chandanbatve** [comment]
Go for it @KaKashi1210 
But add the mainlading page navbar only

**Comment by KaKashi1210** [comment]
im quite busy with exams sorry can you assign this to someone else im really sorry for this .

**Comment by randiepathirage** [comment]
Can I work on this

**Comment by Naresh-chandanbatve** [comment]
Go for it @randiepathirage

**Comment by vk20july** [comment]
sir can i work on this under gssoc'23
i will complete this as early as possible

**Comment by Naresh-chandanbatve** [comment]
@randiepathirage any progress?

**Comment by vk20july** [comment]
> @randiepathirage any progress?

sir can i do as she is not replying

**Comment by Siddhant-Patil0203** [comment]
> > @randiepathirage any progress?
> 
> sir should i do as she is not replying

Hey @vk20july, explain to me what changes you are proposing

**Comment by vk20july** [comment]
> I think if we shift the navbar in demo section to top that will be more convenient and would look nice
> 
> ![Screenshot from 2023-05-20 15-10-38](https://user-images.githubusercontent.com/97914006/239680129-544abf81-5772-45a8-9b01-f355a51d6a41.png)
> 
> I would like to work on this issue -GSSoc

@Siddhant-Patil0203 sir I will shift this navbar to the top of the page which is currently at the bottom

**Comment by Siddhant-Patil0203** [comment]
Hey @vk20july as of now, we are not planing to shift this to the top. 
Thank you for looking out into this issues.

keep Contributing 🙌
