### ISSUE TITLE
Adding badges to readme file

### ISSUE THREAD

**Issue by Rakshitha-reddy-paladugu** [UBA-GCOEN/StichHub#50]
I am a GSSOC'23 contributor. I want to add readme badges.Please assign this issue to me.

**Screenshots**

![239808654-dc4a79c4-a08c-4a21-8e22-fec61d4beff4](https://github.com/UBA-GCOEN/StichHub/assets/132671425/baa071c2-7b77-48dc-a6c2-f0a6065276e9)

This is the screenshot how it looks after changes.

**Comment by Naresh-chandanbatve** [comment]
Go for it @Rakshitha-reddy-paladugu
