### ISSUE TITLE
Feat: UPDATE README

### ISSUE THREAD

**Issue by Shikhar9425** [UBA-GCOEN/StichHub#502]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

wants to add more features other than that you have mentioned.
wants to add some more content to the description so that it will be more easily understandable.
align/modify some of the headings .
wants to make an impressive readme

### Add Screenshots

wants to add more features other than that you have mentioned.
wants to add some more content to the description so that it will be more easily understandable.
align/modify some of the headings .
wants to make an impressive readme

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Shikhar9425** [comment]
@UBA-GCOEN please assign me this issue

**Comment by Naresh-chandanbatve** [comment]
@Shikhar9425 
what features will you be adding in readme? can you please provide in detail
can you provide what exact deatils you are going to add in headings description?

**Comment by Shikhar9425** [comment]
I want to add some features of your platform and write about the heading and details of project in description .
@Naresh-chandanbatve

**Comment by Shikhar9425** [comment]
I want to add some features of your platform and write about the heading and details of project in description .
@Naresh-chandanbatve

**Comment by Shikhar9425** [comment]
> I want to add some features of your platform and write about the heading and details of project in description . @Naresh-chandanbatve

@Naresh-chandanbatve @Naresh-chandanbatve

**Comment by Naresh-chandanbatve** [comment]
Ok go for it

**Comment by Shikhar9425** [comment]
> 'hey @{assignee}, It has been seen that you haven't responded to this issue since long ago, Please update the tatus or reply to this message else will be assigned to someone else.' @{author}, @{reviewer}'

Already updated
