### ISSUE TITLE
[STYLE CHANGE] The social media links open on the same page

### ISSUE THREAD

**Issue by Srishti-Somya** [UBA-GCOEN/StichHub#504]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

the social media links can open in the new webpage.

### Reason for Change:

The user don't have to start its journey again from starting on the website.

### Current Styling:

The social media links open on the same webpage.

### Proposed Styling:

social media links open in a new tab.

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
go for it @Srishti-Somya
