### ISSUE TITLE
BUG:  Tailor Button runtime error

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#508]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

The button on the tailor profile form has a buggy code that makes the site crash and blank out  without providing any response to the user

### Add ScreenShots

https://github.com/UBA-GCOEN/StichHub/assets/86224794/cddc65f5-c5e2-4d5b-8d6c-d83da974a66a

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by AlfiyaSiddique** [comment]
@Siddhant-Patil0203 can you please review this issue a bit earlier? It breaks the entire program. So, If you assign this to me then I can fix it first.

**Comment by AlfiyaSiddique** [comment]
Hello @Naresh-chandanbatve 

Can you please review this issue first or a bit earlier. It is creating difficulties to solve other issues as it makes the entire frontend crash!

**Comment by Naresh-chandanbatve** [comment]
hey @AlfiyaSiddique sure.
