### ISSUE TITLE
BUG:  User does not get response if jwt expired

### ISSUE THREAD

**Issue by AlfiyaSiddique** [UBA-GCOEN/StichHub#509]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

The two Authentication middlewares authUser and authTailor do not give a response if they fail to authenticate the user. 
That means if the jwt is expired then the frontend stays in the loading state because it does not receive any response (successful or errorful response) for the request it made.

**Solution**
The middleware should return a response that contains an error message that the session is expired and the user has to log in again. Also if the front end receives this error message response then it should redirect to the tailor or customer sign-in page.

### Add ScreenShots

.

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
@AlfiyaSiddique
