### ISSUE TITLE
Add smooth scroll over the website

### ISSUE THREAD

**Issue by suryanshsoni120** [UBA-GCOEN/StichHub#51]
To get the best user experience, we can add smooth scroll functionality on the website. Can you assign me this issue under GSSOC'23?

**Comment by gkprasanth** [comment]
@Naresh-chandanbatve Can I work on this issue as part of GSSOC 2023?

**Comment by Naresh-chandanbatve** [comment]
Go for it @suryanshsoni120

**Comment by Siddhant-Patil0203** [comment]
Hey @suryanshsoni120 what's your status?
