### ISSUE TITLE
Feat: Integration of "Contact Us" Form in Node.js with SendGrid ⚡

### ISSUE THREAD

**Issue by Nishitbaria** [UBA-GCOEN/StichHub#510]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the feature

**Proposed Solution:**
Integrate a form on the "Contact Us" page that utilizes Node.js and the SendGrid service to send emails. Here are the suggested steps for implementation:

1. Install the necessary dependencies, including express, body-parser, and @sendgrid/mail.
2. Create a new route in the Node.js application to handle the form submission.
3. Configure SendGrid API credentials and ensure the necessary environment variables are set.
4. Retrieve the form data on the server-side using body-parser middleware.
5. Use the SendGrid API to send an email with the submitted form data. Include the user's name, email, and message in the email body.
6. Handle any errors that may occur during the email sending process and provide appropriate feedback to the user.
7. Upon successful email submission, display a confirmation message to the user on the website.
8. Test the functionality thoroughly to ensure proper integration and email delivery.

### Add Screenshots

![image](https://github.com/UBA-GCOEN/StichHub/assets/85815172/67d4b39b-d47a-4d80-86c9-5a3d6f7e9a20)

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
hey @Nishitbaria 
we already have nodemailer service installed 
can you do this with nodemailer instead of SendGrid?
i am assigning this to you ping me if you think you will not be able to do this with nodemailer.

**Comment by Nishitbaria** [comment]
@Naresh-chandanbatve ,I will do it with nodemailer ,Dont worry

**Comment by Nishitbaria** [comment]
@Naresh-chandanbatve ,please review and merge my pull request
