### ISSUE TITLE
BUG: Forgot and Reset Password 

### ISSUE THREAD

**Issue by niteshtiwari52** [UBA-GCOEN/StichHub#511]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

An issue created regarding forgot and reset password issue no  #154  and the respective PR #272 
As per discussion in PR the forgot and reset password implementation will be in seperate issue. But except issue #154 no other issue open or close regarding forgot and reset password.

**Problem:**
The forgot password is available but this is not working. After clicking on the forgot password It shows only an alert "email verified". I want to make this working. 
**Solution**
As of now the forgot password component is made already. I want to implement the forgot and reset password in this way : 
step 1 : after clicking on the forgot password, we will asking to enter his/her mail id. 
step 2 : after enter user mail Id we will send a password reset URL on his mail Id So that he can easily reset their password.
step 3 : after resetting their password user will redirects to Login page. 

Could you assign me this issue under GSSOC ? 

### Add ScreenShots

![image](https://github.com/UBA-GCOEN/StichHub/assets/82033937/e7de56c6-4bb6-4262-81aa-0bd882e749b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by himanshu56784** [comment]
yup I solve this one

**Comment by niteshtiwari52** [comment]
> yup I solve this one

Could you mention your issue number. Have you created issue regarding?

**Comment by niteshtiwari52** [comment]
@Naresh-chandanbatve  Anyone also working on this issue. issue #154 and PR #272 I didn't get any more regarding this
Could you confirm that no one is working on this issue. if no one working on this issue then please assign me this issue.

**Comment by Naresh-chandanbatve** [comment]
if @SINJINI-G dies not respond i will assign this to you

**Comment by niteshtiwari52** [comment]
Okay @Naresh-chandanbatve no problem till then i am working on the issue #512 .
