### ISSUE TITLE
BUG: Logout probelem

### ISSUE THREAD

**Issue by niteshtiwari52** [UBA-GCOEN/StichHub#512]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

**problem**
if we click on the logout button our session expired then a continuously a redirection happens or flickering happen. 

I want to work on this bug. Could you assign me this issue?  
there is image attached because screenshot is mandatory

### Add ScreenShots

![image](https://github.com/UBA-GCOEN/StichHub/assets/82033937/4260f011-704a-4f10-aabc-712cdfaf4399)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
go for it @niteshtiwari52

**Comment by niteshtiwari52** [comment]
I am so sorry sir. The reason is that for no responding, I working as an intern in another organization. I am facing some difficulty to manage college, internship and open project. I joined internship at 18 Aug. The GSSOC program has finished on 15 Aug so i thought that i can contribute upto 15 Aug or before that.

**Comment by Naresh-chandanbatve** [comment]
No worries you can pick this up whenever you want

**Comment by niteshtiwari52** [comment]
Sure sir. I will do. But it will count still in GSSOC?

**Comment by Naresh-chandanbatve** [comment]
No it has concluded.....

**Comment by niteshtiwari52** [comment]
Okay sir. Right now i am working on multiple from the internship and college. It gets little bit  tough to me. My internship will ends on 21 OCT  I will try to complete this after that. I am really very sorry  this small issue taking very long time  from my end.

**Comment by Naresh-chandanbatve** [comment]
not a big deal.......
