### ISSUE TITLE
BUG: reviewpad is failing

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [UBA-GCOEN/StichHub#519]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

reveiwpad github action is failing

### Add ScreenShots

reviewpad github action is failing

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [ ] I want to work on this issue

**Comment by metabiswadeep** [comment]
Hey @Naresh-chandanbatve ! I am a GSSoC23 Contributor and I would like to work on this issue. Could you please assign the issue to me?

**Comment by metabiswadeep** [comment]
@Naresh-chandanbatve

**Comment by Naresh-chandanbatve** [comment]
go fr it
