### ISSUE TITLE
Adding the transition effect on the buttons

### ISSUE THREAD

**Issue by raghav1030** [UBA-GCOEN/StichHub#52]
The UI doesn't seems to be modern looking as  it lacks some smooth transition on buttons and some other elements

Also there is some issue with the "How it works for tailors" part
![StitchHub](https://github.com/UBA-GCOEN/StichHub/assets/94848646/a8181ec8-d0b7-4899-95a2-980d16736bb2)

I can contribute to the resolve the issue.

This is regarding the gssoc'23

**Comment by Naresh-chandanbatve** [comment]
Go for it @raghav1030

**Comment by raghav1030** [comment]
heyy there! I'm not being able to run it on my local machine. after forking, cloning when i do npm install , the dependencies are not getting installed. I read the readme and it says i have to enter google api key but i don't have one. Please help me with it?

**Comment by raghav1030** [comment]
I'm finding  it difficult to run the repo on my local machine. 
When i do npm run dev it shows : 

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\91767\Desktop\StichHub\client\StichHub\node_modules@jridgewell\sourcemap-codec\dist\sourcemap-codec.mjs' imported from C:\Users\91767\Desktop\StichHub\client\StichHub\node_modules\magic-string\dist\magic-string.es.mjs
Did you mean to import @jridgewell/sourcemap-codec/dist/sourcemap-codec.umd.js?
at new NodeError (node:internal/errors:387:5)
at finalizeResolution (node:internal/modules/esm/resolve:429:11)
at moduleResolve (node:internal/modules/esm/resolve:1006:10)
at defaultResolve (node:internal/modules/esm/resolve:1214:11)
at nextResolve (node:internal/modules/esm/loader:165:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
at link (node:internal/modules/esm/module_job:75:36)

I think the following error can be due to : 
1. api keys that are needed to be inserted in .env file. I don't knnow how to find them.
2. when i do npm install , there are some dependency warning that come as  - 

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-reconciler@0.26.2
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN react@"^18.2.0" from the root project
npm WARN 64 more (@emotion/react, @emotion/styled, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^17.0.2" from react-reconciler@0.26.2
npm WARN node_modules/ink/node_modules/react-reconciler
npm WARN react-reconciler@"^0.26.2" from ink@3.2.0
npm WARN node_modules/ink
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN peer react@"^17.0.2" from react-reconciler@0.26.2
npm WARN node_modules/ink/node_modules/react-reconciler
npm WARN react-reconciler@"^0.26.2" from ink@3.2.0
npm WARN node_modules/ink


Please help me with it...

**Comment by Naresh-chandanbatve** [comment]
Try to manually install the package which is not found 
With npm install packagename

**Comment by vk20july** [comment]
can i work on this under gssoc'23

**Comment by raahul131** [comment]
Hey  @raghav1030, Can you please assign this to me. I love to changes in the buttons and cards to look better and attractive hover effects and transition effect which is eye catcher for the user.
