### ISSUE TITLE
BUG: Active element in navbar

### ISSUE THREAD

**Issue by Akanksha-202** [UBA-GCOEN/StichHub#521]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Navbar component does not highlight the active element when switching to a different component mentioned in the navbar.

### Add ScreenShots

![Screenshot 2023-07-21 114431](https://github.com/UBA-GCOEN/StichHub/assets/100708686/121957ce-5cc5-43e6-89a1-f5e4786590fb)

I am at the Testimonial section but the navbar doesn't make it an active element.
It works well in mobile size:
![image](https://github.com/UBA-GCOEN/StichHub/assets/100708686/73a7e08f-0f3f-43d7-9b2e-2adfb5fe66d9)

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Naresh-chandanbatve** [comment]
it is resolved 
#553
