### ISSUE TITLE
Styling: Unorganised button and text

### ISSUE THREAD

**Issue by Soulpurr** [UBA-GCOEN/StichHub#53]
![Screenshot_2023-05-22-19-33-44-34_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/UBA-GCOEN/StichHub/assets/92094765/50fbedde-f2cf-40b5-96ef-941602e925e5)
![Screenshot_2023-05-22-19-33-39-42_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/UBA-GCOEN/StichHub/assets/92094765/349f1d22-0409-4df4-a73e-eed25c7780e3)

You can see in screenshot that get started button is taking too much height and our services should be in one line.
Please assign this issue to me under gssoc'23

**Comment by Naresh-chandanbatve** [comment]
Fix the button 
Our services is fine 
@Soulpurr

**Comment by Soulpurr** [comment]
Ok I will do it by today

**Comment by Soulpurr** [comment]
I have create a pull request. Can you approve it
