### ISSUE TITLE
 Initialize Commit Lint and ESLint 🚀

### ISSUE THREAD

**Issue by Nishitbaria** [UBA-GCOEN/StichHub#531]
**Issue Description:**
We need to set up Commit Lint and ESLint in our repository to ensure consistent code comments and enforce best practices across the codebase. This will help us maintain a high level of code quality, improve collaboration, and streamline the code review process. By using these tools, we can catch potential issues early, adhere to coding standards, and reduce the chances of introducing bugs into the codebase.

**Commit Lint:**
Commit messages are essential for providing clear and concise information about changes made to the code. Commit Lint is a tool that enforces a specific format for commit messages, making it easier to understand the purpose of each commit at a glance. This helps other developers and team members to quickly comprehend the changes introduced in the codebase without diving into the details.

**ESLint:**
ESLint is a powerful tool for identifying and fixing common coding errors and enforcing code style and best practices. It ensures that the code follows a consistent and maintainable structure, reducing the potential for bugs and making it easier for multiple developers to work on the same codebase.

**Expected Steps:**
1. Set up Commit Lint to enforce commit message standards.
2. Configure ESLint to follow the appropriate coding rules and conventions.
3. Integrate both Commit Lint and ESLint into our pre-commit hooks to ensure every commit adheres to the defined standards before being pushed to the repository.
4. Document the guidelines for writing commit messages and coding practices in the project's README or CONTRIBUTING.md file.

**Benefits:**
- Consistent and informative commit messages.
- Improved code quality and maintainability.
- Reduced chances of introducing bugs.
- Better collaboration among team members.
- Easier onboarding for new developers.
- Streamlined code review process.

**Additional Notes:**
Before proceeding with the implementation, we should decide on the specific commit message format and ESLint rules that align with the best practices of our project. This might include adhering to conventional commit message standards, defining ESLint rules for code style, and possibly incorporating specific plugins or configurations depending on the project's technology stack.

**Comment by harshitkandpal** [comment]
Step 1: Install Commit Lint and ESLint

Install Commit Lint and Commit Lint Configuration:


npm install --save-dev @commitlint/{config-conventional,cli}
Install ESLint and ESLint Configurations:


npm install --save-dev eslint eslint-config-{airbnb-base,prettier} eslint-plugin-import eslint-plugin-prettier prettier
Step 2: Create Configuration Files

Create a .commitlintrc.js file in the root of your project and add the following configuration for conventional commit messages:


module.exports = {extends: ['@commitlint/config-conventional']};
Create an .eslintrc.js file in the root of your project and configure ESLint rules. You can use the following as a starting point:


module.exports = {
  extends: ['airbnb-base', 'plugin:prettier/recommended'],
  plugins: ['import', 'prettier'],
  rules: {
    // Your custom ESLint rules and overrides can go here
  },
};
Step 3: Set Up Pre-commit Hooks

Install Husky to set up pre-commit hooks:


npm install --save-dev husky
Add a "precommit" script in your package.json to run Commit Lint and ESLint before committing:


"scripts": {
  "precommit": "npm run lint && npm run commitlint",
  "commitlint": "commitlint --from=HEAD~1",
  "lint": "eslint ."
}


if this steps can solve the then can i work on it ?

**Comment by Nishitbaria** [comment]
> Step 1: Install Commit Lint and ESLint
> 
> Install Commit Lint and Commit Lint Configuration:
> 
> npm install --save-dev @commitlint/{config-conventional,cli} Install ESLint and ESLint Configurations:
> 
> npm install --save-dev eslint eslint-config-{airbnb-base,prettier} eslint-plugin-import eslint-plugin-prettier prettier Step 2: Create Configuration Files
> 
> Create a .commitlintrc.js file in the root of your project and add the following configuration for conventional commit messages:
> 
> module.exports = {extends: ['@commitlint/config-conventional']}; Create an .eslintrc.js file in the root of your project and configure ESLint rules. You can use the following as a starting point:
> 
> module.exports = { extends: ['airbnb-base', 'plugin:prettier/recommended'], plugins: ['import', 'prettier'], rules: { // Your custom ESLint rules and overrides can go here }, }; Step 3: Set Up Pre-commit Hooks
> 
> Install Husky to set up pre-commit hooks:
> 
> npm install --save-dev husky Add a "precommit" script in your package.json to run Commit Lint and ESLint before committing:
> 
> "scripts": { "precommit": "npm run lint && npm run commitlint", "commitlint": "commitlint --from=HEAD~1", "lint": "eslint ." }
> 
> if this steps can solve the then can i work on it ?

  Yes You Can

**Comment by Naresh-chandanbatve** [comment]
yes you can @harshitkandpal
