### ISSUE TITLE
BUG: Some extra line are coming on hover in "HOW IT WORKS FOR TAILORS ?" section

### ISSUE THREAD

**Issue by ManashAnand** [UBA-GCOEN/StichHub#537]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

I am exploring the web app when I found that some extra line are coming on hovering in "HOW IT WORKS FOR TAILORS ?"  section 
after some time I figure out that on hovering in the line .
We get this effect ( you can see it in screenshot section )
Which is not looking good and overall is a bug in design .

I would like to work on this issue.
Please assign it to me.

### Add ScreenShots

![Screenshot 2023-07-30 222716](https://github.com/UBA-GCOEN/StichHub/assets/91553087/bffe3049-bffe-4ad7-a1f3-a223cf01f8c1)
![Screenshot 2023-07-30 222502](https://github.com/UBA-GCOEN/StichHub/assets/91553087/bac7b89e-db3d-4840-8612-3b037cc10f0d)
![Screenshot 2023-07-30 222705](https://github.com/UBA-GCOEN/StichHub/assets/91553087/d13f940c-567c-4997-8f91-28d3984e484f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by tmsagarofficial** [comment]
I would like to work on this issue if no one else is working on it currently. PLS assign it to me when possible
