### ISSUE TITLE
Dress Change Button Not working in width == 768px

### ISSUE THREAD

**Issue by iasadk** [UBA-GCOEN/StichHub#54]
#### Dress Change Button is not properly functioning in tablet mode. On the other Screen, the button is working perfectly fine and the alignment of the image is also not proper on the tablet screen size. 
Below is the demonstration of the bug 👇
https://github.com/UBA-GCOEN/StichHub/assets/89456039/0ff7e7ed-a31c-4ec8-812e-03c07e8d5fdf

Hope you understand it. Kindly assign this issue to me I would like to work on it.

**Comment by Naresh-chandanbatve** [comment]
Go for it @iasadk

**Comment by iasadk** [comment]
PR raised For the issue
[PR link](https://github.com/UBA-GCOEN/StichHub/pull/69)
