### ISSUE TITLE
bug: Not able to type in describe your concern section

### ISSUE THREAD

**Issue by Soulpurr** [UBA-GCOEN/StichHub#55]
![scrnli_22_05_2023_19-34-46](https://github.com/UBA-GCOEN/StichHub/assets/92094765/33e0344a-ff6f-436c-b9df-7af324944ce4)
Please assign this issue to me under gssoc'23.I will fix it

**Comment by Naresh-chandanbatve** [comment]
Which device are you using?

**Comment by Soulpurr** [comment]
android but this issue is in both android and windows

**Comment by Soulpurr** [comment]
@UBA-GCOEN can you just approve and assign this issue to me under gssoc'23?

**Comment by Naresh-chandanbatve** [comment]
Sure @Soulpurr go for it.
