### ISSUE TITLE
[STYLE CHANGE] Change of twitter logo in footer section

### ISSUE THREAD

**Issue by varunlmxd** [UBA-GCOEN/StichHub#554]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Description:

Replacement of twitter bird logo to new X logo

### Reason for Change:

Twitter has recently changed its logo

### Current Styling:

Only change of while bird logo to white X logo

### Proposed Styling:

change of while bird logo to white X logo and on hovered it changes to black and while logo

### Tick the appropriate boxes as per your choice

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by 4genie** [comment]
I would like to work on it, can you assign this task to me
