### ISSUE TITLE
BUG: Text not aligned properly in the buttons on Home Page

### ISSUE THREAD

**Issue by SaketKaswa20** [UBA-GCOEN/StichHub#562]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

The text is not correctly aligned in the center of the button.

### Add ScreenShots

![Screenshot from 2023-08-14 22-58-46](https://github.com/UBA-GCOEN/StichHub/assets/105808363/ff052d4c-1713-4a9d-a2b9-ec98e29ad1a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by GOKULNATH-RS** [comment]
Can I work on this?

**Comment by GOKULNATH-RS** [comment]
@SaketKaswa20 I've completed the work and opened a PR which is open. Can you review this and merge if it is proper

**Comment by SaketKaswa20** [comment]
I have just raised the issue. I am not the maintainer :)
