### ISSUE TITLE
Fix Frontend

### ISSUE THREAD

**Issue by Ayushhgupta39** [UBA-GCOEN/StichHub#57]
<img width="554" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/96309609/b47244f6-a6e6-4bab-9bdd-46ed3a46c8af">
I want to fix this frontend issue, to make the website look more professional and better looking.

**Comment by Harshajny** [comment]
Hi
I wish to work on this issue. Can you please assign it to me.

**Comment by AnuragK2** [comment]
I'm a gssoc'23 contributor. I would also like to contribute to the same issue. Kindly assign me this issue.

**Comment by Naresh-chandanbatve** [comment]
Have you check is there any duplicate issue and the issue is not solved in current active version

**Comment by Ayushhgupta39** [comment]
> Have you check is there any duplicate issue and the issue is not solved in current active version

I guess the issue is related to screen-size as when I inspect it, it looks fine but when I see it normally, it overlaps the content.

**Comment by Naresh-chandanbatve** [comment]
> > Have you check is there any duplicate issue and the issue is not solved in current active version
> 
> I guess the issue is related to screen-size as when I inspect it, it looks fine but when I see it normally, it overlaps the content.

Can you solve it for standard screens

**Comment by Ayushhgupta39** [comment]
> > > Have you check is there any duplicate issue and the issue is not solved in current active version
> > 
> > 
> > I guess the issue is related to screen-size as when I inspect it, it looks fine but when I see it normally, it overlaps the content.
> 
> Can you solve it for standard screens

It seems solved now, Thus closing the issue. Thank you.
