### ISSUE TITLE
Sign In with Google Functionality is not working

### ISSUE THREAD

**Issue by crocmons** [UBA-GCOEN/StichHub#58]
Sign In with Google Functionality is not working both tailor and customer registration also the sign in page
![project-8](https://github.com/UBA-GCOEN/StichHub/assets/106610322/ea4ba4e4-8d5a-40b0-8a8a-539735132eae)

**Comment by Akanksha-202** [comment]
Please assign this issue to me, already have made a successful merge of a similar type!
Under GSSoC'23 label :)

**Comment by crocmons** [comment]
Please assign this issue to me
Under GSSoC'23 label :)

**Comment by Akanksha-202** [comment]
I was saying this from user's pov, they will not clone the repo and then add their API keys

**Comment by Naresh-chandanbatve** [comment]
What changes are you proposing to do
We have already added the google authentication but we have not included it yet in hosted site that you are seeing We will add it in production

**Comment by Naresh-chandanbatve** [comment]
Please leave tour proposed solution here so that we can assign it

**Comment by crocmons** [comment]
after adding the client id .env file it gives us same issue

**Comment by Akanksha-202** [comment]
Exactly, if a user comes to your website, it should be connected with Firebase fully with your API keys inside an env file which is not shared but the hosted site should work perfectly.

**Comment by Siddhant-Patil0203** [comment]
Hey @crocmons and @Akanksha-202,
Thank you for noticing the Google Auth sign issues in the deployed version of stichHub i.e. https://stichhub-chi.vercel.app
Actually, Google Auth was taking time to configure this domain, therefore it took time to showcase on the deployed site but I guess now it's working, you can check once.

Customer Side :
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/2cdc6378-ef15-4cb9-85ce-3fcb0af0f29f)

Tailor Side :
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/c18253db-b837-4ddc-aace-8dcf4094c9b1)

Please note that, If you want to use Google auth in your local environment, then you have to enter your Google auth key to use it.

Thank you for raising the issue though.
