### ISSUE TITLE
Fixing the icons in the homepage

### ISSUE THREAD

**Issue by mohammadshaad** [UBA-GCOEN/StichHub#61]
Hey @Naresh-chandanbatve, 

I've noticed that the icons on the homepage don't align properly. Some of them appear stretched while others seem to be misaligned, which doesn't adhere to the consistent style of the entire website. I would like to address this issue and make the necessary improvements. As a GSSoC'23 contributor, I kindly request to be assigned this task.

**Comment by Naresh-chandanbatve** [comment]
Can you provide screenshots and check is there is not any already opened issue and issue isn't solved already

**Comment by Siddhant-Patil0203** [comment]
@mohammadshaad ??

**Comment by mohammadshaad** [comment]
@Naresh-chandanbatve @Siddhant-Patil0203 no this issue is fresh and hasn't been addressed by anybody else

**Comment by Siddhant-Patil0203** [comment]
> @Naresh-chandanbatve @Siddhant-Patil0203 no this issue is fresh and hasn't been addressed by anybody else

Can you pls provide the Screenshot, so that I can understand the issue better 😕

**Comment by Siddhant-Patil0203** [comment]
> > @Naresh-chandanbatve @Siddhant-Patil0203 no this issue is fresh and hasn't been addressed by anybody else
> 
> Can you pls provide the Screenshot, so that I can understand the issue better 😕

@mohammadshaad
