### ISSUE TITLE
Adding socials hover effect to the contributors

### ISSUE THREAD

**Issue by Akanksha-202** [UBA-GCOEN/StichHub#62]
![image](https://github.com/UBA-GCOEN/StichHub/assets/100708686/99196b15-d6dc-49f1-b98a-3935601dcb33)
Allow users to connect with the creators of the website.
Adding a hover effect over their image for their socials. HOver effect will emerge from down to up along with GitHub/LinkedIn socials of the contributors/creators.

Please assign this issue to me under GSSoC'23 label :)

**Comment by Naresh-chandanbatve** [comment]
@Siddhant-Patil0203 
Any suggestions

**Comment by Siddhant-Patil0203** [comment]
> ![image](https://github.com/UBA-GCOEN/StichHub/assets/100708686/99196b15-d6dc-49f1-b98a-3935601dcb33)
> Allow users to connect with the creators of the website.
> Adding a hover effect over their image for their socials. HOver effect will emerge from down to up along with GitHub/LinkedIn socials of the contributors/creators.
> 
> Please assign this issue to me under GSSoC'23 label :)

You mean to say, when someone hovers the images the social media handle should be on the right side of the image?? 
@Akanksha-202

**Comment by Akanksha-202** [comment]
Not on the right side but over the image.
Something like this, ![IMG_20230524_094320.jpg](https://github.com/UBA-GCOEN/StichHub/assets/100708686/9f26c4b7-2c65-4ed5-8231-6d1641cb5dab)

Can be more adjustments according to your preference and website's theme.

**Comment by Siddhant-Patil0203** [comment]
Okay @Akanksha-202 go for it
