### ISSUE TITLE
Navbar Icons on small screen

### ISSUE THREAD

**Issue by villAsh** [UBA-GCOEN/StichHub#66]
On small screen the navbar Icon gets too small and it is kind of not visible,
I want to fix this please assign me this under GSSoC'23

**Comment by villAsh** [comment]
![Screenshot 2023-05-24 113639](https://github.com/UBA-GCOEN/StichHub/assets/50195101/b8c9b849-afca-475f-ae91-1be9bf0e47a4)
see this, when the screen gets smaller it gets very small

**Comment by Naresh-chandanbatve** [comment]
@Siddhant-Patil0203 have a look

**Comment by Siddhant-Patil0203** [comment]
Okay @villAsh go for it

**Comment by Siddhant-Patil0203** [comment]
@villAsh what's the status ?
