### ISSUE TITLE
Add hover state to the buttons in the website

### ISSUE THREAD

**Issue by Arunjagan12** [UBA-GCOEN/StichHub#68]
Adding hover state to the buttons will create a better user experience.**I am a gssoc'23 contributor**.
I would like to contribute to this issue.

**Comment by AnuragK2** [comment]
I'm a gssoc'23 contributor. I would also like to contribute to the same issue. Kindly assign me this issue.

**Comment by Naresh-chandanbatve** [comment]
Which buttons will you exactly change

**Comment by kunal-2002** [comment]
I understand what has to be done here, so assign me this issue under GSSOC'23

**Comment by Siddhant-Patil0203** [comment]
> Which buttons will you exactly change

@Arunjagan12
