### ISSUE TITLE
Contact Us Section Not Responsive

### ISSUE THREAD

**Issue by premsaivarmachekuri** [UBA-GCOEN/StichHub#7]
Hi @Naresh-chandanbatve, I have identified an issue related to the responsiveness of the "Contact Us" section.

**Problem:**
The current implementation of the "Contact Us" section lacks responsiveness, causing it to display improperly on different devices and screen sizes. This issue hampers user experience and may result in difficulty for users trying to access the contact information or interact with the section.
![image](https://github.com/UBA-GCOEN/StichHub/assets/110842297/4055d09c-a7a8-4a2b-9a1a-15fbdd3c68f3)
**Approach:**
To address this problem, I propose the following steps:

1) Responsive Design: Implement responsive CSS techniques to ensure that the "Contact Us" section adapts smoothly to various screen sizes, such as mobile, tablet, and desktop views. This will enhance the usability and accessibility of the section.

2) Media Queries: Utilize CSS media queries to define specific styles for different breakpoints, enabling the section to adjust its layout and content dynamically based on the device or screen size. This approach will ensure that the "Contact Us" section remains legible and user-friendly across various devices.

**Additional Information:**
 As a participant in GSSOC3 with prior experience in similar projects, I aim to apply my expertise and prior experience in addressing similar issues to enhance the responsiveness of the "Contact Us" section. This will contribute to the overall improvement of the project and enhance the user experience.

Thank you for considering my involvement in resolving this issue. I look forward to collaborating with the organization to ensure the successful implementation of the necessary changes.

Best regards,
Premsai Varma

**Comment by Naresh-chandanbatve** [comment]
Go for it @premsaivarmachekuri ..

**Comment by premsaivarmachekuri** [comment]
Working on it Naresh.

**Comment by vk20july** [comment]
I want to work on this issue under gssoc'23

**Comment by Siddhant-Patil0203** [comment]
okay @vk20july go ahead

**Comment by vk20july** [comment]
@Siddhant-Patil0203 sir can you check is it still non-responsive as i think it is responsive in all different size

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 sir can you check is it still non-responsive as i think it is responsive in all different size

Yup it is responsive now 🙂
