### ISSUE TITLE
Improve SEO, Best Practices and Accessibility

### ISSUE THREAD

**Issue by rahulaarora** [UBA-GCOEN/StichHub#70]
- [x] There is not a similar existing open issue
- [x] This is under GSSoC'23

# Screenshots
## Lighthouse Results of [StichHub](https://github.com/UBA-GCOEN/StichHub)
<img width="496" alt="Screenshot 2023-05-23 at 3 23 34 PM" src="https://github.com/UBA-GCOEN/StichHub/assets/24794534/129d19d8-2a8d-4545-95f9-a6732ad41172">

## Accessibility issues
<img width="827" alt="Screenshot 2023-05-23 at 3 24 49 PM" src="https://github.com/UBA-GCOEN/StichHub/assets/24794534/61e33030-2603-412e-9c4e-a977227c5ac9">

## Best Practices issues
<img width="828" alt="Screenshot 2023-05-23 at 3 25 27 PM" src="https://github.com/UBA-GCOEN/StichHub/assets/24794534/52606728-819c-4c85-b750-021d5429f7bd">

## SEO issues
<img width="821" alt="Screenshot 2023-05-23 at 3 25 52 PM" src="https://github.com/UBA-GCOEN/StichHub/assets/24794534/7cb0332b-8212-4118-bb05-7e758bac158c">

**Comment by rahulaarora** [comment]
I am a GSSoC'23 contributor and I would like to work on this issue please assign it to me.

**Comment by Naresh-chandanbatve** [comment]
Go for it @rahulaarora
