### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by shraddha761** [UBA-GCOEN/StichHub#71]
![Screenshot 2023-05-21 160801](https://github.com/UBA-GCOEN/StichHub/assets/106100728/6002c2cd-347f-4ca0-901b-6f4da3e69e75)

Adding this badges to readme makes it more attractive assign me this issue under GSSOC'23 label

**Comment by Siddhant-Patil0203** [comment]
Okay @shraddha761, I am assigning you this issue.
