### ISSUE TITLE
Sticking up the NavBar so it don't overlap the text.

### ISSUE THREAD

**Issue by AditiSingh2003** [UBA-GCOEN/StichHub#75]
The navbar in the website is overlapping the text in various places.
![Screenshot (28)](https://github.com/UBA-GCOEN/StichHub/assets/97729662/78d17936-67eb-4b63-ac0c-ddac8f9d3a96)
![Screenshot (27)](https://github.com/UBA-GCOEN/StichHub/assets/97729662/1717a677-fef9-47cd-8ceb-5bfa4ba13664)

So not to Overlap of the navbar will make the UI clean and easy to read.

**Comment by Abhishekraj8757** [comment]
Can you assign me the issue under GSSOC.
Currently the position of the navbar is fixed it can be made non fixed and the ui will clean.

**Comment by rahulaarora** [comment]
this has been fixed already @Abhishekraj8757 @AditiSingh2003

**Comment by Naresh-chandanbatve** [comment]
It is resolved
