### ISSUE TITLE
Overlapping the heading to text.

### ISSUE THREAD

**Issue by AditiSingh2003** [UBA-GCOEN/StichHub#76]
In many places in the website the heading is overlapping the text. 
![Screenshot (27)](https://github.com/UBA-GCOEN/StichHub/assets/97729662/36d3b473-393a-4a92-8572-7484d3a296c6)
![Screenshot (28)](https://github.com/UBA-GCOEN/StichHub/assets/97729662/08e2ea04-e9f5-4cc2-b9f5-3919da8c7896)

**Comment by Naresh-chandanbatve** [comment]
Already resolved
