### ISSUE TITLE
Footer Year should be Dynamic 

### ISSUE THREAD

**Issue by crocmons** [UBA-GCOEN/StichHub#78]
**In the Footer component the year should be Dynamic so that every year it will be automatically updated** Plz assign me this issue as GSSOC'23 Contributor.

![Screenshot (333)](https://github.com/UBA-GCOEN/StichHub/assets/106610322/81066b0a-174c-43c7-9a99-231ce759e94f)

**Comment by Naresh-chandanbatve** [comment]
Go for it @crocmons
