### ISSUE TITLE
Fix Grammar in About Us Section

### ISSUE THREAD

**Issue by Sriparno08** [UBA-GCOEN/StichHub#79]
I have noticed a typo in the About Us Section.

![Screenshot 2023-05-23 210430](https://github.com/UBA-GCOEN/StichHub/assets/89148144/a6c541c6-31ed-4e60-9e61-448c97a8aff0)

Fix:

`benifits` -> `benefits`

**Comment by Sriparno08** [comment]
I would like to work on this as part of GSSoC'23.

**Comment by Siddhant-Patil0203** [comment]
Hey @Sriparno08 
Apart from the typo can you also update the context into these?

**We're a team of enthusiasts, hoping to bring the tailoring community online and introduce them to the benefits of online business, while also providing customers with a convenient and easy way to find tailors who can meet their needs.**

**Comment by Siddhant-Patil0203** [comment]
Okay I am Assiging you this issue @Sriparno08
