### ISSUE TITLE
Lack of Responsiveness and Misalignment in the "Our Services" Section

### ISSUE THREAD

**Issue by premsaivarmachekuri** [UBA-GCOEN/StichHub#8]
Hi @Naresh-chandanbatve,

I have identified an issue related to the responsiveness and alignment of the "Our Services" section.

**Problem:**
The current implementation of the "Our Services" section lacks responsiveness, causing inconsistent display across different devices and screen sizes. Additionally, there is a noticeable misalignment within the section's layout, impacting its visual presentation and user experience.

![image](https://github.com/UBA-GCOEN/StichHub/assets/110842297/b79f3a41-777e-491f-aa3b-ca356eee8c0f)

**Approach:**
To address this problem, I propose the following steps:

1) Implement Responsive Design: Apply responsive design principles to ensure that the "Our Services" section adapts seamlessly to diverse screen sizes, including mobile, tablet, and desktop views. This approach will enhance accessibility and provide an optimal user experience across all devices.

2) Correct Misalignment: Identify and rectify the misalignment within the "Our Services" section's layout. This involves aligning the elements precisely, maintaining consistent spacing, and ensuring visual harmony within the section.

**Additional Information:**
As a participant in GSSOC3 with experience in similar projects, I am confident in my ability to effectively address the responsiveness and alignment issues in the "Our Services" section. By implementing these improvements, we can enhance the overall refinement and usability of the project.

Thank you for considering my involvement in resolving this issue. I am eager to collaborate with the team to ensure the successful implementation of the necessary improvements.

Best regards,
Premsai Varma

**Comment by Naresh-chandanbatve** [comment]
Go for it @premsaivarmachekuri 
But you have to create different prs for different issues..

**Comment by premsaivarmachekuri** [comment]
Noted Naresh 👍

**Comment by vk20july** [comment]
I want to work on this issue under gssoc'23

**Comment by Siddhant-Patil0203** [comment]
@vk20july I am assigning you this

**Comment by vk20july** [comment]
@Siddhant-Patil0203 everything is responsive in ```our service``` section expect the title ***our service*** do you want ***our service*** text to be at the center while reducing the size of website?

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 everything is responsive in ```our service``` section expect the title ***our service***. Do you want ***our service*** text to be at the center while reducing the size of website?

No not required as of now
