### ISSUE TITLE
Add navigation links in CustomersPage

### ISSUE THREAD

**Issue by VSatwika** [UBA-GCOEN/StichHub#80]
- In the customers page, the navbar elements do not have links directing to their pages.
 - The Home element is clickable but does not redirect to home page in the navbar
 - Log Out does not work
  
   I would like to solve these issues by adding the appropriate links. 
   Could this be assigned to me @Naresh-chandanbatve
   I am contributing as a part of GSSoC'23.

**Comment by Siddhant-Patil0203** [comment]
Hey @VSatwika 
Can you elaborate on your issue and provide some screenshots, So that I can understand it better?

**Comment by VSatwika** [comment]
> Hey @VSatwika Can you elaborate on your issue and provide some screenshots, So that I can understand it better?

Sure.

![StichHub](https://github.com/UBA-GCOEN/StichHub/assets/112561024/a2943793-2617-481e-90f7-24ae6f1535b7)

- Here the navbar is not responsive. Except the Home element, the other elements of the navbar are not responsive/clickable.
- Upon clicking, the Home element does not redirect to Home page, it remains in the same page.
- I would to add correct navigation links to all the elements in the navbar.

**Comment by Naresh-chandanbatve** [comment]
Go for it @VSatwika

**Comment by AmanKumarVlgs** [comment]
Hey @Naresh-chandanbatve, I'm new here and I am a UI/UX Designer I want to contribute at @StichHub.Where I can find your Figma file?
