### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by VSatwika** [UBA-GCOEN/StichHub#81]
- I would like to request the addition of a code of conduct to the repository.
 - Having a code of conduct is essential to establish a welcoming and inclusive environment for all contributors.
 - It provides clear guidelines for expected behavior and helps create a safe and respectful space for collaboration.
 - I am contributing as a part of GSSoC'23. Could you assign this issue to me @Naresh-chandanbatve ?

**Comment by Siddhant-Patil0203** [comment]
Hey @VSatwika,
I am Assigning you this issue.
