### ISSUE TITLE
Add blog link in README

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [UBA-GCOEN/StichHub#86]
Wanted to add a blog link in Readme

Blog link : https://medium.com/@sidd0203/stichhub-38d01da27f37

**Comment by Siddhant-Patil0203** [comment]
> I can add this sir. Please assign me this issue .happy to work with you

Okay @codewithnadeem14502 where are you planning to add a blog section to Readme, can you pls tell me this with screenshots pls, then I will assign you this issue

**Comment by 3kori** [comment]
@Siddhant-Patil0203 I would like to be assigned to this issue. @codewithnadeem14502 are you still working on it?

**Comment by Naresh-chandanbatve** [comment]
@3kori go for it

**Comment by 3kori** [comment]
![blogpost](https://github.com/UBA-GCOEN/StichHub/assets/127242906/62a9b83e-8c4e-4e51-bba5-1428daac9d9b)

I was planning on adding the blog link in a section of its own right before the feedback section or, 

![Blog](https://github.com/UBA-GCOEN/StichHub/assets/127242906/b9b59cd5-c094-4fe8-a629-445a3ddb71e0)

after the last sentence on the stichhub description.

**Comment by 3kori** [comment]
Which one would be fine? @Naresh-chandanbatve

**Comment by Siddhant-Patil0203** [comment]
> ![blogpost](https://user-images.githubusercontent.com/127242906/241390904-62a9b83e-8c4e-4e51-bba5-1428daac9d9b.png)
> 
> I was planning on adding the blog link in a section of its own right before the feedback section or,
> 
> ![Blog](https://user-images.githubusercontent.com/127242906/241390881-b9b59cd5-c094-4fe8-a629-445a3ddb71e0.png)
> 
> after the last sentence on the stichhub description.

Add it before the feedback section

**Comment by 3kori** [comment]
Ok, on it.
