### ISSUE TITLE
[Bug] local setup test

### ISSUE THREAD

**Issue by Ghat0tkach** [UBA-GCOEN/StichHub#9]
Current :The navbar isnt responsive at the moment
![image](https://github.com/UBA-GCOEN/StichHub/assets/59855919/526177a1-dca1-4e65-8917-5196679d59ce)

Expected behavior:
![image](https://github.com/UBA-GCOEN/StichHub/assets/59855919/0d799025-a853-4407-8133-c3d436f19cc3)

i would like to work on this issue as part of gssoc-23

**Comment by Naresh-chandanbatve** [comment]
Go for it @Ghat0tkach

**Comment by Ghat0tkach** [comment]
@Naresh-chandanbatve  i think the issue is already resolved by other's 😅😅

**Comment by Naresh-chandanbatve** [comment]
Yes in #65

**Comment by Naresh-chandanbatve** [comment]
Have you done the changes

**Comment by Naresh-chandanbatve** [comment]
If it is the case then make a pr we will see wich one to merge 
Please mention this issue # in pr

**Comment by Ghat0tkach** [comment]
Actually im having problem in setting up the repo , npm install isnt working and idk about the env api keys and all😅

**Comment by Naresh-chandanbatve** [comment]
What error is it giving
Try to delete package-lock.json 
Rebuild by npm install
Only package-lock.json
