### ISSUE TITLE
Hover Effect on OUR SERVICES section 

### ISSUE THREAD

**Issue by Prajwal0225** [UBA-GCOEN/StichHub#96]
**I would like to propose adding a hover effect to the "OUR SERVICES" section of the repository. By adding a hover effect, we can enhance the visual appeal of the section and make it more engaging for customers.**

**Motivation:**
The addition of a hover effect in the "OUR SERVICES" section will improve the overall user experience by providing a visually interactive element. When customers hover over the services, it will create an eye-catching effect that grabs their attention and encourages further exploration.

![our services](https://github.com/UBA-GCOEN/StichHub/assets/103810119/35b90738-0c25-4f18-8d1b-49aa3b99cab3)

**If you like my suggestion can you please assign this issue to me?**
**I would love to contribute to this project** 😇...

**Comment by Avinash905** [comment]
If no one is working on this issue then please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Siddhant-Patil0203** [comment]
> If no one is working on this issue then please assign me this issue so that I can work on this issue under **GSSOC'23**.

Okay @Avinash905 go for it
